#include"v.a"//L(3,cF,gg(Ai,Xi),IA,U3)L(3,nf,1<<31&(j6)Xi,U3)
#define M2(K) h(8/K,ik=K;j(k,ii=2*h*k+j;Ri=_P(Ri,r(Rk,Rk=P_(Ri,r)))))
U(i_,i(n4(n),Ub=b2(m==Ri);P(b,l(n,16*i|iu(b))))n,im,in,IR)Z(s2,i(n,Ri=i_(Xi,n,A)),IA,in,iR,iX)A(y2,A?G2(A,Xi):p2(*--X,15-I2))Z(f2,M2(1)M2(2)M2(4)M2(8),im,U3)
Z(gf,ee=n;h(n,i(n,*R++=h/e;*R++=i/e)),in,eR)L(6,gz,m-z2,im,in,IR)y(gi,I2|16*i)y(ge,EI(I2|16*i)/(e2)n)y(gr,(e6)(E1|b(23)&(i6)JJ())-1)
z(qe,q(Xi))z(Re,l_(Xi))z(Ee,_l(Xi))z(ig,C(i6,X4))z(ie,IE(Xi))z(ei,EI(Xi))L(6,d0,Xi,U3)
#define ft(m,s,S,t,T) T##f(S##t,i(m,x=S##T(x,r##m(i,x)))x)U(s##t,S##t(r(z0,i(n##m(n),r=S##T(r,Xi))))[b(m)],in,IX)Z(s##T,T##z=z0;R##m(z=z[15]+S##t(Xi)),U3)
ft(6,m,M,g,G)ft(4,m,M,i,I)ft(4,s,S,i,I)c(l2,<)c(g2,>)c(q2,==)a(ai,m+Xi)a(bi,m-Xi)a(ci,m*Xi)a(di,x((i1)m*Xi>>16,m>>16?Xi-(m>>16)*x:x))d(ae,e+Xe)d(be,e-Xe)d(ce,e*Xe)d(de,e/Xe)
A(aI,Ai+Xi)A(bI,Ai-Xi)A(cI,Ai*Xi)A(aE,Ae+Xi)A(bE,Ae-Xi)A(cE,Ae*Xi)A(dE,Ae/Xi)L(3,fd,C(j6,X5)<<32,U3)L(3,fe,C(j6,X5),U3)ab(af,qq)ab(df,P_)ab(ef,_P)
a(DE,(e2)m*Xe)A(EE,Ae*Xi/(1+_l(-Xi)))
#define e4(g,a,b,Y...) e(g,se(r(ze,n=n4(n);Ez[4]={};i(n/4,i(4,zi+=a*X++))i(n%4,r+=b Xi)i(4,r+=zi))),Y)
#define E4(g,a,b,Y...) Z(g,n=n4(n);i(n/4,Ez[4]={};h(m,i(4,zi+=a X[n*h+i]))X+=4;i(4,*R++=zi))i(n%4,Ri=r(ze,i(m,r+=b X[n*i])++X)),Y)
e4(sv,,,in,EX)e4(vv,*A++*,Ai*,EA,in,EX)E4(sm,,,im,in,IR,EX)E4(vm,A[h]*,Ai*,eA,im,in,IR,EX)e(v8,se(r(ze,i(n,r+=Ri*dot(Ai,Xi)))),eR,EA,in,EX)
Z(mv,i(m,Ri=vv(A+n/16*i,n,X)),EA,im,in,eR,EX)Z(m8,Vx[n/=64];i(n,x[i]=C(g6,X8))e2*e=A+m*n;i(m,Ri=v8(e+n*i,A+n*i,n,x)),EA,im,in,eR,EX)Z(mm,i(l,vm(A+m*i,m,n,R+n*i,X)),il,eA,im,in,IR,EX)
Z(Ze,ee=me(r(ze,i(n4(n),r=ME(r,Xi))));R4(_l(Xe-e))e=1/sv(n,R);R4(e*Xe),U3)Z(RE,ee=1/q(vv(X,n,X)/n-ze)[0];R4(e*Ae*Xi),IA,U3)
