a:[a_].[ch] makefile
	clang-13 -ffast-math -Os -oa a.c -nostdlib -w -ferror-limit=1 -fno-unwind-tables -mavx512f -mavx512vbmi 

#	clang-13 -ffast-math -Os -om a.c -nostdlib -w -fno-stack-protector -target arm64-apple-macos -fuse-ld=lld
#	clang-13 -ffast-math -Os -oa a.c -nostdlib -w -fno-unwind-tables -mavx2

