#define gx _(ua=g_(x)|(u)g_(x>>30)<<32;*(g*)&a)
#define t(t,i,e,g) c4(t-2,tc(i),ti(i),te(e),tg(g))
#define T(t,c,h,e,g) _x(R(t,nx,C4(t-2,i(nx,rc=c),i(nx,ri=h),i(nx,re=e),i(nx,rg=g))))
#define R(t,n,z) r(t_(t,n),z) //rrrtn bcieg  acd mnop |fgim rtuwx
#include"a.h"//ACDEMNOPS|FG  QRTUW (B) HIJKL UV [XYZ] At Cut Dot Equal F/Flip/flop G Max Num Order Prod Q Res Sum Type Write/work
void*malloc(),free(),*memcpy();long write(),read();int stat(),open(),close();int sprintf(char*,const char*s,...);
G(w_,write(f,sa,x))G(_w,read(f,sa,x))f(_h,close(x))F(h$,stat(sa,sx))F(h_,open(sa,x))f(W_,(u)malloc(x))f(_W,free((char*)x);0)G(mc,(u)memcpy(sf,sa,x))
ns(nw,w_(1,(u)s,n))f(w,127>x?nw(1,&x):_(ss=sx;Wh(*s)++s;nw(s-sx,sx)))f(s,in=0;X(n+=xc)n)nu(vc,++W;sx[nx++]=n;x)
Ze pi=3.1415927;Ze ei(unsigned x){return*(e*)&x;}u(te,4l<<61|(u)*(unsigned*)&x,e x)
#include<complex.h>
typedef float complex g;e sqrtf(e),expf(e),logf(e);Ze rf(e x){return 1/x;}g csqrtf(g),cexpf(g),clogf(g);Zg crf(g x){return 1/x;}
Zi N=1<<31,G=95<<23;i1(g_,i=(N/4&i)*4|(1<<29)-1&i;~N&i?G+i:0)i1(_g,~N&i?(N&i)/4|(1<<29)-1&m(G,i)-G:0)u(tg,unsigned*a=&x;5l<<61|_g(*a)|(u)_g(a[1])<<30,g x)
u(t_,ii=n<<l[t];W+=i;ux=W_(8+i+1);*xU=t<<24|n<<32;x+8,it,un)f(_t,W-=Nx;_W(x-8);0)f(r_,Ax?x:(++xr,x))f(_r,Ax?x:(1<<24)-1&xr?(--xr,x):_(if(!tx)X(_r(xu))_t(x)))
iu(a,tx?t(tx,ci,xe,xg):r_(xu))u(n,R(3,n,i(n,ri=i)),in)u(n$,R(3,n,i(n,ri=n-1-i)),in)nu(nz,ua=ix;R(ax,n,i(7+Nr>>3,ru=a)))f(v,r(t_(ax,1),*(u*)r=x))f(c1,v(tc(x)))
G(c,mc(t_(tx,a),x+(f<<lx),a<<lx))F(V,_a(R(tx,na+nx,mc(r,a,Na);mc(r+Na,x,Nx))))F(_C,_x(R(2,0,X(r=vc(a,V(r,xu))))))nu(cv,V(c1(n),x))
f(ind,_x(R(3,s(x),unsigned*s=sr;X(if(xc)*s++=i))))nu(ec,T1(n==xc))F(C,_a(T0(c(xi,(i+1<nx?xI[i+1]:na)-xi-1,a))))f(C_,ua=ec(sx[nx-1],x);a=_a(c(-1,na,a));*sa=1;C(x,ind(a)))
#define ue(t,z) _(x=t>ax?Ua(t,x):x;z)
#define uE(t,z) _(x=t>tx?Ut(t,x):x;z)
tu(Ua,t(t,ix,ix,4>ax?ix:ex))tu(Ut,T(t,xc,xc,xi,4>tx?xi:xe))
#define uu(e) _(if(aa!=ax)If(aa<ax,a=Ua(ax,a))x=Ua(aa,x);e)
#define UU(e) _a(it=aa?:ta;if(t!=tx)If(t<tx,a=aa?Ua(tx,a):Ut(tx,a))x=Ut(t,x);e)
#define b(g,t,a,v) f(g,ax?ue(t,a):uE(t,v))
#define B(g,o) b(g,4,5>ax?te(o##f(ex)):tg(c##o##f(gx)),5>ax?T4(o##f(xe)):T5(c##o##f(xg)))
#define ME(g,o) F(g,ax?aa?uu(tb(ia o ix)):M==g?M(_s(x),_s(a)):g(x,a):UU(_x(T1(ai o ci))))
#define SP(g,o) F(g,ax?aa?uu(ue(2,t(ax,ia o ix,ea o ex,ga o gx))):g(x,a):UU(uE(2,T(tx,ai o xc,ai o xi,ae o xe,ag o xg))))
b(_e,0,tb(!ix),T1(!ci))b(_s,2,t(ax,-ix,-ex,-gx),T(tx,-xc,-xi,-xe,-xg))b(d,4,tg(I*ex),T5(I*xe))B(_p,r)B(_l,exp)B(_q,sqrt)B(l_,log)
SP(S,+)SP(P,*)ME(M,>)ME(E,==)f(q1,1+ix?_q(x):tg(I))f(l1,1+ix?l_(x):tg(I*pi))
ns(k,mc(t_(2,n),(u)s,n))f($i,bs[12];k(sprintf(s,"%d",ix),s))
f($e,bs[12];k(sprintf(s,"%g",ex),s))f($g,bs[24];e a=ei(g_(x));e b=ei(g_(x>>30));!a?cv(46,$e(te(b))):!b?$e(te(a)):k(sprintf(s,"%g+.%g",a,b),s))
f($,px?c1('?'):ax?c3(m(3,ax)-3,$i(x),$e(x),$g(x)):2==tx?x:e($))f($_,Ax||!lx?$(x):tx?_C(32,e($)):c1('.'))f(wx,_x(nw(nx,sx)))f(w$,wx(vc(10,Ax||tx?$_(x):_C(10,e($_)))))
#define Qi(z) Qr(!a##z)Qt(3<a##z)Qd(0>i##z)
F(err,w(a);w(58);w(x);w(10);Q)F(A,QZ)F(A_,Qr(aa)A(a,x))F(_A,Qr(aa)QZ)F(F_,QZ)f(f_,Qr(ax)A(x,n$(nx)))f(_n,Qr(ax)_x(ti(nx)))f(_v,Qr(ax)_x(a(0,x)))
f(n_,Qi(x)n(ix))F(N$,Qi(a)QZ)F(_N,Qi(a)ax?nz(ia,x):_x(c(0,ia,x)))F(N_,Qi(a)ax?nz(ia,x):_x(c(ia,nx-ia,x)))F(V_,a=aa?v(a):a;x=ax?v(x):x;Qt(ta!=tx)_x(V(a,x)))
F(_S,S(a,_s(x)))F(_P,P(a,_p(x)))F(_M,M(x,a))F(_E,_e(E(a,x)))F(D,QZ)F(_$,QZ)F(_m,QZ)F(m_,QZ)f(o,QZ)f(_o,QZ)f(o_,_o(_e(x)))f(O,QZ)f(_O,QZ)
Z_// +  - *  %  &  |  <  >  =  ~  $ . !  @   ?  # _  ^ ,  *exp %log &Flip |flop <asc >desc =group ?nub ^order (#= #'=)
f[]={0,_s,_l,l1,F_,f_,_o,o_,O,_e, $,d,n_,_v,_O,_n,q1,o,v },F[]={S,_S,P ,_P,_m,m_,_M,M ,E,_E,_$,D,N$,A_,_A,_N,N_,0,V_};ns(is,st=s;Wh(*t)Pr(n==*t++,t-s)0)
f(z_,10>x-48?ti(x-48):26>x-97?r_(U[x-97]):is(x,"+-*%&|<>=~$.!@?#_^,"))us(z,ua=z_(*s++);!*s?a:x(z(s+!pa),Q(x)pa?f[a-1](x):F[z_(*s)-1](a,x)))
us(ps,i(13,in=is(" \"`;()[]{}'/\\"[i],s);Pr(n--,w((u)s);w(10);wx(vc(94,nz(n,tc(32))));w(10);Q))(u)s)
us(ws,ux=92==*s?(u)s:ps(s);Q(x)Q(x=es(sx))x?w$(x):0)us(ts,ux=ps(s);Q(x)in=1e6;uf=uz();i(n,Q(_r(es(sx))))ti((m(f,uz())-f)/(OS?2.4e6:2.4e4)-4*n/1e6))
us(f1,ii[36];in=!h$((u)s,(u)i)&&1&i[OS?6:1]>>15?i[OS?12:24]:0;Qs(!n,s)R(2,n,ii=h_((u)s,0);_w(i,r,n);_h(i)))us(f0,ux=f1(s);Q(x)C_(x))
us(ls,ux=f0(s);Q(x)ii=-1;Wh(++i<nx&&nxu)Q(ws(sxu))_x(0))us(es,92==*s?c4(is(s[1],"ltw"),0,ls(s+3),ts(s+3),ti(W)):58==s[1]?_(u*a=U+*s-97;_r(*a);*a=z(s+2);0):z(s))
int main(int _,char**a){OS=(u)a>>46;If(*++a,ls(*a))w((u)"k/fun (c)atw "__DATE__),w(10);bs[64];Wh(1)w(32),s[_w(0,(u)s,64)-1]=0,*s?ws(s):0;}
