v:!4000
m:_1e9%#v
\t:10?m +\v
\t:m 2=v
\t:m +/v
\t:m |/v
\t:m 2+v
\t:10?m 2%v
\t:10?m %v
\t:10?m +\v
m:1000000
\t:m ----------2
\t:m 2-2-2-2-2-2
\t:m @,@,@,@,@,2

`and
("and";"or")/"1.2+3"
x:k/x
a:1'"q.s"
\t:6000 0/a


todo
Ia2E3  !(;;)
Waa:-a (:a)/..
+/
x+*
+/'!'2 3
A1>_#9
A2>_(x+*)/x:#9

a'b while(a)b

A'B if(a)b if(c)d else e 
2b|~2b
?n
^?<>= 
x.y
sql
^x [a/deepmind]
sql c python3 p4 k csv json

+\01011
x=|\("`"x)*x:+\"."x
(010;011)\".`"?" "x
a.`a.a`
0111222(+\.)
0011112(x*`)


