#include"a.h"//thomn uar :+-*%&|<>=~ !@?#_^ ,.$ RE NLMSGVD g[&|<>= !@?#^] _V(wI,i(4,wi(zi))z,Iz)
#define e4(g,o,y,x...) _e(g,EX=sx;r(ze,y;i(4,r=o(r,s0(1<<2+i,r))))[15],x)
#define A(m,o,O,t,T,w) _D(t##6,O##t,i(6-m,x=O##T(x,s0(1<<m+i,x)))x,i6 x)_U(o##t,Iz=z##m-w;I(n<<m,z=O##T(z,X_))O##t(z)[b(6-m)],in,VX)_Z(o##T,T##z=z##m-w;I(n<<m,A_=z=O##T(z[b(6-m)]-z##m,O##t(X_))),in,VA,VX)
VF(SG,a+x)IF(SI,a+x)EF(SE,a+x)A(0,l,L,g,G,1)A(0,m,M,g,G,0)A(0,s,S,g,G,0)A(2,l,L,i,I,1)A(2,m,M,i,I,0)A(2,s,S,i,I,0)_f(m2,p(0,x);mi(nx,sx))e4(me,ME,i(n4(nx),r=ME(r,X_)),Ux)
e4(se,SE,in=n4(nx);Ez[4]={};i(n/4,i(4,zi+=X_))i(4,r+=zi)i(n%4,r+=X_),Ux)e4(EE,SE,in=n4(nx);Ez[4]={};i(n/4,i(4,zi+=Ea*X_))i(4,r+=zi)i(n%4,r+=Ea*X_),EA,Ux)
_Z(ve,EX=sx;in=vx/16;i(n/4,Ez[4]={};h(ux,i(4,zi+=A[h]*X[n*h+i]))X+=4;i(4,R_=zi))i(n%4,R_=r(ze,i(ux,r+=Ai*X[n*i])++X)),ER,eA,Ux)
F(S,Qt(ta-tx|3-tx)x=p(0,x);im=ua;in=vx;_x(mx?ma?u_(m,R(3,m*n,i(m,ve(r2+n*i,a2+m*i,x)))):R(3,n,ve(sr,sa,x)):ma?R(3,m,i(m,re=EE(a2+n*i,x))):te(EE(sa,x))))
g(e9,x=p(0,T(3,x));ee=1/$4(i,nx,se(x),_q(EE(sx,x)/nx-ze)[0],se(x=p(0,(e=me(x),X(Ex-e)))));X(e*Ex))G(b3,Qr(!aa)2>tx?X(1&$3(i-6,ga<X_,ga>X_,ga==X_)):X(1&$3(i,ia<Ix,ia>Ix,ia==Ix)))
G(a6,ij=i-1;X($3(tx-1,5>j?LG(ga-z0,X_):MG(ga-z0,X_),$6(j,ia+Ix,ia-Ix,ia*Ix,z2,LI(ia-z2,Ix),MI(ia-z2,Ix)),$6(j,ea+Ex,ea-Ex,ea*Ex,ea/Ex,LE(ea-ze,Ex),ME(ea-ze,Ex)))))
G(A6,ij=i-1;_a(VA=sa;X($3(tx-1,5>j?LG(A_,X_):MG(A_,X_),$6(j,Ia+Ix,Ia-Ix,Ia*Ix,z2,LI(Ia-z2,Ix),MI(Ia-z2,Ix)),$6(j,Ea+Ex,Ea-Ex,Ea*Ex,Ea/Ex,LE(Ea,Ex),ME(Ea,Ex))))))
G(A0,it=m(4>i?2:5>i?3:0,m(ta,tx));a=aa?a:T(t,a);x=ax?x:T(t,x);ax?aa?3>t?t(7>i?t:1,$9(i-1,ia+ix,ia-ix,ia*ix,0,l(ia,ix),m(ia,ix),ia<ix,ia>ix,ia==ix)):_v(A0(i,a,v(x))):
A0(3>i?1:5>i?3:$3(i-7,8,7,i),$5(i-1,x,3>t?ti(-ix):te(-ex),x,te(1/ex),x),a):(7>i?aa?a6:A6:b3)(i,a,x))G(ep,Qz(a|2-i|2-tx)ii=*x2;IA=x2-1;x=X(Ix-A_);*x2=i;x)G(Nt,0)
G(a0,P(ax,_v(a0(i,a,v(x))))P(10<i,_T(x))x=T(4>i?2:3,x);ee=a&&aa?l_(ea-ze)[0]:1.442695;4>i?A0(i,3>i?0:r_(x),x):5>i?X(_q(Ex)):aa?1&i?X(_l(e*Ex)):X(l_(Ex)/e):_a(a=T(3,a);EA=sa;X(x(Ex,x/(1+_l(e*-x))*Ea))))
F(_I,Qn(na<=m2(x=T(2,x)))!ta?RU(nx,_i(xi,a)):2-x(a,bx)?_R(tx,nx,$(2>tx,I(Nx,RX=C(g4,(i6)g0(sa,XZ))))I(Nr,RZ=g3(sa,XY))):X(g2(sa,XZ)))F(I_,Qr(!ta)Qt(ta-tx)_R(2,nx,i(nr,ri=i_(xi,a))))
Vf(ba,p2(x,BA))Vf(ab,AB&LI(x,ba(x))|~AB&MI(x,ba(x)))_Z(bk,IA=Z;i(n4(m),A_=z0)i(n,++Z[Xi>>k]),ik,im,in,iX)inx(m1,bk(0,i,n,sx);sI(i,Z,Z);_X(i,IA=R;i(n4(n),A_=z2)i(i,R[i?Z[i-1]:0]=i)mI(n,R,R)))
inx(n1,ik=lu(i)-lu(n);iA=sx;bk(k,i=1+(i-1>>k),n,A);ij=mi(i,Z);sI(i,Z,Z);_X(i,p(1,r);i=n;W(i--)R[--Z[Ai>>k]]=Ai;IX=R--;*R=r(*R,*R=0;IA=R;i(1+j>>1,i(n4(n),Xi=ab(Xi))i(n4(n),Ai=ab(Ai))))))
f(sq,Qz(2-tx)in=nx;il=0;im=1+m2(x);Qz(17>n)(m/4>n?n1:m1)(m,n,x))f(uq,Qz(2-tx)in=nx;il=0;im=1+m2(x);Qz(17>m)Qn(m-1>>18)bk(0,m,n,sx);IA=Z;_x(RV(2,m,A_)))

_G(sS,0)f(aq,0)f(bq,0)f(fq,0)f(gq,0)G(v1,$a(i-5-(9<i),ff,rr,aq,bq,fq,gq,_v,uq,_n,sq)(x))
G(g1,im=iz(x);10>i?u_(m,6>i?n_(m*m,te(1)):R(3,m*m,j(m,*(i6*)(r2+m*j)=E1&$4(i-6,m-1-j==I2,j<I2,j>I2,j==I2)))):13-i?x(RV(2,m,I2|16*i),11-i?e9(0,x):x):RV(3,m,(e6)(E1|b(23)&(i6)JJ())-1))
G(A3,i-=11;P(aa,in=(ia+65535)/ia;1==i|2<m(ta,tx)?A0(3,1<i?te(1/ea):a,x):ax?ti($3(i,ix%ia,ix*ia,ix/ia)):X(Iz=Ix;x(n*z>>16,i?x:z-ia*x)))Qz(!i--)_a(ax?i?ti(i_(x,a)):_i(x,a):(i?I_:ma|mx?S:_I)(a,x)))
g(r9,Qz(2<i)p(!i,x);_x(3>tx?t(tx,$6(2*i+tx-1,lg,li,mg,mi,sg,si)(nx,sx)):te($3(i,me,me,se)(x))))g(s9,Qz(2<i|2<tx)r(uz(x),$6(2*i+tx-1,lG,lI,mG,mI,sG,sI)(nx,sr,sx)))ZU er(ii,U,U);
Ui(q3,2>i-5?i-5:1-i?3:2)G(R7,i-=22;Qr(ax)Qz(!i--)P(a,_a(S(a,x)))r9(i,x))G(O3,i-=29;Qr(ax|!tx)P(ta,Qz(i)e9(ia,x))Qr(!pa)a-=32;P(!i--,(11>a?ep:er)(a,0,x))P(17==a,_u(x))(i?s9:r9)(q3(a),x))
G_(k,(2>i-20||(a?10>i:5>i|10==i|15==i)?tx?a&&10>i?A0:a0:er:17>i?a?11>i?Nt:14>i?A3:L3:ax?g1:v1:20>i?$3(i-17,cC,dD,sS):29>i?R7:O3)(i,a,x))G(er,Qr(!aa)ij=i;RU(nx,k(j,r_(a),_i(i,x))))
