#!/usr/bin/env -S deno run --allow-read
let kc=(P,A,S)=>{ //program(string), target:c,w, step:pars,comp,lift..
 let pars=p=>{let i=-1,c,n=x=>(c=p[++i],x?0:_()),N=(x,...y)=>(y.i=x,y),Q=x=>{throw new Error("@"+i+" "+x)},l=x=>x[x.length-1]
  let _=n=>{while(1){while(In(n?" \t\n":" \t",p[i]))i++;if(p[i]=='/'&&(In(' \n',p[i-1])||!i)){i++;while(p[i]&&p[i]!='\n')i++;i++;continue};break};c=p[i]||''}
  let In=(x,y)=>x.includes(y)
  let sy=c=>/[A-Za-z]/.test(c),ys=c=>/[A-Za-z0-9.]/.test(c),yn=c=>In("0123456789",c),ym=c=>In('abcdefghijklmnopqrstuvxwyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789)]}"',c),yy=c=>In(":+-*%!&|<>=~,^#_$?@.",c),YY=c=>In("/\\'[",c)
  let ya=c=>In("/\\'",c),yx=c=>In("$@.",c),yo=c=>In("({[",c),yc=c=>In("]})",c),ye=c=>In(";\n",c),yb=$=>p[i-1]!=' '&&(c==':'||yy(c)&&p[1+i]==':'),yi=x=>x[0]=='sym'&&(p[i-1]=='i'||yn(p[i-1])),yC=x=>In(['num','vec'],x[0])
  let A="",L=[],AL="xyzabcdefghijklmnopqrstuvw",v=x=>In(['opr','drv','com','prj'],x[0])
  let prg=$=>{let r=[];while(_(1),c)r.push(fun()),c==';'?n():0;return N(0,'prg',...r)}
  let fun=$=>{let j=i,m,s,b,a,l;m=sym();s=sig();b=bdy();a=arg(j,s);l=loc(j,a);A="";L=[];return N(j,'fun',m,s,a,l,b)}
  let arg=(j,s)=>{let a=s[2].length?s[2].length:In(A,'z')?3:In(A,'y')?2:1; return N(j,'arg',...AL.split("").slice(0,a).map(x=>N(j,'sym',x)))}
  let loc=(j,a)=>{a=","+a.slice(1).map(x=>x[1]+",").join("");return N(j,'loc',...L.filter(x=>!(In(a,`,${x},`))).map(x=>N(j,'sym',x)))}
  let sig=$=>{let j=i,k,r='K:';if(c=='(')while(n(),c!=')');if(i!=j)r=p.slice(1+j,i),n();r=((+r)?"K:"+"K".repeat(+r):r).split(":");if(2!=r.length||r[0].length>1){i=j;Q("signature")};return N(j,'sig',...r)}
  let sym=q=>{let j=i,k=i,s='',y=0,w=0;if(!sy(c))Q("expected identifier");while(c&&ys(c))s+=c,c=p[++i];if(q&&s=='if'||s=='while')return ifw(j);_();
   if(q&&s.length>1&&s[0]!='K'&&(l(s)=="i"||yn(l(s))))y=l(s),s=s.slice(0,-1);                    //suffix i09  (index)
   if(q&&s.length>1&&/[cijz]/.test(s[0]))w=s[0],s=s.slice(1);                                    //prefix cijz (cast)  CIJZ (ptrtype)
   if(1==s.length&&In("x y z",s)&&!In(A,s))A+=s;if(s=='i'&&!In(L,'i'))L.push('i');s=N(j,'sym',s);j+=s.length-1;  //arity
   s=y?jux(s,'i'==y?((!In(L,y)?L.push(y):0),N(j,'sym',y)):N(j,'num',y)):s;return w?(s.i++,N(k,'cst',w,s)):s}
  let bdy=$=>{let j=i,r=c=="{"?lst('}'):[];return N(j,'bdy',...r.slice(1))}
  let lst=(t,z,w)=>{let j=i,e,r=[];w||n();while(c&&c!=t){e=exp();if(z||e)r.push(e);if(In(":})]",c))break;c==';'||c=='\n'?n(w):c!=t?Q(`expect ; or ${t} got ${c}`):1};if(c==t&&!w)n();return N(j,'lst',...r)}
  let blo=$=>N(i,'blk',...lst(']').slice(1)),bk1=x=>x[0]=="blk"&&x.length==2?x[1]:x              //block expression [1;2;3]
  let blk=$=>{let j=i,b=lst(' ',0,1);if(p[i-1]==';')c=';';return N(i,'blk',...b.slice(1))}       //auto block       1;2;(space)
  let rls=(t,x)=>{let j=i;return 2==x.length?x[1]:N(x.i,t,...x.slice(1))}
  let bkt=x=>{let j=i,r=lst(']',1);if(2==r.length)r=r[1];return(yb())?(x[0]!='sym'?(i=i,Q("asn")):asn(x,r)):jux(x,r)}           // 1-:  => com(opr +, prj(opr :,1))
  let asn=(x,y)=>{let j=i,r=c;if(x[0]=='opr')return n(),N(x.i,'com',N(j,'opr',':'),x);             //-:
   if(p[1+i]==':')++i,r+=':';
   if(yC(x)&&2==r.length)return n(),N(x.i,'com',N(j,'opr',':'),N(j,'prj',x,N(j,'opr',r[0]))); //1+:
   if(!(x[0]=='sym'||x[0]=='dya'&&x[1][0]=='opr'&&x[1][1]=='@'&&x[2][0]=='sym'))(i=x.i,Q("assign"));
   if(r==':'&&x[0]=='sym'&&!y&&!In(L,x[1]))L.push(x[1]);n();r=N(j,'asn',r,x,y,ex(tt()));if(!y)r.splice(3,1);return r}
  let exp=x=>{x=ex(tt());return(c=='?'&&p[1+i]==' ')?ter(x):x}
  let ex=x=>{let j=i,y,r;if(!x)return 0;
   if(c==':'&&p[i-1]==' '||x[0]=='whl'||x[0]=='iff')return x;
   if(c=='?'&&p[i+1]=='[')return jmp(x);
   y=tt();if(!y)return x;
   if(v(y)&&!(v(x))){r=ex(tt());if(!r)return prj(y,x);if(v(r))return com(r,prj(x,y));return dya(y,x,r)};r=ex(y);return !v(x)?jux(x,r):(r==y||r[0]=='com')&&v(x)&&v(y)?com(r,x):mon(x,r)}
  let tt=$=>{let j=i,r;_();r=ye(c)||c=='?'&&p[1+i]==' '||c==':'&&p[i-1]==' '?0:yn(c)||c=='-'&&yn(p[1+i])&&!ym(p[i-1])?num():sy(c)?sym(1):yy(c)||ya(c)?opr():'('==c?rls('enl',lst(')')):c=='{'?lam():c=='['?blo():0;if(!r)return r;']}';
   if(yb())return yi(r)?asn(r[2],r[3]):asn(r,0);if(c=='['&&yx(p[i-1]))return spc(r);
   while(YY(c)&&p[i-1]!=' '){j=i;if(c=='['){r=yy(p[i-1])?Q("primitive bracket call"):bkt(r)}else r=N(j,'drv',adv(),r)};return r}
  let dya=(f,x,y)=>N(f.i,"dya",f,x,y),mon=(f,x)=>N(f.i,"mon",f,x),jux=(x,y)=>dya(N(y.i-1,'opr','@'),x,y),com=(x,y)=>x[0]=="com"?(x.push(y),x):N(x.i,"com",x,y)
  let opr=$=>{let j=i,r=c;n();return N(j,'opr',r)}
  let adv=$=>{let j=i,r=c;n();return N(j,'adv',r)}
  let prj=(x,y)=>{let j=i;return N(j,'prj',x,y)}
  let tet=(j,x,r)=>{if(r.length==4){r.splice(3,0,N(j,'num','0'));r[3].T='K'};return N(j,'cal',x=='@'?'Amd':'Dmd',...r.slice(1))}
  let num=$=>{let j=i,s=c=='-'?c:'';if(s)c=p[++i];while(/[0-9.ijfzea]/.test(c))s+=c,c=p[++i];_();return N(j,'num',s)}
  let ter=x=>{let j=i,t,e;n();t=blk();if(c!=':')c=p[++i];if(c!=':')Q('tern expect :');n(1);e=blk();_();return N(j,'ter',x,bk1(t),bk1(e))}
  let jmp=x=>{let j=i++,r=lst('[]'[1]);return N(j,'jmp',...r.slice(1))}
  let ifw=j=>{if(c!='(')Q('(missing');'))';n(1);let e=exp();n(1); return N(j,p[j]=='i'?'iff':'whl',e,blk())}
  let spc=x=>{let j=i-1,r=lst(']');x=x[1];return x=='$'?cnd(r.slice(1),j):(r.length>5||r.length<4)?(i=j,Q('triadic or tetradic')):In("@.",x)?tet(j,x,r):(i=j,Q('unknown special'))}
  let cnd=(x,j)=>{if(x.length<3||!(1&x.length))(i=j,Q("cond-length"));return N(x[0].i,'ter',x[0],x[1],x.length>3?cnd(x.slice(2),j):x[2])}
  let lam=$=>{'{';let j=i,_a=A,_l=L;A="";L=[];let b=bdy('}'),s=sig(j,'sig','K:'),a=arg(j,s),l=loc(j,a);A=_a;L=_l;return N(j,'lam',a,l,b)}
  return n(),prg()}
 
 let comp=a=>{   //convert compositions and unapplied derived verbs to lambdas
  let N=(x,...y)=>(y.i=x,y),F=(x,I,p)=>{if(!Array.isArray(x))return;x.forEach(F);
  if(x[0]=='com'){let i=x.i,m=x[1][0]=='opr'&&x[1][1]==':',xy=m?["x"]:["x","y"],r=N(x[1].i,'sym','x');x.slice(1).forEach((x,j)=>{r=(j||m)?N(x.i,'mon',x,r):N(i,'dya',x,r,N(i,'sym','y'))});
   x.splice(1);x[0]='lam';x.push(N(x.i,'arg',...xy.map(x=>N(i,'sym',x))),N(i,'loc'),N(i,'bdy',r))}
  if(x[0]=="drv"&&p[0]!='mon'&&p[0]!='dya'){let i=x.i,b=N(i,'mon',x,N(i,'sym','x')),r=N(i,'lam',N(i,'arg',N(i,'sym','x')),N(i,'loc'),N(i,'bdy',b));P[I]=r}  // drv -> lam .. mon drv sym x
  };F(a,0,0)}
  
 let lift=a=>{   //lift lambdas.  lam arg loc bdy -> fun sym sig arg loc bdy          maybe check for duplicates (parse tree? input string?)
  let f=0,N=(x,...y)=>(y.i=x,y),F=(x)=>{if(!Array.isArray(x))return;x.forEach(F);
  if(x[0]=="lam"){let r=N(x.i,'fun',N(x.i,'sym',`_${f}`),N(x.i,'sig','K',''),...x.slice(1));x.splice(2,2);x[0]='sym';x[1]=`_${f++}`;a.push(r)}};F(a)}
 
 let maco=a=>{   //type macro nx.. [ntprIJCFZ]
  let fn=x=>{let i,f,v={},m="ntprIJCFZ",a=x[3].slice(1).map(x=>x[1]),l=x[4].slice(1).map(x=>x[1]),al=[...a,...l],In=(x,y)=>x.includes(y)
   f=x=>{if(!Array.isArray(x))return;x.forEach(f);if(x[0]!="sym"||x[1].length!=2||In(l,x[1]))return;
    let p=x[1][0],q=x[1][1];if(!(In(m,p)&&In(al,q)))return; x.T=In("IJFZp",p)?p.toLowerCase():"i"; x[0]='cal';x[1]=p.toUpperCase();x[2]=['sym',q];x[2].i=x.i};f(x[5])} //x[2].T is typed later
  a.filter(x=>x[0]=='fun').forEach(fn)}
 
 let btin=a=>{   //builtin calls as operators
  let b='Lt Le Gt Ge Sh Dv Mo'.split(' ')
  let f=x=>{if(!Array.isArray(x))return;x.forEach(f);if(x[0]=='dya'&&x[1][0]=='opr'&&x[1][1]=='@'&&x[2][0]=='sym'&&b.includes(x[2][1])){x[1][1]=x[2][1];x[2]=x[3][1];x[3]=x[3][2]}};f(a)}
 
 let type=a=>{   //type each node
  let X={Ma:'p',Mf:'',break:''},Y={Ma:'i',Mf:'p'},N=(x,...y)=>(y.i=x,y),rt,fn=a.filter(x=>x[0]=='fun');
  fn.forEach(x=>{x.T=x[2][1];X[x[1][1]]=x.T;Y[x[1][1]]=x[2][2]||'K'.repeat(x[3].length-1);x[2][2]=(!x[2][2])?'K'.repeat(x[3].length-1):x[2][2];x[2][2].split("").forEach((t,i)=>x[3][1+i].T=t)}); //X={'name':'K'} namespace:funcs/arg/loc/glo
  let e=x=>{console.error(x);throw new Error("@"+x.i+" type: "+Li(x))},t0=x=>'',t1=x=>x[1].T,t2=x=>x[2].T,tl=x=>x[x.length-1].T,lup=x=>(x[1] in X)?X[x[1]]:e(x),nm=(x,s)=>(x=x[1],s=x[x.length-1],x.includes("a")?"z":x.includes(".")?"f":"i");
  let cst=(t,x,r)=>(t==x.T?0:t=='K'?toK(x):x[0]=='num'&&x.T=='i'?x.T=t:x[0]=='mon'&&x[2][0]=='num'?(x.T=t,x[2].T=t):(r=x.slice(),(r.i=x.i),(r.T=x.T),x.splice(1),x[0]='cst',x[1]=t,x[2]=r,x.T=t),t)
  let toK=x=>{let t=x.T,r=x.slice();if(x[0]=='opr'){x.T='K';return'K'};if(t=='j')return 'K';r.i=x.i;r.T=t;x[0]='cal';x.T='K';x[1]='K'+('ifz'.includes(t)?t:e(x));x.splice(2);x[2]=r;return 'K'}
  let tak=x=>x[1][0]=='opr'&&x[1][1]=='#'&&x[2].T=='i'&&x[2][0]!='num'
  let tet=x=>{if(x.length!=6)e(x);for(let i=2;i<6;i++)if(x[i].T!='K')toK(x[i]);return'K'} // cal Amd x i f t
  let mac=(x,i)=>{if('Amd'==x[1]||'Dmd'==x[1])return tet(x);i="NTRPIJCFZ".indexOf(x[1][1]);if(i<0)e(x);return x.T=i<3?'i':x[1][1].toLowerCase()}
  let cal=x=>(x[1][1]=='@'&&x[2][0]=='sym'&&(x[2][1]in Y)?(ca(x[2][1],x[3]),x):x)
  let ca=(f,x)=>{let i,a=Y[f],n=a.length,m=x[0]=='lst'?x.length-1:1;if(n!=m)e(x);if(n-1){for(i=0;i<n;i++)cst(a[i],x[1+i])}else cst(a,x);}
  let dy=x=>tak(x=cal(x))?x.T='K':x[2].T==x[3].T?x[2].T:x[1][1]=='@'&&x[3].T=='i'?x[2].T:x[1][1]=='@'?lup(x[2]):x[2].T=='K'?toK(x[3]):x[3].T=='K'?toK(x[2]):x[2].T=='i'?cst(x[3].T,x[2]):x[3].T=='i'?cst(x[2].T,x[3]):(console.error(x),e('type'))
  let bd=x=>{if(rt&&rt!=x[x.length-1].T)cst(rt,x[x.length-1]);return rt}
  let as=x=>{let m=+(5==x.length),xx=x[3+m],s=x[2][0]=='sym'?x[2][1]:'';if(s&&(!m))if(!(s in X))e(x);if(x[1]==':'&&s&&!X[s])X[s]=xx.T;else if(xx.T!=x[2].T)cst(x[2].T,xx);return xx.T}
  let f=x=>{if(!Array.isArray(x))return; if(x[0]=='blk'||x[0]=='bdy'||x[0]=='ter'||x[0]=='iff'){for(let i=1;i<x.length;i++)f(x[i])}else{for(let i=x.length-1;i>0;i--)f(x[i])}
   let m={sym:lup,num:nm,mon:t2,dya:dy,cal:mac,cst:x=>x[1],blk:tl,bdy:bd,lst:t0,adv:t0,drv:t0,asn:as,ter:t2,iff:t0,jmp:t2,opr:t0};x.T=x.T?x.T:(x[0]in m)?m[x[0]](x):e(x)}
  fn.forEach(x=>{rt=x[2][1];x[3].slice(1).forEach(x=>X[x[1]]=x.T); x[4].slice(1).forEach(x=>X[x[1]]=x.T?x.T:x[1]=='i'?'i':'');f(x[5]);x[4].forEach(x=>"string"!=typeof x?x.T=X[x[1]]:0)})}
 
 let digr=a=>{   //non-k digraphs  <<  >>  <= >=
  let f=x=>{if(!Array.isArray(x))return;x.forEach(f);
   if(x[0]=='dya'&&x[1][0]=='opr'&&x.T!='K'&&1+'<>'.indexOf(x[1][1])&&x[3][0]=='mon'&&x[3][1][0]=='opr'&&1+'<=>'.indexOf(x[3][1][1])){x[1][1]+=x[3][1][1];x[3]=x[3][2];}}
  a.forEach(f)}
 
 let asin=a=>{    //replace modified assign +: for k types and everywhere for wasm, replace k indexed/modified assign with Amd/Dmd. //blk
  let toK=x=>{let t=x.T,r=x.slice();if(t=='j'||t=='K')return x;r.i=x.i;r.T=t;x[0]='cal';x.T='K';x[1]='K'+('ifz'.includes(t)?t:e(x));x.splice(2);x[2]=r;return x}
  let e=x=>{console.error(x);throw new Error("@"+x.i+" asin: "+Li(x))},N=(x,t,...y)=>(y.i=x,y.T=t,y),f=x=>{if(!Array.isArray(x))return;x.forEach(f);
   if(x[0]=='asn'&&x.T=='K'&&x[1]==':'){let s=x[2],i=x.length==5?x[3]:0,r=toK(x[4-!i]);x[3]=i?N(x.i,'K','cal','Amd',s,toK(i),N(x.i,'K','num','0'),r):r;x.splice(4)}
   if(x[0]=='asn'&&x.T=='K'&&x[1]!=':'){let i=x.length==5?x[3]:0,s=x[2],f=N(x.i,'K','opr',x[1][0]),r=x[3+!!i] //modified K  x.length 4|5(indexed)
    if(x[3][0]=='lst')e(x);console.log('f',f);
    x[1]=':';x[3]=i?N(x.i,'K','cal','Amd',s,toK(i),f,toK(r)):N(x.i,'K','dya',toK(f),s,toK(r));x.splice(4)}};a.forEach(f)}
  
/*let kfun=a=>{   //k function objects  f => K2(f)  todo ignore globals   todo track Kn
  let N=(x,...y)=>(y.i=x,y),al,ar={},F=x=>{al=[...x[3].slice(1).map(x=>x[1]),...x[4].slice(1).map(x=>x[1])];f(x[5])}
  let f=x=>{if(!Array.isArray(x))return;x.forEach(f);if(x[0]=='sym'&&x.T=='K'&&ar[x[1]]&&!(al.includes(x[1]))){let s=x[1];x[0]='cal';x[1]='K'+ar[s];x[2]=N(x.i,'sym',s);}}
  let fn=a.filter(x=>x[0]=='fun');fn.forEach(x=>{if(x[2][0]=='K'&&x[2][1].length>1&&x[2][1]=='K'.repeat(x[2][1].length))ar[x[1][1]]=x[2][1].length});fn.forEach(F);
  }*/
  
 let call=a=>{    //replace k ops with calls, f@ with call,  correct type for P(x)
  const op=" +   -   *   %   !   &   |   <   >   =   ~   ,   ^   #   _   $   =   @   .".replaceAll(" ","")
  const o1="Abs Neg Sqr Sqt Til Flp Rev Asc Dsc Grp Not Enl Srt Cnt Flr Str Unq Fst Val".split(" ")
  const o2="Add Sub Mul Div Mod Min Max Les Mor Eql Neq Cat Cut Tak Drp Fmt Fnd Atx Cal".split(" ")
  let fn={Ma:1,Mf:1},K={},al,N=(x,...y)=>(y.i=x,y.T='K',y),f=x=>{if(!Array.isArray(x))return;if(x[0]=='fun')al=[...x[3].map(x=>x[1]),...x[4].map(x=>x[1])];
   if(x[0]=='opr'&&x.T=='K'&&op.includes(x[1])){let s=o2[op.indexOf(x[1])];x[0]='cal';x[1]='K2';x[2]=N(x.i,'sym',s)}
   if(x[0]=='mon'&&x[1][0]=='opr'&&x.T=='K'&&x[2].T=='K'){             x[0]='cal';x[1]=o1[op.indexOf(x[1][1])]};
   if(x[0]=='dya'&&x[1][0]=='opr'&&x.T=='K'&&x[2].T=='K'&&x[3].T=='K'){x[0]='cal';x[1]=o2[op.indexOf(x[1][1])];if(x[1]=='Atx'&&x[3][0]=='num'&&x[3].T=='K'&&(!x[3][1].includes("."))){x[3].T='i';x[1]='Ati'}}
   else if(x[0]=='dya'&&x[1][0]=='opr'&&x[1][1]=='@'&&x[2][0]=='sym'&&fn[x[2][1]]&&!al.includes(x[2][1])){x[0]='cal';x[1]=x[2][1];let l=x[3];x.splice(2);l[0]=='lst'?x.push(...l.slice(1)):x.push(l);}
   x.forEach(f)}
  a.filter(x=>x[0]=='fun').forEach(x=>{fn[x[1][1]]=1; if(x[2][1]=='K'&&x[2][2].length&&x[2][2]=="K".repeat(x[2][2].length))K[x[1][1]]=x[2][2].length});a.forEach(f)}
 
 let loop=a=>{    // i#(tak)  i/(lop)
  let fn,si=['sym','i'],ii=_=>{if(!(fn[4].slice(1).map(x=>x[1])).includes('i')){si.T='i';si.i=fn.i;fn[4].push(si)}},f=x=>{if(!Array.isArray(x))return;if(x[0]=='fun')fn=x;x.forEach(f);
   if(x[0]=='cal'&&x[1]=='Tak'&&x[2].T=='i'&&x[2][0]!='num'){x[0]='tak';x.T='K';x[1]=x[2];x[2]=x[3];x.slice(3);ii()}
   if(x[0]=='mon'&&x[1][0]=='drv'&&x[1][1][0]=='adv'&&x[1][1][1]=='/'&&x[1][2].T=='i'&&x[1][2][0]!='num'){x[0]='lop';x[0].T='';x[1]=x[1][2];ii();}
  }
  a.forEach(f)}
 
 let cord=a=>{   //evaluate function parameters right-to-left    //todo >2args
  if(A!="c")return;let F="Ki Kf Kz N P R".split(" ")
  let N=(x,...y)=>(y.i=x,y.T='K',y),f=(x,e)=>{if(!Array.isArray(x))return e;
   x.forEach(x=>e|=f(x,e));
   if(e&&x.T=='K'&&x[0]=="cal"&&x.length==4&&x[2][0]!='num'&&x[3][0]!='num'&&!(x[2][0]=='sym'&&x[3][0]=='sym')){x.splice(1,0,'$2');x[2]=N(x.i,'sym',x[2]);}  //order doesn't matter if one of 2 args is num or both are sym.
   if(x.T=='K'&&((x[0]=="cal"&&!F.includes(x[1]))||x[0]=="asn"))e=1;
   return e;
  }
  a.forEach(x=>f(x,0))}

 let swap=a=>{   //swap cmp ops; swap xy for ops where it matters introducing locals: y set x get, keep track of live vars, e.g: (x<<y)%z needs 2 temps
  if(A!='w')return;  // x%y:  (dya (opr %) (x) (y)) -> (blk (asn : $t (y)) (dya (opr %) (sym $t) (x)))
  let c="< > <= >= Lt Le Gt Ge".split(" "),d="> < >= <= Gt Ge Lt Le".split(" "),g="- % Dv Mo Sh << >>".split(" ")
  let L,V,T=x=>x=='K'?'j':x=='p'?i:x,N=(x,t,...y)=>(y.i=x,y.T=t,y),f=x=>{if(!Array.isArray(x))return;x.forEach(f);
   if(x[0]=='cal'&&x[1]=='P'){x[0]='cst';x[1]='i';x.T='i'} //replace call P(x) with cst
   if(x[0]=='dya'&&x[1][0]=='opr'){let s=x[1][1],i=c.indexOf(s);if(i>=0){x[1][1]=d[i];return};i=g.indexOf(s);if(i<0)return;
    if(x[2][0]=='num'||x[3][0]=='num'){[x[2],x[3]]=[x[3],x[2]];return} //just swap without creating locals
    let X=x[2],Y=x[3],t=T(x.T);f(Y);let v=`${t}${V[t].length}`;L[v]=1,V[t].push(1);f(X);V[t].pop();
    let sy=N(Y.i,Y.T,'sym',v),as=N(Y.i,Y.T,'asn',':',sy,Y),dy=N(x.i,x.T,'dya',N(x.i,x.T,'opr',x[1][1]),sy,X)
    x.splice(1);x[0]='blk';x[1]=as;x[2]=dy}}
  let fn=a.filter(x=>x[0]=='fun');fn.forEach(x=>{L={},V={i:[],j:[],f:[],z:[]};f(x[5]);for(let v in L)x[4].push(N(x.i,v[0],'sym',v))})}
 
 let indx=a=>{    //convert I(x)[y] to idx for CIJ
  if(A!='w')return; //wasm only  
  let f=x=>{if(!Array.isArray(x))return;x.forEach(f);
   if(x[0]=='dya'&&x[1][0]=='opr'&&x[1][1]=='@'&&x[2][0]=='cal'&&"C I J".includes(x[2][1])){
    x[0]='idx';x.T=x[2][1].toLowerCase();x[1]=x[2][2];x[2]=x[3];x.splice(3)}};a.forEach(f)}

 let refc=a=>{   //inc refcount on args, dec on exit, remove asn on return
  let e=(x,y)=>{console.error(x,y);throw new Error("@"+x.i+" "+y+" refc: "+Li(x))},N=(x,t,...y)=>(y.i=x,y.T=t,y),_x={},R=['R0','R1','K1','K2','K3','K4']
  let r1=x=>x[0]=="sym"?(_x[x[1]]=N(x.i,'K','cal','R1',x)):x,$n=x=>x.startsWith('$'),r0=x=>{x[0]='sym';x[1]=x[2][1];x.splice(2)}
  let fn=x=>{_x={};let t=x[2][1],a=x[3].slice(1).filter(x=>x.T=="K").map(x=>x[1]),l=x[4].slice(1).filter(x=>x.T=="K").map(x=>x[1]),al=[...a,...l],b=x[5],u={};l.forEach(x=>u[x]=1);
   let f=x=>{if(!Array.isArray(x))return;
    if(x[0]=='cal'&&!R.includes(x[1])){for(let i=2+$n(x[1]);i<x.length;i++)if(x[i].T=="K")x[i]=r1(x[i]);}
    if(x[0]=='asn'&&x.length==4&&x[3][0]=='sym'&&x[3].T=='K')x[3]=r1(x[3]);
    if(x[0]=='iff'||x[0]=='ter'){_x={};u={};x.forEach(f)}  //reset inc tracking in branches
    else if(x[0]=='bdy'||x[0]=='blk')x.forEach(f)
    else if(x[0]=='asn'){let s=x[2][1];for(let i=x.length-1;i>2;i--)f(x[i]);if(s in u)u[s]=0;}
    else for(let i=x.length-1;i>0;i--)f(x[i]);
    if(x[0]=='sym'&&u[x[1]])e(x,'local '+x[1]+' used before assign.')
   }
   f(b);if(al.length){
    for(let i=al.length-1;i>=0;i--){let s=al[i];if(s in _x){r0(_x[s]);al.splice(i,1)}} //revert last call to R1 and don't unref at return
    let r=b[b.length-1];
    if(r[0]=='asn'&&r[1]==':'){b[b.length-1]=r[3];r=b[b.length-1]} //remove asn on ret, todo global
    if(r[0]=='sym'&&al.includes(r[1]))al.splice(al.indexOf(r[1]),1);
   }
   if(t&&b[b.length-1][0]!='ret'){let r=b[b.length-1];b[b.length-1]=N(r.i,t,'ret',r,...al)}
  };a.filter(x=>x[0]=='fun').forEach(fn)}
 
 let lifmt=s=>{let l=0,i=0,n=[0],m=[0],c,p=0,o="";
  for(i=0;i<s.length;i++,p++){c=s[i];l+=c=='('?1:c==')'?-1:0;f=s.slice(i+1,i+4);if(c=='('&&(p>100||f=="bdy"||f=="fun")){n.push(i-1);m.push(l-2);p=l}}
  n.push(s.length);for(i=0;i<n.length-1;i++)o+=" ".repeat(m[i])+s.slice(n[i],n[1+i])+"\n";return o}

 let li=a=>{let f=x=>(!Array.isArray(x))?x:`(${x.map(f).join(" ")})`;return f(a)} //lisp
 let Li=a=>{let f=x=>(!Array.isArray(x))?x:`(${x.map((e,i)=>(i?'':(x.T||'.'))+f(e)).join(" ")})`;return f(a)} //typed lisp
 let cc=a=>{const H1=`#include<stdint.h>
#include<stdlib.h>
typedef long K;
#define C(x) ((char*)P(x))
#define I(x) ((int*)P(x))
#define J(x) ((K*)P(x))
#define K(x) ((K*)P(x))
#define F(x) ((double*)P(x))
#define Z(x) ((double _Complex*)P(x))
#define N(x) (I(x)[-1])
#define R(x) (I(x)[-2])
#define T(x) ((int)(x>>56))
#define P(x) ((uintptr_t)(0xffffffffffffff&(K)x))
#define K1(f) (((uintptr_t)(void*)&(f))|0x0500000000000000)
#define K2(f) (((uintptr_t)(void*)&(f))|0x0600000000000000)
#define $(c,t,e) ((c)?(t):(e))`,
/*
#define $2(f,x,y) ({K _y=(y);K _x=(x);f(_x,_y);})
#define _1(r,x)           ({K _=(r);R0(x);_;}
#define _2(r,x,y)         ({K _=(r);R0(x);R0(y);_;}
#define _3(r,x,y,z)       ({K _=(r);R0(x);R0(y);R0(z);_;}
#define _4(r,x,y,z,a)     ({K _=(r);R0(x);R0(y);R0(z);R0(a);_;}
*/
H2=`
#define $S(t,c,b,d) ({t _;switch(c){b default:_=(d);};_;})
#define $C(i,x)   case i:_=(x);break;
#define W(c,x) {for(i=0;i<(c);i++){x;}}
#define NI(n,e) ({int _n=(n);K _=Ktn(2,_n);int*_r=(int*)P(x);for(i=0;i<_n;i++){_r[i]=(e);};_r;})
#define Ma(x) (uintptr_t)malloc((size_t)(x))
#define Mf(x) free(x)
#define Mc(d,s,n) memcpy(d,s,(size_t)n)
#define Lt(t,x,y) ((unsigned t)(x)<(unsigned t)(y))
#define Le(t,x,y) ((unsigned t)(x)<=(unsigned t)(y))
#define Gt(t,x,y) ((unsigned t)(x)>(unsigned t)(y))
#define Ge(t,x,y) ((unsigned t)(x)>=(unsigned t)(y))
#define Sh(t,x,y) ((unsigned t)(x)>>(y))
#define Dv(t,x,y) ((unsigned t)(x)/(y))
#define Mo(t,x,y) ((unsigned t)(x)%(y))
`
  let e=x=>{console.error(x);throw new Error("@"+x.i+" cc: "+x)},t=x=>({i:"int",j:"K",p:"uintptr_t",K:"K",f:"double","z":"double _Complex","":"void"}[x])
  let _={},_n=n=>(_[n]=1,n),xw="xyzabcdefghijklmnopqrstuvw",_N=(i,x)=>{let r="";for(i in _){x=xw.slice(0,i).split('');r+=`\n#define _${i}(r,${x.join(',')}) ({K _=(r);${x.map(x=>'R0('+x+')').join(';')};_;})`};return r}
  let $={},$n=(x,n)=>(x[0]=='$'&&(n=+x.slice(1))?($[n]=1,x):x)
  let $N=(i,x,y)=>{let r="";for(i in $){x=xw.slice(0,+i).split('');y=x.toReversed();r+=`\n#define $${i}(f,${x.join(',')}) ({${y.map(x=>'K _'+x+'=('+x+')').join(';')};f(${x.join(',')});})`};return r}
  let res,f=x=>{if(!Array.isArray(x))return x;let s,ch=x=>x.slice(1).map(f),x1=x=>x[1],em=x=>x[0]=='sym'||x[0]=='num'?f(x[1]):`(${f(x)})`
   let m={
    bdy:x=>x.slice(1).map(f).join(';'),
    blk:x=>`({${x.slice(1).map(f).join(";")};})`,
    num:x=>x[1], //todo complex
    iff:x=>`if(${f(x[1])})${f(x[2])}${x[3]?'else '+f(x[3]):''}`,
    sym:x1,
    tak:x=>`N${x[2].T.toUpperCase()}(${f(x[1])},${f(x[2])})`,
    lop:x=>`W(${f(x[1])},${f(x[2])})`,
    cst:x=>'('+t(x[1])+')'+em(x[2]),
    lst:x=>x.slice(1).map(f).join(","),
    cal:x=>$n(x[1])+"("+x.slice(2).map(f).join(",")+")",
    ter:x=>`$(${f(x[1])},${f(x[2])},${f(x[3])})`,
    jmp:x=>`$S(${t(x[1].T)},${f(x[1])},${x.slice(1,-1).map(f).map((x,i)=>'$C('+i+','+x+')').join('')},${f(x[x.length-1])})`,
    asn:(x,s,i)=>(i=5==x.length,s=f(x[2]),`${s=="_"?t(x[2].T)+" _":s}${i?'['+f(x[3])+']':''}${x[1].replace('>','>>').replace('<','<<').replace(':','=')}${f(x[3+i])}`),
    mon:x=>x[1][0]=='opr'?`(${x[1][1]}${em(x[2])})`:x[1][0]=='drv'?`${dr1(x[1],f(x[2]))}`:e(x),
    dya:x=>x[1][0]=='opr'?("SGL".includes(x[1][1][0])?`${x[1][1]}(${t(x.T)},${f(x[2])},${f(x[3])})`:x[1][1][0]=='@'?`${em(x[2])}[${f(x[3])}]`:`${em(x[2])}${x[1][1]}${em(x[3])}`):e(x),
    ret:x=>(res?'return ':'')+(x.length==2?f(x[1]):'_'+_n(x.length-2)+'('+f(x[1])+','+x.slice(2).join(',')+')' ),
   };return(x[0]in m)?m[x[0]](x):e(x)}
  let ret=(t,x,n)=>{if(t)x[n=x.length-1]="return "+x[n];return x.join(";")+";"}
  let loc=l=>{let r="",i,g={};l.forEach((x,tx)=>(tx=t(x.T),(tx in g)?g[tx].push(x[1]):g[tx]=[x[1]]));for(i in g)r+=i+" "+g[i].map(x=>i!='K'?x:x+'=0').join(",")+";";return r}
  let fn=x=>{let name=x[1][1],arg=x[3].slice(1),l=x[4].slice(1),bdy=x[5],lt='';res=x[2][1]
   return `${t(res)} ${name}(${arg.map(x=>t(x.T)+" "+x[1]).join(",")}){${loc(l)}${f(bdy)};}\n`}
  let r=a.filter(x=>x[0]=='fun').map(fn).join("");return H1+$N()+_N()+H2+r}
 
 let wa=a=>{let o=[0,97,115,109,1,0,0,0],p=(...x)=>o.push(...x),L,F,T=[],E=[],N=(x,...y)=>(y.i=x,y),Kn='K1 K2 K3 K4'.split(' '),e=x=>{console.error(x);throw new Error("@"+x.i+" wa: "+x)} //L=
  let t=x=>[0,127,126,124,123,127,126][1+"ijfzpK".indexOf(x)],it=t=>[-1,0,1,2,3,0,1][1+"ijfzpK".indexOf(t)]
  let us=x=>new TextEncoder().encode(x),uf=x=>{let b=new ArrayBuffer(8),v=new DataView(b);v.setFloat64(0,Number(x),1);return new Uint8Array(b)},ns=x=>[...eu(x.length),...us(x)]
  let eu=(x,b,r)=>{r=[];do{b=x&127;r.push((x>>>=7)?b|=128:b)}while(x);return r}
  let en=(x,b)=>{let r=[];while(1){b=x&127n;x=x>>7n;if((!x)&&!(b&64n)||(x==-1n&&(b&64n))){r.push(Number(b));break};r.push(Number(b|128n))};return r}
  let ei=(x,b)=>{let r=[];while(1){b=x&127;x>>=7;if(x==0&&!(b&64)||(x==-1&&(b&64))){r.push(b);break};r.push(b|128)};return r}
  let ws=(x,y)=>(y=[...eu(y.length),...y.flat()],p(x,...eu(y.length),...y))
  let S={},sg=(r,a)=>{let i,s,f=x=>x.replaceAll('K','j').replaceAll('p','i');r=f(r);a=f(a);s=r+':'+a;if(!(s in S))S[s]=[96,a.length,...a.split('').toReversed().map(t),...(r?[1,t(r)]:[0])];return Object.keys(S).indexOf(s)}
  let Ys="+     -     *     %     !     &     |     ^     Dv    <     Mo    >     Sh    <<    >>    ==    ~     <=    >=    Lt    Gt    Le    Ge"
  let YY="6a7ca06b7da16c7ea26d7fa36f81007183007284007385006e7f004853637082004a55647688007486007587004651614752624c57654e59664954004b56004d58004f5a00".match(/..?/g).map(x=>parseInt(x,16))
  let o2=(x,t,i)=>{t=it(t);if(t<0||t>2)e(x);i=Ys.indexOf(x[1])>>1;if(i<0)e(x);return YY[t+i]||e(x)}
  let lo=x=>{let o=[0],i,T;x[4].slice(1).forEach(x=>{T=t(x.T);o[o.length-1]==T?o[o.length-2]++:o.push(1,T)});o[0]=o.length>>1;return o}
  let cn=t=>[0x41,0x41,0x42,0x44]["ipjf".indexOf(t)]
  let Ca={0:0,1:167,10:172,11:0,22:0,33:0}
  let Ti=(x,i)=>(i=T.indexOf(x),i>=0?i:T.push(x)-1)
  let co=x=>{let o=[],O=(...x)=>o.push(...x.flat()),fc=x=>x.slice(1).forEach(f),f1=x=>f(x[1]),fd=x=>x.slice(1).forEach((x,i,a)=>i==a.length-1?f(x):dr(x)),
   lu=(x,i)=>(i=L.indexOf(x[1]),i>=0?O(32,i):((i=F.indexOf(x[1])),i>=0)?O(cn(0),eu(Ti(i))):e(x)),
   dr=x=>(f(x),x[0]=='asn'&&o[o.length-2]==34?o[o.length-2]--:O(26)),
   dy=(x,s)=>((x[1][0]=='opr'||e(x)),f(x[3]),f(x[2]),O(o2(x[1],x.T))),
   as=x=>(x.length!=4||x[1]!=':'?e(x):f(x[3]),lu(x[2]),o[o.length-2]+=2),
   cs=x=>{f(x[2]);let i=10*it(x[1])+it(x[2].T);if(!(i in Ca))e(x);i=Ca[i];if(i)O(i)},
   nm=x=>O(cn(x.T),x.T=='i'||x.T=='p'?ei(+x[1]):x.T=='j'?en(BigInt(x[1])):x.T=='f'?[...uf(+x[1])]:e(x)),
   kn=x=>{let i,n=1+Kn.indexOf(x[1]);O(cn('i'),4+n,16);i=F.indexOf('Ktx');i<0?e(x):O(eu(i))},
   ca=x=>{let i=x.length;if(Kn.includes(x[1]))return kn(x);while(--i>1)f(x[i]);O(16);i=F.indexOf(x[1]);i<0?e(x):O(eu(i))},
   sh=(s,x)=>(x.T!='i'?e(x):x[0]=='num'?O(65,ei((+(x[1]))<<s)):(f(x),O(65,ei(s),74))),
   ix=x=>{let i,r=[0,45,40,41,43,253][i=1+"cijfz".indexOf(x.T)],s=[0,0,2,3,3,4][i];if(!r)e(x);sh(s,x[2]);O(r,s<4?s:0,0)},
   re=x=>{f(x[1]);x.slice(2).forEach(s=>f(N(x.i,'cal','R0',N(x.i,'sym',s))))},
   //lod=(x,O,i)=>(i=["b_","i_","I_","ff"].indexOf(x[1][1]),i<0?0:O([45,40,41,43][i],i==0?0:i==1?2:3,0))
   m={bdy:fd,ret:re,dya:dy,sym:lu,blk:fd,asn:as,num:nm,cst:cs,cal:ca,idx:ix},f=x=>(m[x[0]]||e(x))(x);O(lo(x));f(x[5]);if(!(x[2][1]))O(26);O(11);return o}
  E.push([...ns("memory"),2,0]);
  let fn=a.filter(x=>x[0]=="fun");fn.map(x=>sg(x[2][1],x[2][2]));F=fn.map(x=>x[1][1])
  let loc=x=>{let r=[[],[],[],[]];x.forEach(x=>r[it(x.T)].push(x[1]));return r.flat()}
  ws(1,Object.values(S)); //1type 2import 3func 4table 5memory 6global 7export [8start] 9element 10code 11data
  ws(3,fn.map(x=>eu(sg(x[2][1],x[2][2])))) //;ws(4,[[112,0,...eu(te)]]);
  ws(5,[[0,1/*block*/]])
  E.length?ws(7,E):0;
  ws(10,fn.map((x,r)=>(L=[...x[3].slice(1).toReversed().map(x=>x[1]),...loc(x[4].slice(1))], r=co(x),[...eu(r.length),...r])))
  return new Uint8Array(o)} 

/*
let wb=a=>{let o=[0,97,115,109,1,0,0,0],p=(...x)=>o.push(...x)  //1type 2import 3func 4table 5memory 6global 7export [8start] 9element 10code 11data
 let e=(x,y)=>{throw new Error(`@${x.i}: ${y}`)}
 let us=x=>new TextEncoder().encode(x),uf=x=>{let b=new ArrayBuffer(8),v=new DataView(b);v.setFloat64(0,Number(x),1);return new Uint8Array(b)},vals=x=>Object.values(x)
 let eu=(x,b,r)=>{r=[];do{b=x&127;r.push((x>>>=7)?b|=128:b)}while(x);return r}
 let en=(x,b)=>{let r=[];while(1){b=x&127n;x=x>>7n;if((!x)&&!(b&64n)||(x==-1n&&(b&64n))){r.push(Number(b));break};r.push(Number(b|128n))};return r}
 let ei=(x,b)=>{let r=[];while(1){b=x&127;x>>=7;if(x==0&&!(b&64)||(x==-1&&(b&64))){r.push(b);break};r.push(b|128)};return r}
 let ws=(x,y)=>(y=[...eu(y.length),...y.flat()],p(x,...eu(y.length),...y))
 let t=x=>[0,127,126,124][1+"ijf".indexOf(x)]
 let S=[],F={},G={},D=[],nf=0,ng=0,T=[],te=0,mm=0,E=[],sig=(x,i)=>(i=S.indexOf(x),i<0?S.push(x)-1:i),sfun=(x,s)=>(x.T?x.T:"_")+x[2].slice(1).map(x=>x.T).join(""),simp=x=>(x.T?x.T:"_")+x.slice(2).map(x=>x.T).join("")
 let Y="6a7ca06b7da16c7ea26d7fa36f81007183007284007385006e7f004853637082004a55647688007486007587004651614752624c57654e59664954004b56004d58004f5a00".match(/..?/g).map(x=>parseInt(x,16))
 let X="00009a0067790000687a0000697b0000".match(/..?/g).map(x=>parseInt(x,16))
 let N1="4648494c4d5153545758474e4f4a4b52595a5556".match(/..?/g).map(x=>parseInt(x,16))
 let N2="474e4f4a4b52595a55564648494c4d5153545758".match(/..?/g).map(x=>parseInt(x,16))
 let sg=x=>[96,x.length-1,...x.split("").slice(1).map(t),...(x[0]=="_"?[0]:[1,t(x[0])])]
 let cn=t=>[0x41,0x42,0x44]["ijf".indexOf(t)]
 let gl=(x,y)=>G[x[1]]={name:x[1],mut:y,t:x.T,e:x.length>2?x[2][1]:0,idx:ng++}
 let ns=x=>[...eu(x.length),...us(x)]
 let not=(t,O)=>{let z=o[o.length-1],i=N1.indexOf(z);i<0?O(t=="i"?69:80):o[o.length-1]=N2[i]}
 let icl=(x,O,i)=>["_tab","tab","Tab","tabf"].includes(x[1][1])?(i=S.indexOf((x.T?x.T:"_")+x.slice(2,-1).map(x=>x.T)),i<0?e(x,"unknown function signature"):O(17,0,eu(i))):0
 let sto=(x,O,i)=>(i=["_b","_i","_I","_f"].indexOf(x[1][1]),i<0?0:O([58,54,55,57][i],i==0?0:i==1?2:3,0))
 let lod=(x,O,i)=>(i=["b_","i_","I_","ff"].indexOf(x[1][1]),i<0?0:O([45,40,41,43][i],i==0?0:i==1?2:3,0))
 let cnv=(x,O,i)=>(i=["s$","i$","f$","U$","I$","$f"].indexOf(x[1][1]),i<0)?0:O([192,167,170,173,172,183][i]) //s$(i32.extend8_s) i$(i32.wrap_i64) f$(i32.trunc_f64_s) U$(i64.extend_i32_u) I$(i64.extend_i32_s) $f(f64.convert_i32_s)
 let mem=(x,O)=>(x=="memgrow"?O(64,0):x=="_memcpy"?O(252,10,0,0):x=="_memfill"?O(252,11,0):0)
 let lo=x=>{let o=[0],i,T;x[3].slice(1).forEach(x=>{T=t(x.T);o[o.length-1]==T?o[o.length-2]++:o.push(1,T)});o[0]=o.length>>1;return o}
 let co=(l,L,x)=>{let o=[],O=(...x)=>o.push(...x.flat()),f=x=>(({ret:x=>(f(x[1]),O(15)),blk:x=>x.slice(1).map(f), drp:x=>(f(x[1]),O(26)),
  dya:x=>(f(x[2]),f(x[3]),O(Y["+  -  *  /  %  &  |  ^  div<  rem>  shr<< >> == != <= >= lt gt le ge".indexOf(x[1])+"ijf".indexOf(x.T)])),
  mon:x=>(f(x[2]),x[1]=="!"?not(x.T,O):O(X["-   clz ctz cnt".indexOf(x[1])+"ijf".indexOf(x.T)])),
  num:x=>O(cn(x.T),x.T=="i"?ei(+x[1]):x.T=="j"?en(BigInt(x[1])):[...uf(+x[1])]),
  asn:x=>(f(x[2]),(x[1][1]in l)?O(34,l[x[1][1]]):O(36,eu(G[x[1][1]].idx),35,eu(G[x[1][1]].idx))),
  set:x=>(f(x[2]),(x[1][1]in l)?O(33,l[x[1][1]]):O(36,eu(G[x[1][1]].idx))),
  sym:x=>(x[1]in l)?(o[o.length-2]==33&&o[o.length-1]==l[x[1]]?o[o.length-2]++:O(32,l[x[1]])):(x[1] in G)?O(35,eu(G[x[1]].idx)):e(x,"unknown symbol"),
  cnd:x=>(f(x[1]),O(4,t(x.T)),f(x[2]),O(5),f(x[3]),O(11)),
  iff:x=>(f(x[1]),O(4,64),f(x[2]),(x.length>3?(O(5),f(x[3])):0),O(11)),
  whl:x=>(O(2,64,3,64),f(x[1]),not("i",O),O(13,1),f(x[2]),O(12,0,11,11)),
  dow:x=>(O(3,64),f(x[1]),f(x[2]),O(13,0,11)),
  cal:x=>(x.slice(2).map(f),icl(x,O)?0:sto(x,O)?0:lod(x,O)?0:cnv(x,O)?0:mem(x[1][1],O)?0:O(16,F[x[1][1]]?F[x[1][1]].idx:e(x,"unknown func"))),
  })[x[0]])(x);O(L);f(x);if(o[o.length-1]==15)o.pop();O(11);return o.flat()}
 let fn=x=>{let l={};[...x[2].slice(1).map(x=>x[1]),...x[3].slice(1).map(x=>x[1])].map((x,i)=>l[x]=i);F[x[1][1]].code=co(l,lo(x),x[4])}
 a.forEach(x=>x[0]=="imp"?x.slice(1).map(x=>F[x[1]]={name:x[1],sig:sig(simp(x)),imp:x[2].split("."),idx:nf++})
   :x[0]=="fun"?F[x[1][1]]={name:x[1][1],sig:sig(sfun(x)),imp:"",idx:nf++}
   :x[0]=="tab"?(T.push([+x[1][1],x.slice(2).map(x=>x[1])]),te=Math.max(te,(+x[1][1])+x.length-2)):x[0]=="mem"?(x.length==2?(mm=+x[1][1],E.push([...ns("memory"),2,0])):D.push([+x[1][1],x[2]]))
   :x[0]=="exp"?x.slice(1).map(x=>E.push([...ns(x[1]),0,...eu(F[x[1]].idx)])):x[0]=="var"?x.slice(1).map(x=>gl(x,1)):x[0]=="con"?x.slice(1).map(x=>gl(x,0)):0);
 a.forEach(x=>x[0]=="fun"?fn(x):0);
 ws(1,S.map(sg));ws(2,vals(F).filter(x=>x.imp).map(x=>{let y=x.imp;return[...ns(y[0]),...ns(y[1]),0,...eu(x.sig)]}))
 ws(3,vals(F).filter(x=>!x.imp).map(x=>eu(x.sig)));ws(4,[[112,0,...eu(te)]]);if(mm)ws(5,[[0,mm]])
 ws(6,vals(G).map(x=>[t(x.t),x.mut,...[cn(x.t),...(x.t=="f"?uf(x.e):ei(x.e)),11]]));
 E.length?ws(7,E):0;
 T.length?ws(9,T.map(x=>[0,0x41,...eu(x[0]),11,...x[1].map(x=>eu(F[x].idx)).flat()])):0
 ws(10,vals(F).filter(x=>x.code).map(x=>[...eu(x.code.length),...x.code]))
 D.length?ws(11,D.map(x=>[0,0x41,...eu(x[0]),11,...eu(x[1].length),...x[1]])):0;return new Uint8Array(o)}
*/
 
 //if(!P)return`Ktx(K:ip){jy|jx<<56}R0(:j){x}Sub{y}f{a-a:y}`
 //if(!P)return`f{x;y}`
 if(!P)return`Ktx(K:ip){jy|jx<<56}R0(:j){x}Add{y}f{x;+}`
 if(!P)return`f{a:x;a}`
 if(!P)return`f{x:+}`
 if(!P)return`f{x[4]+:5}`
 if(!P)return`f{x:4;x}`
 if(!P)return`h{x[i]:5}`
 if(!P)return`f{@[x;0;2]}`
 if(!P)return`f{@[x;0;+;2]}`
 if(!P)return`f{x:3}g{x+:5}h{x[i]:5}m{x[i]+:5}` //x:x<5
 if(!P)return`Ki(K:i){Ktx[2;px]}Ktx(K:ip){jy|jx<<56}modas(i:i){x-:5}idxas{Ix1:3}idxmod{Ix1+:3}`
 if(!P)return`Ki(K:i){Ktx[2;px]}Ktx(K:ip){jy|jx<<56}\nK0(:j){t:0;t:x>>56;p:px-8;c:Ix[-2]-1;!c? if(!t)n:Ix[-1];n/K0 Jxi; Mf px-8; :Ix[-2]:c}`
 if(!P){return`

Ki(K:i){Ktx[2;px]} Kf(K:f){r:Ktn[3;1];Fr0:x;Ktx[-3;px]} Kz(K:z){r:Ktn[1;4];Zr0:x;Ktx[-4;px]}
K0(:j){t:0;t:x>>56;p:px-8;c:Ix[-2]-1;!c? if(!t)n:Ix[-1];n/K0 Jxi; Mf px-8; :Ix[-2]:c}
Ktx(K:ip){jy|jx<<56}
Ktn(K:ii){r:Ma 8+y<<x?[3;0;2;3;4];r+:8;Ir[-2]:1;Ir[-1]:y;Ktx[x;r]}
Ufy{(!nx? x :t:tx0);!t? x :(n:nx)/if(t~txi)t:0;break; t?[n#Cxi;n#Ixi;n#Fxi;n#Zxi]}


`.trim()
 }

 
 /*
 P=`/you can edit the input
 f{x+/a:y}        /dyadic with local a
 g(i:Kii){x;y;z}  /func with signature
 h{1+x? 2*x :3*y} /ternary
 q{if(1<x)x:+1;y*:2; x+y}  /if-body extends to ;(space) without {}
 f{{x+y}[1;2]}    /inner lambda needs to be liftet
 `
 */
 
 let indicate=(s,i,p)=>{let v=p.split("\n"),n=v.map(x=>1+x.length),c=i,l;for(l=0;l<n.length;l++){if(n[l]>c)break;c-=n[l]};return `k:${1+l}:${1+c} ${s.split(' ')[0]}\n${v[l]}\n${" ".repeat(c)}^${s.replace(/@\d+ /,"")}\n`}

 try{let f,a=pars(P);if(S=="pars")return a
  for(f of[comp,lift,maco,btin,type,digr,asin,call,loop,cord,swap,indx,refc]){f(a);if(S===f.name)return a};
  return A=="c"?cc(a):A=="w"?wa(a):"l"==A?lifmt(li(a)):lifmt(Li(a))
 }catch(e){let s=e.message;console.error(e);return s[0]=='@'?indicate(s,+s.slice(1,s.indexOf(' ')),P):s}
}

if("undefined"!=typeof Deno){
 let P="",A="c",f="out",s,argv=process.argv.slice(2),read=x=>new TextDecoder("utf-8").decode(Deno.readFileSync(x))
 for(s of argv){
  if("c w l t".includes(s))A=s;
  else if(s.endsWith(".k")){f=s.slice(-2);P+=read(s)}
  else{throw new Error(s)}}
 if(!P)P=kc(0);
 f+="."+A; s=kc(P,A); if(s.constructor==Uint8Array){Deno.stdout.write(s);Deno.exit(0)};if(s.startsWith("k:")){console.error(s);Deno.exit(1);} console.log(s);}


