#define lZ() r(~u0,i(NX,r=li(r,O))r=li(r,s(4,r));r=li(r,s(8,r));r=li(r,s(16,r)))[7]
#define mZ() r( u0,i(NX,r=mi(r,O))r=mi(r,s(4,r));r=mi(r,s(8,r));r=mi(r,s(16,r)))[7]
#include"a.h"//(c)2024 arthur whitney(l)MIT ! #$%&'()*+,-./:;<=>?@[\]^_{|}~ [rrit]n f(ty,ti(tx?:Tx))
#define S(f,i) AN(f,"mov %rcx,%r10;mov $"#i",%rax;syscall;ret",Ux,...)//void _start(){asm("lea 8(%rsp),%rsi;call main");}
AN(ut,"rdtsc;shl $32,%rdx;or%rdx,%rax;ret")S(_w,0)S(w_,1)S(f_,2)S(_f,3)S(_l,4)S(m_,9)S(_k,60)V(sq,I(sqrtps)(a),Va)U(b2,I(movmskps)(a),Va)U(b_,I(pmovmskb)(a),Va)
VF(li,I(pminud)(a,b))VF(mi,I(pmaxud)(a,b))VF(a5,bl(I0/16==b/16,i0(a,b),i0(I(permvarsi)(a,4+I0/4),b)))VF(gg,I(vfmaddsubps)(a,i2(b,0xa0),(e5)i2(a,0xa0+0x11)*(e5)i2(b,0xa0+0x55)))
V(s,Va=I0-c;a<32&a5(v,a),cc,Vv)V(_b,Vv=1<<I0%8&a5(U0+x,I0/8);1&0<v,Ux)Ui(g_,ij=N&i;j>>2|b(29)&m(g,i)-g)f(G_,g_(x)|g_(x>>32)<<30)Ui(_g,ij=i&b(29);j?N&i<<2|j+g:0)f(_G,_g(x)|_g(x>>30)<<32)
g(_M,W-=1<<f;xx=M[f];M[f]=x)Ui(M_,Ux=M[i];x?(W+=1<<i,M[i]=xx,x):31>i?_M(i,M_(i+1))+(32L<<i):_K())g(T,ii=l2(1==f?32+x/8:39+(x<<L[f]));r(32+M_(i),R_=i<<16|f<<24|x<<32))
f(_r,P(px||tx,x)P(M1&rx,--rx;x)if(!Tx)n(_r(xU))_M(mx,x-32);x)f(r_,P(px||tx,x)P(M1&++rx,x)_K())U(dn,n5(rV=O)r+n,Ur,Un,Ux)U(jn,R(Tx,n,dn(r,(U)n<<Lx,x+((int)j<<Lx))),ij,in,Ux)
g(_i,ii=f;t(Tx,$6(Tx,XU,1&xb>>i%32,o,xu,xu,G_(xU))))G(i_,ii=f;$6(Tx,xU=a,a?xb|=1<<i%32:(xb&=~1<<i%32),o=a,xu=a,xu=a,xU=_G(a));x)f(v_,R(tx,1,*UR=5==tx?_G(x):x))
f(sb,ii=nx/64;ij=nx%64;if(j)xU&=b(j);r(0,N6(r+=nb(xU))))g(bo,in=sb(x);!--f?ti(n):tb(5>f?n==nx:0<nx))g(bp,Un=0;_R(1,nx,N6(Ua=xU;n|=a<<1;rU=f?$6(f-5,a&n,a|n,~a&n,a&~n,0,a^n):n;n=a>>63)))
U(f1,KX($(_i(i,x))),_$,Ux)U(fr,KX($(f,_i(i,x))),_$,uf,Ux)G(e2,KX(jJ(f,ta?a:AU,tx?x:XU)))f(vk,Q(x)it=a(xx,ta);P(!t,x)n(P(t!=tU,x))Qz(2!=L[t])TX(3,_u))F(dx,if(!Tx)n(XU)dn(a,Nx,x))
g(t_,x=f-1>Tx?t_(f-1,x):x;$4(f-2,_N(_b(xu)),x,TX(4,C(e5,(i5)Ix)),TX(5,Uu)))v1(_t,3>Tx?_N(O+(26>O-65&32)):TX(Tx-1,5>Tx?C(i5,Ex):sq(_u*_u+u_*u_)))V1(j4,Qt(4<Tx)x=4>Tx?t_(4,x):x;_N(sq(Ex)))
F(V_,a=ta?v_(a):a;x=tx?v_(x):x;Qz(Bx)a=Tx>Ta?t_(Tx,a):a;x=Ta>Tx?t_(Ta,x):x;_a(_R(Ta,na+nx,dx(dx(r,a),x))))F(_V,Qr(ta||tx)Qt(3!=Ta||Bx)_a(_x(KN(na,jn(au,au_-au,x)))))F(Ll,V_(a,v_(x)))
f(p0,i_(0,0,jn(-1,nx,x)))f(Ss,Ua=p0(x);*sa=x_;a=n_(_a(aA(8,tc(x_),a)));x=_V(a,x);n(Ur=xU;(sr)[--nr]=0)x)g(sS,in=f?nx:0;ij;n(n+=j=nU)_R(a(xx,Ta),n,Ua=r;n(a=dx(a,xU);if(f)*sa++=f)))
g(nz,Vv=3>tx?cx+c0:5>tx?u0+ix:U0+_G(x);TN(tx,f,v))G(NN,Qz(!ta)P(tx,nz(ia,x))P(1==nx,Tx?nz(ia,_v(x)):_x(KN(ia,_i(0,x))))Qn(ia>nx)_x(jn(f?ia:0,f?nx-ia:ia,x)))
g(Vc,V_(x,tc(f)))G(c3,$3(f,QZ,Qr(Tx)sS(a,x),Qr(!Tx)Ss(Vc(a,x))))G(i3,Qz(f)P(2==Tx,x=Vc(0,x);_x((ia?_1:_0)(sx)))QZ)f(ra,QZ)
Ui(g0,in=i;R(3,n,i(nr,ru=i)))Ui(g1,in=i;R(4,n,i(nr,ru=ue(1.f*i/n))))Ui(g2,in=i;KN(n,Ua=(U)ue(1.f*i/n)<<32;R(5,n,i(nr,rU=a|ue(1.f*i/n)))))
g(fo,P(Bx,bo(f,x))f-=5;ii=nx/8;if(nx%8)O=bl(nx%8>I2,O,f?u0:~u0);t(Tx,$3(f,lZ(),mZ(),3==Tx?s_(u):ue(s_(e)))))g(fs,Qz(2!=Lx||1!=f)3==Tx?S_(i):S_(e))
g(fp,P(Bx,bp(f,x))P(!f--,p0(x))Ur=x;r-=1<<Lx;Ua=R_;R_=UX[-1];x=i_(0,xx,aA(f,x,r));R_=a;x)G(p3,Qd(!pa)P(18==a,Qr(1-f||Tx)sS(0,x))_x($3(f,fp,fo,fs)(a,x)))
Ui($i,N&i?1|$i(-i)<<4:r(0l,do r=r<<4|4+i%10;W(i/=10)))U($e,0>e?1|$e(-e)<<4:1e-9>e?4:1e9<e?52:1>e?3|$e(1/e)<<4:eq((int)e/e)?$i(e):x($i(.5+1e4*e),in=z4(x)-4<<2;2<<n|b(n)&x|(~b(n)&x)<<4),ee)
f($t,x=$3(tx-3,$i(ix),$e(ex),x=_G(x);Ua=$e(ex);x>>=32;a|(14|$e(ex)<<4)<<4*z4(a));Vv=44+(15&a5(*(V*)&x,I0/2)>>I0%2*4);ns(z4(x),&v))
nS(i$,48>*s?-i$(n-1,s+1):r(0,i(n,r=si%16+10*r)))nS(e$,P(48>*s,N|e$(n-1,s+1))ii=is(101,n,s);ue(n>i?i$(i,s)*E[s[i+1]%16]:(i=is(46,n,s),n>i?_(n-=i+1;i$(i,s)*E[n]+i$(n,s+i+1))/E[n]:i$(n,s))))
nS(t$,Ux=Ss(Vc(32,ns(n,s)));it=0;n(t=m(t,qg(58,xU)?2:qg(46,xU)||qg(101,xU)))av(_R(t+3,nx,IF(2>t,n(ru=t?e$(nU,sU):i$(nU,sU)))n(in=is(58,nU,sU);rU=e$(n,sU)|e$(nU-n-1,sU+n+1)<<32))))
f(n_,_R(3,sb(x),u*s=sr;N6(Ua=xU;j(nb(a),*s++=64*i+IU(a)))))V1(d_,Qz(3!=Tx)_N(Ix/f))V1(_d,Qz(3!=Tx)_N(Ix%f))v1(uu,P(4<Tx,TX(4,u_))x=4>Tx?t_(4,x):x;TX(5,Uu<<32))
v1(no,_x($3(Tx-1,N(~Ix),bC(32>=O),bI(0==Ix))))g(T_,tx?t(f,$3(f-3,ix,ue((int)ix),G_(4>tx?T_(4,x):ix))):t_(f,x))
G(aA,4>f?N($3(Tx-3,a3(I),3>f?a3(E):Ea/Ex,Vv=ta?(e5)(U0+_G(a)):Ea;$3(f,v+Ex,v-Ex,gg(v,Ex)))):3>Tx?bC(b3(Ca,Cx)):bI(b3(Ia,Ix)))G(aa,4>f?4>tx?ti(a3(i)):te(2<f?ea/ex:a3(e)):tb(b3(ia,ix)))
G(jJ,ii=ta?:Ta;ij=tx?:Tx;P(!i||!j,e2(f,a,x))it=m(3>f?3:4>f?4:1,m(i,j));a=t>i?T_(t,a):a;x=t>j?T_(t,x):x;P(tx,Qz(!ta)5>tx?aa(f,a,x):_v(jJ(f,a,v_(x))))_a(_x(aA(f,a,x))))F(A_,Qt(3!=tx)_i(ix,a))
F(_A,QZ)F(mm,QZ)F(No,QZ)F(Dt,QZ)f(dt,QZ)G(AA,ta?2==ta?_(ij=a-101;Qd(3==f)j4(f+2*j,x)):f&&3==ta?d_(f,x):jJ(2,f?te(1/ea):a,x):qf(a)?z(&x,a):!tx&&(!Tx||4==Tx)?mm(a,x):(f?A_:_A)(a,x))
F(N_,Qt(3!=ta)_d(ia,x))f(wd,n_(no(fp(8,x))))f(ff,P(tx?:Tx,uu(x))QZ)f(rr,Qz(2!=Tx)_R(2,nx,n(rc=(sx)[nx-1-i])))
f(or,QZ)f(ou,Q(x=or(x))Qt(Bx||2<Lx)A_(x,wd(x)))f(_o,QZ)f(o_,QZ)f(og,QZ)f($,tx?lx?$t(x):2>tx?v_(tc(48+ix)):$(v_(x)):$3(Tx-1,TX(2,32+14*_b(xu)),10!=x_&&qe(x)?_p(x):x,f1($,x)))
Z_(H,ff,qr,qr,qr,qr,no,dt,g0,qr,ra,g2,_t,g1,v_,$,qr,qr,qr,qr)Z_(F,ff,rr,_o,o_,og,no,dt,n_,_v,ou,_n,_t,or,v_,$)Z_(G,No,Dt,N_,_V,V_,Ll)
g(a1,P(!f,x)P(20>f,Qr(px)$5(--f,jJ(0,ti(1),x),jJ(0,ti(-1),x),jJ(2,r_(x),x),j4(-1,x),(tx?H:F)[f-4](x)))Qr(tx||!Tx)f-=20;x=1<f?t_(4,x):x;_x($3(f,fo(5,x),fo(6,x),Ua=fo(1,x);3>f?a:te(ea/nx))))
G(a2,P(20>f,P(pa||px,Qr(13!=f)a1(a,x))9>--f?jJ(f,a,x):12>f?G[f-9](a,x):14>f?AA(1&f,a,x):16>f?NN(1&f,a,x):G[f-13](a,x))Qz(29>f)f-=29;!f&&9>a-11?vk(f1(F[a-5],x)):$3(ta-2,c3,i3,p3)(f,a,x))
Zc*pP="+-*sqr %sqrt &flip |flop <asc >desc =group ~ . !index @first ?nub  #count _floor ^order ,$\n+-*    %     &and  |or   <    >     =      ~ . !index @at    ?find #take  _drop  ^cut   ,$";
U(z,Ua=x;x=xx;Ur;_W(ij=o%32;Q(r=*c=$4(o/32,--c;22>j?_i(j,a):ti(j-22),a1(j,r),a2(j,r,*++c),U*a=_&&3>j-24?_+j-24:D+j;IF(128>o,--i;_r(*a);*a=r)--c;r_(*a))))*c++,U*_,Ux)
Zc*P_=" L OSDE]  CARBK^@ GIHNM _ QP F J",*P="3  5       01     2  4",*_P=":+-*%&|<>=~.!@?#_^,$LMSAVD...'/\\;()[]";f(_p,B3(90,32>O,O+26,96<O,O%32+96,a5(*(V*)_P,O%32)))
f(p_,B3(O,10>O-48,O-26,26>O-97,O+(58!=s(-1,O)&32),bl(26>O-65,a5(*(V*)P,O-65)+4,a5(*(V*)P_,O-32-(57<O&10)-(90<O&26)-(122<O&27))-32)))
ZU r,rd();f(ap,UR[nr]=x;nr++)f(pz,i(4,x=rd(2+i,x))x)f(Pz,qg(57,x)?(x=f1(pz,Ss(Vc(57,x))),a(V_(tc(32),nz(nx-1,tc(83))),V_(a,sS(0,x)))):pz(x))
f(Bq,bC(34==O))f(Bt,bp(5,bC(Vv=10>O-48;v|s(-1,v)&(45==O&~s(1,10>O-48|26>O-97)|(46==O|58==O|101==O|32==O)&s(1,v)))))f(Bp,0)g(nv,bC(Va=160>O&32<O-32;s(1,a)&(f?~a:a)))
f(Bn,nv(0,x))f(Bv,nv(1,x))f(Bo,bC(3>O-61))nS(q$,av(ns(n-2,s+1)))nS(p$,Pz(ns(n-2,s+1)))nS(v$,r(rr(ns(n,s)),*sr+=32))nS(o$,if(1==*s/32)*s=ap(*s%32);v$(n,s))nS(n$,V_(nz(n-1,tc(77)),ns(n,s)))
Z_(P0,Bq,Bt,Bp,Bo,Bv,Bn)Z_(P1,q$,t$,p$,o$,v$,n$)g(prr,wx(x);wx(Vc('^',nz(f,tc(32))));96)
g(rd,Ua=P0[f](x);P(!a,x)a=n_(bp(f?10:0,a));_a(na?_x(c(ij=0;i(na,ik=au-1;d=dn(d,k-j,x+j);j=++i<na?au:nx;*sd++=160*(1<f)+ap(P1[f](j-k,sx+k)))dn(d,nx-j,x+j))):x))
F(pS,n(IF(160>o,*sa++=o)a=pS(a,UR[o%32]))a)Us(ps,Ux=xs(s);r=T(0,32);nr=1;i(2,x=rd(i,x))ii=ig(224,x=p_(x));P(nx>i,prr(i,xs(s)))*UR=_x(c(pS(d,x=pz(x))));r)
Us(zs,P(92==*s,ys(s+1))P(26u>*s-97&&32==s[1]||58==s[1],_r(D[*s%32]);D[*s%32]=(58>*s?ps:zs)(s+2);0)Qx(ps)_x(z(0,x)))g(ts,Q(x)Ua=ut();i(f,Q(_r(z(0,x))))_x(ti(((ut()-a)/2.4e6-f/2e5))))
Us(os,P(!*s||39==*s,0)Qx(zs)x?wx(x):0)Us(ls,Qx(_0)n(Q(nU?os(sU):_x(96)))_x(0))Us(ys,if(!*s)_k(0);$5(is(*s,4,"ltvw"),ls(s+2),ii=is(32,20,s);si=0;ts(i?zs(s+2):1,ps(s+i+1)),QZ,ti(W),xs(pP)))
int main(int n,char**_){A=(U)main>>32;M[31]=m_(0,32L<<31,3,A?0x1042:0x4022,0,0);if(*++_)ls(*_);cc[256];W(1)wc(32),c[_w(0,(U)c,256)-1]=0,*c?os(c):0;}

f(_z,px?v_(tc(_P[x])):tx||!Lx?$(x):qf(x)?$(_v(x)):sS(32,f1(_z,x)))f(wx,x=sS(10,px||tx||Tx||qf(x)?v_(_z(x)):f1(_z,x));w_(2,x,nx);_x(0))
Us(lf,it[36];!_l((U)s,(U)t)&&1&t[A?1:6]>>15?t[A?24:12]:0)Us(_1,in=lf(s);Qs(!n,s);ii=f_((U)s,0);R(2,n,_w(i,(U)sr,n);_f(i)))Us(_0,Qx(_1)Qd(10!=x_)Ss(x))
