#include"v.h"
#define b4(g,a,b,x...) e2(g,Se(r(ze,I=n4(I);Ez[4]={};i(I/4,i(4,zi+=a*X++))i(I%4,r+=b Xi)i(4,r+=zi)))[15],x)
#define ft(m,o,O,t,T) t##6(O##t,i(6-m,x=O##T(x,S##m(i,x)))x,Vx)i2(o##t,((t##6)O##t(r(z##m,i(nm(m,I),r=O##T(r,Xi)))))[b(6-m)],iI,EX)_(o##T,T##z=z0;i(nm(m,I),Ri=z=O##T(z[b(6-m)]-z##m,O##t(Xi))),U3)
b4(se,,,iI,EX)b4(vv,*A++*,Ai*,iI,EA,EX)i2(s2,i(n4(I),Ub=b2(n==Ri);P(b,16*i|iu(b)))I,in,iI,IR)ft(0,s,S,g,G)ft(0,m,M,g,G)ft(2,m,M,i,I)ft(2,s,S,i,I)e2(me,ii=mi(I,X);*(e2*)&i,iI,EX)
_(mm,i(3+I>>2,j(J,Ez[4]={};h(H,kk(4,z[k]+=A[H*(4*i+k)+h]*X[J*h+j]))kk(4,t?R[J*(4*i+k)+j]+=z[k]:(R[J*(4*i+k)+j]=z[k])))),it,iH,IJ)
_(MM,J/=16;$(H*J-1>>12,i(I*J,Ri=z0)h(H/64,j(J/4,mm(1,64,I,4,A+H*64+h,R+J*4+j,X+J*H*(64+h)+j))))mm(0,H,I,J,R,A,X),iH,IJ)_(BV,i(n9(I),Ri=$3(j,AI&XI,AI|XI,~XI)),ij,U4)
#define mM(n,i) ik=1<<i;h(1<<6-n-1-i,j(k,ii=2*h*k+j;zi=l##n(zi,r(zk,zk=m##n(zi,r)))))
_(mv,i(I,((e2*)R)[i]=vv(J,A+J*i,X)),IJ)_(vm,J/=16;j(J/4,Ez[4]={};i(I,j(4,zj+=Ai*Xj)X+=J)j(4,*R++=zj)X-=I*J-4)i(J%4,Ri=r(ze,i(I,r+=Ai*X[J*i])++X)),IJ)
_(t0,i(I>>6,j(J>>6,Ez[1<<6];i(1<<6,zi=Xi)i(6,mM(0,i))i(1<<6,Ri=zi))),iJ,U3)_(t2,i(I>>4,j(J>>4,Ez[1<<4];i(1<<4,zi=Xi)i(4,mM(2,i))i(1<<4,Ri=zi))),iJ,U3)
#define V2(g,z,x...) _(g,i(n4(I),Ri=z),x)
#define V0(g,z,x...) _(g,i(n6(I),Ri=z),x)
#define VB(g,a,z) V0(g,b0(z),ij,a,iI,U*R,VX)
VB(cV,in,3>j?$3(j,(i0)n<Xi,(i0)n>Xi,(i0)n==Xi):GI($3(j-3,n<X8,n>X8,n==X8)))VB(CV,VA,3>j?$3(j,Ai<Xi,Ai>Xi,Ai==Xi):GI($3(j-3,A8<X8,A8>X8,A8==X8)))V0(n0,I0|(i0)(64*i),iI,IR)V0(gw,n-z2,in,iI,IR)
V0(r0,R0(*--X),U3)V2(r2,R2(*--X),U3)V2(gb,GB(((U*)X)[i]),U3)V2(gi,GI(X8),U3)V2(ig,IG(((g4*)X)[i]),U3)V2(ei,EI(Xi),U3)V2(ie,IE(Xi),U3)V2(eZ,E(Xi),U3)V2(q_,Xi*Xi,U3)V2(_q,qq(Xi),U3)
V2(jj,JJ(),iI,IR)V2(iV,$3(j,n+XI,n-XI,n*XI),ij,in,U3)V2(eV,$4(j,e+Xi,e-Xi,e*Xi,e/Xi),ij,ee,U3)V2(IV,$3(j,AI+Xi,AI-Xi,AI*Xi),ij,U4)V2(EV,$4(j,Ai+Xi,Ai-Xi,Ai*Xi,Ai/Xi),ij,U4)
V2(DM,x(n*XI>>16,j?XI-j*x:x),ij,in,U3)V2(gV,1&$3(j,(i0)n<XV,(i0)n>XV,(i0)n==XV),ij,in,U3)V2(n2,I2|16*i,iI,IR)V2(a2,A(A,Xi,2),U4)V2(EZ,Ai*Xi/(1+E(-Xi)),U4)
_(sZ,ee=me(I,X);i(n4(I),Ri=E(Xi-e))e=1/se(I,R);i(n4(I),Ri*=e),U3)_(a0,i(n4(I),((g4*)R)[i]=c(A(A,Xi,1),g4)),U4)_(RZ,ee=1/qq(vv(I,X,X)/I-ze)[0];i(n4(I),Ri=e*Ai*Xi),U4)
