a:_.[ch] a.c makefile
	clang-13 -ffast-math -Os -oa a.c -nostdlib -w -ferror-limit=1 -fno-unwind-tables -mavx512f -mavx512vbmi 
#	clang-13 -v -ffast-math -Os -oa a.c -nostdlib -w -ferror-limit=1 -fno-stack-protector -target arm64-apple-macos -nostdlib -fuse-ld=lld

#	clang-13 -ffast-math -Os -oa a.c -nostdlib -w -ferror-limit=1 -fno-unwind-tables -mavx2


 
