#include"a.h"//mdkv drx ma h(6,j(m,i(3,ai+=ki)) J(m,e=max)J(m,s+=ai=E(ai-e))j(n,i(3,ri=a/s*vi))
_e(se,n=n4(n);Ez[4]={};i(n/4,z4(X_))Eb={};i(4,b+=zi)i(n%4,b+=X_)sE(b)[15],in,EX)_e(Sv,n=n4(n);Ez[4]={};i(n/4,z4(A_*X_))Eb={};i(4,b+=zi)i(n%4,b+=A_*X_)sE(b)[15],in,EA,EX)
MN(vm,VR=r;n/=16;i(n/4,Ez[4]={};EX=x;h(m,z4(X_*a[h])X+=n-4)i(4,R_=zi)x+=4)i(n%4,Ez={};EX=x;i(m,z+=*X*ai;X+=n)R_=z;++x))MN(mm,i(m,vm(m,n,r+i*n,a+i*m,x)))MN(mv,i(m,r[i]=Sv(n,a+n*i,x)))   
MN(Sm,VR=r;n/=16;i(n/4,Ez[4]={};EA=a;EX=x;h(m,z4(X_*A_)A+=n-4;X+=n-4)i(4,R_=zi)a+=64;x+=4)i(n%4,Ez={};EA=a;EX=x;i(m,z+=*X**A;A+=n;X+=n)R_=z;a+=16;++x))
_D(e6,sm,r(ze,i(m,r+=A_*X_)),im,eA,EX)_Z(sfm,Ez=ze;i(n,z=MI(z,Xi))ee=ei(mI(z)[15]);z=ze;i(n,z+=Xi=E(Xi-e))i(n,Xi/=z),in,EX)
U_(vak,im=mx;in=na;_R(tx,n,VR=sr;EA=x(b,sx);EX=sx;h(6,e2 z[n4(m)*16];i(m,zi=Sv(48,aV+3*h,X+i*n+3*h))sfm(n4(m),z);i(3,R_=sm(m,z,A+3*h)))_r(b)),Ub,Ua,Ux)
f(T_,M(mx,_R(tx+1,nx,VR=sr;$3(tx-1,XX=sx;JR(i),SX=sx;JR(e),YX=sx;JR(j)))))f(_T,M(mx,_R(tx-1,nx,VX=sx;$3(tx-2,XR=sr;JX(g4,I),IR=sr;JX(s6,E),YR=sr;JX(i5,J)))))g(T,W(i>tx)x=T_(x);x)
_G(S,Qn((i?va:ua)-ux)EE x=P0(x);in=vx;_a(_x(ma|mx?R(tx,(i?:1)*n,$(i,j(i,vm(mx,n,r2+j*n,a2+j*i,sx)))(ma?mx?Sm:mv:vm)(ma?:mx,n,sr,sa,sx)):te(Sv(nx,sa,sx)))))
g(o3,x=(i?P0:P1)(x);_x(1<i&2<tx?te(se(nx,sx)):t(tx,$6(2*i+bx/2,l0,l2,m0,m2,s0,s2)(x))))g(s3,Ez=z0;1<i&2<tx?X(z=sE(X_)+z[15]):$6(2*i+tx-1,L0,L2,M0,M2,S0,S2)(x))
_G(e3,i-=6;EE P(a,_a(X(Eb=Ex;aE[j]*b/(1+E(-b)))))P(!i--,X(E(Ex)))ee=1/(i?(e=ei(m2(x)),x=X(E(Ex-e)),se(nx,sx)):_q(Sv(nx,sx,sx)/nx-ze)[0]);X(e*Ex))
F(Dt,Qz(a)4>tx?T(4,x):_T(x))G(vv,EA=sa;_a(X(3>tx?$3(i,Ia+Ix,Ia-Ix,Ia*Ix):$4(i,*A+++Ex,*A++-Ex,*A++*Ex,*A++/Ex))))g(pe,Qz(--i-1|2-tx)ii=*x2;EA=x2-1;x=X(Ix-A_);*x2=i;x)
G(av,X(3>tx?$3(i,ia+Ix,ia-Ix,ia*Ix):$4(i,ea+Ex,ea-Ex,ea*Ex,a?ea/Ex:_q(Ex))))G(MV,Qz(mx|3-ta|nx%16)Qn(va-nx)im=nx/16;EA=sx;_x(x(a,X(A[i++%m]*Ex))))_f(_v,_x(_i(0,x)))
G(B,P(15==i,ax?_v(_T(v(x))):_T(x))a=9-i?a:(--i,t(1,0));P(aa&ax,ti($5(i-4,ia&ix,ia|ix,ia<ix,ia>ix,ia==ix)))Qz(2-tx|!aa^6>i)VA=aa?0:sa;_a(X($5(i-4,Ia&Ix,Ia|Ix,1&ia<Ix,1&ia>Ix,1&ia==Ix))))
G(A,a=a|2-i?a:r_(x);it=2<i|2<ta|2<tx;P(ax,aa?t?_v(A(i,a,v(x))):ti($3(i,ia+ix,ia-ix,ia*ix)):A(i,$4(i,x,ti(-ix),x,te(1/ex)),a))if(t)EE;(aa?av:!!ma^!!mx?MV:vv)(i,a,x))f(pi,QZ)
G(d3,in=(ia+65535)/ia;1==i|2<m(ta,tx)?A(2,1<i?te(1/ea):a,x):ax?ti(i?ix/ia:ix%ia):X(i6 z=Ix;x(n*z>>16,i?x:z-ia*x)))
F(_I,Qt(2<tx)x=T(2,x);Qn(m2(x)>=na)_a(ta?2>ta?X(g0(sa,Ix)):t(ta-tx,X(g2(sa,Ix))):RU(_i(x2[j],a))))F(I_,Qt(2-ta|2-tx)Qn(64<nx)_a(r(uz(x),i(nr,r2[i]=i_(xi,a)))))
G(I3,Qz(!i--)ax?_a(i?ti(i_(x,a)):_j(x,a)):ma|mx?S(ma,a,x):(i?I_:_I)(a,P0(x)))G(Z3,QZ)//&|<>=AAA@?#A^[gief...] [+-*%~_.!]f 
g(ny,RV(tx,i,ix-z2))_U(G1,P(!i--,M(n,ny(n*n,te(1))))QZ,ii,in)g(g1,in=iz(x);n>>31?pi(-n):9>i?G1(i-4,n):RV(AT>i?2:3,n,$5(i-11,I|j<<4,ze,(e6)(127<<23|(i6)CD()>>14<<5)-1,ze,C(e6,I|j<<4)/(e2)n)))
G(N3,P(1<i,M(ia,x))Qr(!aa)in=iz(a);P(ax,(i?ry:ny)(n,x))P(i^n>>31,Qz(!tx|mx)n+=!i*ux;_x(ln(n,nx-n,x)))n+=!!i*ux;x=tx?mx?M(n,nt(n*vx,x)):nt(n,x):_R(0,n,i(n,_i(i%nx,x))))
F(CC,P(!a,ax?v(x):!tx|mx?R(0,1,*rU=x):M(1,x))Qz(ta-tx|mx||ma&&va-nx)a=aa?v(a):a;x=ax?v(x):x;R1(x);x=_x(r(nz(na+nx,a),m9(Nx,sr+Na,sx)));ma?M(ma+1,x):x)
f(rr,Qz(mx)VX=sx+Nx;RX(VR=sr;J(Nx,R_=2>tx?a0(*--X,63-I0):q(*--X,15-I))))g(v1,AT==i?_x(_j(0,x)):CN==i?_x(ti(ux)):$6(i-4,ff,rr,aq,bq,fq,CN>i?uq:sq)(x))
G(er,RU(k(i+1,a,_j(j,x))))G(R6,Qr(ax)P(a,S(0,a,x))Qz(mx)o3(i,x))G(O3,P(ta,Z3(i,a,x))Qr(ax)P(10>i,(tx?10:4)<a?er(a-1,0,x):pe(a,x))P(18==a,M(0,x))Qz(--a&&1<a-4|mx)(1&i?s3:o3)(a?a-4:2,x))
G_(k,17>--i&&1<i-9?(a?9>i:4>i|9==i|15==i)?(tx?4>i?A:B:er)(i,a,x):a?14>i?(aa?d3:I3)(i-11,a,x):N3(i-14,a,x):(ax?g1:v1)(i,x):19>i?$3(i-17,CC,qq,Dt)(a,x):(25>i?R6:28>i?e3:O3)(i-19,a,x))
g_(k_,x?$3(i,_r(x),r_(x),(U)sx):o?ti(W):(o=1,om()))
