#define v(z) _x(r(T(0,0,nx),j(nx,*(U*)R=_(z);R+=8)))
#define V(n,z) R=x(r,UX);j(n6(n),*(V*)R=_(z);R+=64)
#include"a.h"//__*%ll B02 ZU s9();O2(m,M,i,I)O2(s,S,i,I)O2(s,S,e,E)Zg(of,mi,si,s9)
#define aa x(a,ax)
ZU R,A,X;G(M6,Ur=a;X=UX;V(i,Ix)r)F(Z,R(3>a?a?4:3:ta,ix,ee=1./ix;V(Nr,$4(a,I2|j<<4,e*C(e6,I2|j<<4),(e6)(127<<23|(i6)PQ()>>9)-1,$4(za,ga-z0,z0,ia-z2,ja-z3)))))
g(a_,mx?M6(lx<<zx,T(tx,0,lx),UX+(lx*i<<zx)):iv(i,x))f(_v,_x(a_(0,x)))
U(e1,v(A(a_(j,x))),Uf A,Ux)
g(e9,$6(i,X(C(s6,Ex))-(1L<<60),(1L<<60)+X(C(e6,(s6)Ix)),0,X(sq(Ex)),X(l_(Ex)),X(_l(Ex))))g(t_,Qz(4!=i|3!=tx)e9(1,x))
G(av,X($3(i,ia+Ix,ia-Ix,ia*Ix)))g(pe,Qz(2<i)A=UX-(1<<lx);X($3(i,Ix+Ia,Ix-Ia,Ix*Ia)))
g(v0,X($3(i,1+Ix,-Ix,i6 a=Ix;a*a)))
_f(f0,5>tx?ti(-ix):te(-ex))_f(f1,te(1./(5>tx?ix:ex)))
G(A9,it=m(3>i?3:4>i?4:0,m(ta,tx));ax?3<t|3==i?_v(A9(i,a,v_(x))):ti($3(i,ia+ix,ia-ix,ia*ix)):av(i,t>ta&7>3?te(ia):a,t>tx?t_(t,x):x)) //!ma^!mx?MM:VV
G(md,P(!i|3<m(ta,tx),av(2,i?f1(a):a,x))im=ia;P(tx,ti(++i?ix/m:ix%m))Qz(m-1>>16)in=(m+65535)/m;i?X(n*Ix>>16):X(i6 a=Ix;a-m*(n*a>>16)))
g(a9,3<tx|3==i|9<i?_v(v0(i,v_(x))):ax?3>i?ti($3(i,1+ix,-ix,ix*ix)):tb(!ix):3>i?v0(i,x):10>i?QZ:e9(0,x))
f(n_,Z(0,x))f(o_,tx?Z(1,x):QZ)f(_o,tx?4>tx?Z(2,x):te(ex/0x1p64*PQ()[0]):QZ)G(NN,Qz(!ax)Z(x,a))
G(AA,QZ)//P(ta,(7>ta?md:nn)(i,a,x))tx?i?ti(_a(x,a)):a_(x,a):!i&&(ma|mx|4==tx)?_x(Qz(2!=zx)Qn(!qm(a,Z6(x)))(ma?mx?mm:mv:mx?vm:vv)(a,x)):(i?_A:A_)(a,x))
G(C3,QZ)//S_ F(C_,P(ax,sv(2,te(ix),gf(1,a)))Qz(mx)uz(a,cz(x)))F(_C,a=ta?v(a):tx?a:kv(a);x=tx?v(x):ta?x:kv(x);Qz(ta!=tx)CC(x,a))
f(_n,Qr(ax)_x(ti(mn)))
G(f9,QZ)//Qz(a|2!=zx|2<i)_x(o3(i,x)))
F(E9,ax?_v(E9(a,v_(x))):av(2,te(l_((4>ta?ia:ea)-ze)[0]),e9(5,x)))
g(ie,QZ)
G(io,QZ)G(po,QZ) //Qz(i)P(18==a,P(tx,mx?mz(0,cz(x)):x)_x(_V(x)))P(3==a,Qz(4!=tx)ti(_x(pi(x))))Qd(1!=a&1<a-5)_x((1==tx?ob:o3)(l(2,a-5),x)))
Zf(f,n_,_v,_o,_n,0,o_,v_,0)
g_(k,Qr(!tx)5>i|10==i|16==i?a9(i-1,x):12>i?QZ:20>i?f[i-12](x):f9(i-1,0,x))
G_(K,Qr(!aa|!tx)P(29>i,28>i?(12>i?A9:15>i?AA:17>i?NN:20>i?C3:f9)(i-1,a,x):E9(a,x))Qr(!vx)30>i?8>a-12?e1(f[a-12],x):(pa?pe:ie)(ia,x):(pa?po:io)(1&i,a,x))

