#include"v.b"//reduce(MS) mv vm mm atomic(+-* <>=) uniform(+|\QR)
#define b4(g,a,b,Y...) e2(g,Se(r(ze,I=n4(I);Ez[4]={};i(I/4,i(4,zi+=a*R++))i(I%4,r+=b Ri)i(4,r+=zi)))[15],Y)
b4(se,,,IR)b4(vv,*X++*,Xi*,RX)i2(s2,i(n4(I),Ub=b2(n==(i6)Ri);P(b,16*i|iu(b)))I,in,IR)
V(mv,i(I,((e2*)R)[i]=vv(J,A+J*i,X)),aX)V(vm,J/=16;j(J/4,Ez[4]={};i(I,j(4,zj+=Ai*Xj)X+=J)j(4,*R++=zj)X-=I*J-4)i(J%4,Ri=r(ze,i(I,r+=Ai*X[J*i])++X)),aX)
V(mm,i(3+I>>2,j(J,Ez[4]={};h(H,l(4,zl+=A[H*(4*i+l)+h]*X[J*h+j]))l(4,t?R[J*(4*i+l)+j]+=zl:(R[J*(4*i+l)+j]=zl)))),it,iH,aX)
V(MM,J/=16;$(H*J-1>>12,i(I*J,Ri=z0)h(H/64,j(J/4,mm(1,64,I,4,A+H*64+h,R+J*4+j,X+J*H*(64+h)+j))))mm(0,H,I,J,R,A,X),iH,aX)
#define mM(n,i) ik=1<<i;h(1<<6-n-1-i,j(k,ii=2*h*k+j;zi=l##n(zi,r(zk,zk=m##n(zi,r)))))
V(t3,i(I>>6,j(J>>6,Ez[1<<6];h(1<<6,zh=Xh)i(6,mM(0,i))h(1<<6,Rh=zh))),iJ,RX)V(t5,i(I>>4,j(J>>4,Ez[1<<4];h(1<<4,zh=Xh)i(4,mM(2,i))h(1<<4,Rh=zh))),iJ,RX)
#define ft(m,M,o,O,t,T) T##f(O##t,i(M,x=O##T(x,S##m(i,x)))x)i2(o##t,O##t(r(z##m,i(b(M)+I>>M,r=O##T(r,Ri))))[b(M)],IR)V(o##T,T##z=z0;i(b(M)+I>>M,Ri=z=O##T(z[b(M)]-z##m,O##t(Xi))),RX)
ft(0,6,s,S,g,G)ft(0,6,m,M,g,G)ft(2,4,m,M,i,I)ft(2,4,s,S,i,I)e2(me,ii=mi(I,R);*(e2*)&i,IR)i2(sb,r(z2,i(n9(I),r+=O(vpopcntd_)(Ri)))[15],IR)
V(n0,i(n6(I),Ri=I0|(i0)(64*i)),IR)V(gz,i(n6(I),Ri=n-z2),in,IR)V(d0,i(n6(I),Ri=Xi),RX)V(r3,i(n6(I),Ri=R0(*--X)),RX)V(BV,i(n9(I),Ri=$3(j,AI&XI,AI|XI,~XI)),ij,AR)
#define V2(g,z,x...) V(g,i(n4(I),Ri=z),x)
V2(r5,R2(*--X),RX)V2(gb,GB(((U*)X)[i]),RX)V2(gi,GI(X8),RX)V2(ig,IG(X4),RX)V2(ei,EI(Xi),RX)V2(ie,IE(Xi),RX)V2(eZ,E(Xi),RX)V2(q_,Xi*Xi,RX)V2(_q,q(Xi),RX)
V2(jj,JJ(),IR)V2(iV,$4(j,n+XI,n-XI,n*XI,d(n,Xi)),ij,in,RX)V2(eV,$4(j,e+Xi,e-Xi,e*Xi,e/Xi),ij,ee,RX)V2(IV,$3(j,AI+Xi,AI-Xi,AI*Xi),ij,AR)V2(EV,$4(j,Ai+Xi,Ai-Xi,Ai*Xi,Ai/Xi),ij,AR)
V2(n2,I2|16*i,IR)V2(a5,G2(A,Xi),AR)V(a3,i(n4(I),R4=c(G0(A,Xi),g4)),AR)//V(RZ,ee=1/q(vv(I,X,X)/I-ze)[0];i(n4(I),Ri=e*Ai*Xi),AR)V2(EZ,Ai*Xi/(1+E(-Xi)),ij,AR)
V(sZ,ee=me(I,X);i(n4(I),Ri=E(Xi-e))e=1/se(I,R);i(n4(I),Ri*=e),RX)

