#include"a.h"//el  :+-*%&|<>=~ $,.! @? #_^ bcieE [!^?][-]n [[-]n][!@?#_^] (fFgGrRxX)(NPQW) AtCatType B D HIJKLM O S UV XYZ rrotnnnn //+-*%el[xyz]
Zu AA(),z();e sqrtf(e),expf(e),logf(e),log2f(e),exp2f(e);Ze(*e5[])(e)={sqrtf,expf,logf,log2f,exp2f};ZE(*E5[])(E)={csqrtf,cexpf,clogf};//madhava(neper euler cotes)
void*malloc(),free();u(T_,ii=n<<lt[t];W+=i;r((u)malloc(8+8*n3(i)+7)+8,r8=t<<24|(u)n<<32),it,in)f(_T,W-=Nx;free(sx-8);0)f(_r,pax?x:(1<<24)-1&xr?(--xr,0):_(if(!tx)N(_r(xu))_T(x)))
s(_s,ns(sl(s),s))g(nz,ua=5>ax?(_u)x:x;if(3>ax)(a|=a<<8,a|=a<<16);if(5>ax)a|=a<<32;R(ax,f,i(n3(Nr),ru=a)))f(c,R(ax,1,*(u*)r=x))u(_c,dn(T_(tx,n),n<<lx,x+((int)i<<lx)),ii,in,ux)
f(ind,_x(R(3,s_(x),_u*s=(_u*)sr;N(*s=i;s+=xc))))F(C,_a(_x(R(tx,nx+na,dn(dn(r,Nx,x)+Nx,Na,a)))))F(_C,x=ind(x);Tu(_c(xi,xi_-xi-1,a)))F(k2,R(0,2,i(2,ru=!i?a:x)))g(o,r(c(x),or=f))
g(cC,in=nx;N(n+=nu)_x(R(2,n,ua=r;N(a=dn(a,nu,xu)+nu;*sa=f;++a))))f(Cc,ua=T0(1,i?x_==_xc:1);_x(_C(x,a)))g(oc,x=cC(f,x);--nx;x)g(sc,++nx;x_=f;r(Cc(x),--nx))u(iot,R(3,N&n?-n:n,i(nr,ri=N&n?-n-1-i:i)),in)
g(a_,ii=f;tx?c5(tx-1,tb(xc),tc(xc),ti(xi),te(xe),tE(xE)):r_(xu))u(e1,Tu(b(a_(i,x))),_ b,ux)f(fst,_x(a_(0,x)))f(lst,_x(a_(nx?nx-1:0,x)))S(c,*--t=c;t)S(s,*s?$c(*s,$s(s+1,t)):t)f(cnt,_x(ti(nx)))
S(i,P(N&i,$c(45,$i(-i,t)))do*--t=48+i%10;W(i/=10);t)Ze _e=1+1e-6,e_[]={1.4142136,2.7182818,3.1415927,1/0.};Zs F[]={"%2","e","\xcf\x80","inf"};Zi iq(ee)__(ii=_e*e;P(eq(i),-i)i(4,P(eq(e_[i]),i))4)
S(e,P(1>e,0>e?$c(45,$e(-e,t)):_e-1>e?$c(48,t):$c(39,$e(1/e,t)))ii=iq(e);N&i?$i(-i,t):4>i?$s(F[i],t):1e7>e?r($i(.5+1e4*e,t)-1,i(i=t-r-5,rc=r[i+1])r[i]=46):$s(1e39>e?"1e?":"nan",t))
f($,P(!ax,lx?e1($,x):1==tx?Tc(48+xc):x)b64 ss=b+63;*s=0;_s(c3(ax-4,$e(ex,s),$e(ex,$c(58,$e(fx,s))),$i(ix,s))))f(kv,Tu(a_(i,x)))F(Cat,a=aa?c(a):a;x=ax?c(x):x;ta==tx?C(x,a):C(kv(x),kv(a)))
F(A_,_x(c4(la,T0(ta,sa[xi]),0,T2(ta,((_u*)a)[xi]),T3(ta,((u*)a)[xi]))))f(rev,A_(x,iot(-nx)))g(ord,QZ)
g(t,4>f?ti(ix):te((int)ix))g(T,4>f?Ti(xc):Te((int)xi))u(uu,ua=*_;ax>aa?(*_=t(ax,a),x):t(aa,x),u*_,ux)u(uU,ua=*_;tx>i?(*_=aa?t(ax,a):T(ax,a),x):T(i,x),ii,u*_,ux)
g(b,P((3==f||5==f)&&ti(-1)==x,tE(3==f?I:I*e_[2]))ii=3>f?3:4;ax?(x=i>ax?t(i,x):x,c3(ax-3,ti(c3(f,N&ix?-ix:ix,-ix,ix*ix)),te(c4(f,N&ix?-ex:ex,-ex,ex*ex,e5[f-3](ex))),tE(c4(f,cabsf(Ex),-Ex,Ex*Ex,E5[f-3](Ex))))):
tx?(x=i>tx?T(i,x):x,c3(tx-3,Ti(c3(f,N&xi?-xi:xi,-xi,xi*xi)),Te(c4(f,N&ix?-xe:xe,-xe,xe*xe,e5[f-3](xe))),TE(c4(f,cabsf(xE),-xE,xE*xE,E5[f-3](xE))))):Tu(b(f,a_(i,x))))
G(A,ii=3>f?3:4>f?4:0;P(ax,aa?(x=i>ax?t(i,x):x,x=aa!=ax?uu(&a,x):x,c5(f,ao(+),ao(-),ao(*),ao(/),tb(c5(f-4,ia&ix,ia|ix,bo(<),bo(>),bo(==))))):A(f/2*2+(2>f-5),1==f?b(1,x):3==f?te(1/ex):x,a))
ij=a?aa?:ta:tx;j&&tx?_a(x=i>tx?T(i,x):x;x=j!=tx?uU(i,&a,x):x;c5(f,Ao(+),Ao(-),Ao(*),Ao(/),c6(f-4,Tb(ac&xc),Tb(ac|xc),Bo(<),Bo(>),Bo(==),Bo(!=)))):Tu(A(f,aa?a:a_(i,a),a_(i,x))))
g(p9,u w=!!f**(u*)x;x=r(f?A(f-1,0,x):_x(_c(-1,nx,x)),ii=0;C4(lr,rc=10==f,,ri=w,ru=w)))g(s5,P(!f,x)P(10==f,Qt(1!=tx)ij=0;Tb(j^=xc))Qt(3!=tx)Qz(5==f)in=0;f?Ti(n+=xi):Ti(n=m(n,xi)))
g(o5,Q(x=s5(f,x))lst(x))f(not,P(ax,tb(!ix))Qr(1!=tx)Tb(!xc))f(dot,P(ax,tE(4>ax?ix:ex))Qr(!tx)TE(4>ax?xi:xe))f(flr,Qt(4!=(ax?:tx))ax?ti(ex):Ti(xe))F(Not,QZ)F(Dot,QZ)F(Cst,QZ)
//   |!~#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~  :,$~._+-*% @#&|!^?<>=
f(q,"fnjqkdet^^calbmu__________`^gihpo__________________________^v^sr"[x-32-32*(x>96)-60*(x>122)]&31)Zs R=":+-*%&|<>=~$,.!@?#_^",*r="`fghilmqrscbadnjpkeo";
g(j,f=31&r[f];10>f?c4(f,x,c(x),$(x),c4(f-3,not(x),dot(x),flr(x),b(f-6,x))):ax?_(Qr(14!=f)iot(ix)):c6(f-10,fst(x),cnt(x),QZ,rev(x),ind(x),ord(f-15,x)))
G(J,10>f?A(f-1,a,x):14>f?c4(f-10,Not,Cst,Cat,Dot)(a,x):17>f?_a(AA(f-15,a,x)):_x(Qr(!aa)ax?nz(a,x):c3(f-17,_c(0,a,x),_c(a,nx-a,x),QZ)))
F(_o,ii=oa;a=x(a,xx);P(1==i,sa[na]=0;z(&x,sa))i-=6;Qr(ax)P(2==aa,c3(i,QZ,Qr(tx)oc(a,x),Qr(!tx)sc(a,x)))Qr(!tx)Qd(10<a||i&&1<a/5)c3(i,p9,o5,s5)(a,x))
//a@ a? a'('0a) ?[x;~'b;f]) cfFf(tf,is(x,"'0a"))G(cf,c3(f,a,!a*n(x),!a*a(x)))g(class,ij=10;Tb(cf(f,j^=34==xc,xc)))g(code,QZ)g(data,ij=0;R(2,nx,ss=sr;N(s+=cf(f,j,*s=xc))nr=s-sr))
//k2(code(a,x),data(a,x)) //P(ca,ii=i(a, P(aa, A(2,e,1/e)
G(prs,QZ)
G(AA,P(aa,ii=is(a,"el");2==aa?i?b(2+2*i+f,x):prs(f,a,x):A(2,f?te(1/(4>aa?ia:ea)):a,x))Qz(f)P(pa,j(a,x))P(oa,_o(a,x))P(ax,Qd(ix>=na)a_(ix,a))Qt(3!=tx)A_(a,x))
long read(),write();int open(),close(),stat();G(_w,read(f,sa,x))G(w_,write(f,sa,x))F(f_,open(sa,x))f(_f,close(x))F(nf,stat(sa,sx))
s(_1,ij[36];in=!nf((u)s,(u)j)&&1&j[O?1:6]>>15?j[O?24:12]:0;Qs(!n,s)R(2,n,ii=f_((u)s,0);_w(i,r,n);_f(i)))s(_0,X(_1(s),Qd(10!=x_)Cc(x)))f(av,1==nx?fst(x):x)
f(_z,px?ns(1,&R[x]):ax||!lx?$(x):tx?cC(32,e1($,x)):_s(".."))f(w,127>x?w_(2,(u)&x,1):w_(2,x,sl(sx)))f(wx,x=cC(10,pax||tx?c(_z(x)):e1(_z,x));_x(w_(2,x,nx)))
Zu ys(),G[26];u(v,a(x)?r_(_&&3>x-120?_[x%4]:G[x-97]):x,u*_,ux)u(_v,_=_&&3>a-120?_+a%4:G+a-97;_r(*_);*_=x,u*_,ua,ux)s(_n,ii=s[-1];n(s[45==*s&&(!i||32==i||q(i))]))
s(nc,P(34==*s,is(34,s+1)+1)ii=1;W(32==si?_n(++i+s):si&&n(s[i+(46==si||58==si)]))++i;i)
u(uc,P(34==*s,ns(n-2,s+1))ij=1;i(n,j+=32==si)it=n>ins(58,n,s)?2:n>ins(46,n,s);R(t+3,j,i(j,j=ins(32,n,s);C3(t,ri=i$(j,s),re=e$(j,s),rE=E$(j,s))s+=++j;n-=j)),in,ss)
u(z,ii=34==*s||_n(s);in=i?nc(s):1;ua=i?av(uc(n,s)):a(*s)?*s:q(*s);s+=n;i=is(*s,"'/\\");a=i?(++s,o(6+i-1,v(_,a))):a;P(!*s,v(_,a))
n=pa||a>>7&&!aa&&oa;i=q(*s);X(z(_,s+!n*(31>i)),n?pa?j(a,x):_o(a,x):i?J(31>i?i:15,v(_,a),x):(_v(_,a,x),s[-2]?r_(x):0)),u*_,ss)
s(qs,ij=1;st=s-1;W(*++t)if(j^=34==*t)P(30==q(*t),err(0,(u)t))0)s(zs,92==*s?ys(s+1):qs(s)?0:z(0,s))s(ws,a(*s)&&32==s[1]?G[*s-97]=o(1,_s(s+2)):X(zs(s),x?wx(x):0))
s(ls,X(_0(s),N(P(!nu,_x(0))if(su[nu]=0,39!=*su)Q(ws(su)))_x(0)))s(ts,ii=is(32,s);s[i-1]=0;in=i>1?z(0,s+1):1;s+=i;ua=ut();i(n,ua=zs(s);Q(a)_r(a))ti((ut()-a)/et-n/2e5))
Zs M="+-*% &and  |or   <    >     =      ,~$. !index @ ?find #take  _drop  ^cut\n+-*% &flip |flop <asc >desc =group ,~$. !index @ ?nub  #count _floor ^order";
s(ys,c4(is(*s,"ltw"),_s(M),ls(s+2),ts(s+1),ti(W)))int main(int n,char**_){ftz();*++_?ls(*_):w((u)"k/fun (c)atw "__DATE__"\n");b64 W(1)w(32),b[_w(0,(u)b,64)-1]=0,*b?ws(b):0;}

