#include"b.c"//+-*%&|<>=~.!@?#_^,  ie+* bgi|@?, //&|<>= .!@?# ^
_Z(m6,i(n/4,Ez[4]={};EX=x;h(m,i(4,zi+=A[h]*X[i])X+=n)i(4,R_=zi)x+=4)i(n%4,Ez={};EX=x++;h(m,z+=A[h]**X;X+=n)R_=z),im,in,ER,eA,e6*x)F(mm,ik=kx;M(ma,k,i(ma,m6(mx,n4(k),r2+k*i,a2+mx*i,x2))))
_F(S,Qn(ma!=mx|na!=nx)_a(_x(R(tx,kx,VR=sr;in=nr/16;i(n/4,Ez[4]={};EA=aE+4*i;EX=xE+4*i;i(mx,i(4,zi+=AZ*X_)A+=n-4;X+=n-4)i(4,R_=zi))))))F(vm,ik=kx;R(tx,k,m6(mx,n4(k),r2,a2,x2)))f(ff,0)
G(VV,Qn(ka!=mn)Q(i&2!=i)it=ma;if(t){Uu=a;a=x;x=u;}ik=kx;_a(_x(M(mx,k,h(mx,VR=r2+h*k;VX=x2+h*k;$(t,EA=a2;$(i,J(4*k,R_=AZ*Ex))J(4*k,R_=AZ+Ex))$(i,J(4*k,R_=ae[h]*Ex))J(4*k,R_=ae[h]+Ex))))))
F(mv,R(tx,ma,eR=sr;i(ma,R_=sE(a2+i*nx,x))))F(at,Qn(ka!=mn)_a(_x(ma|mx?(ma?mx?mm:mv:vm)(a,x):te(sE(sa,x)))))
_g(T,i==tx?x:ax?4>i?t(i,ix):te(ex):t_(--i>tx?T(i,x):x))f(H,4>tx?T(4,x):x)
G(R6,Qr(ax)P(!a&3>i,o3(i,x))P(a,Q(aa)(ma&&mx?S:at)(H(a),P0(x)))_x(te(4>i?se(nx,sx)/nx:_q(sE(sx,x)/nx-ze)[0])))
G(E3,ax?_v(E3(i,a,v(x))):$4(i-6,V(_l((a?l_(ea-ze)[0]:E)*Ex)),V(L*l_(Ex)),a?(a=H(a),_a(V(aE[j]/1+_l(-E*Ex)))):_(ee=1/r(ze,ee=ei(mi(nx,sx));EX=sx;J(Nx,r+=L*_l(Ex-e)))[0];V(e*Ex)),V(_q(Ex))))
//g(iZ,x) //a&&aa&&2==i?iZ(a,x): _x(r(mtn(mx,tx,nx/i),))) eR=sr;eX=sx;h(mx,i(i,R_=2.3))))) //se(kx/i,X))X+=kx/i)))) //DEZ 48\ZS''6^'
#define A(G,I,E) 4>i?V(4>tx?$3(i,I+Ix,I-Ix,(I)*Ix):$4(i,E+Ex,E-Ex,(E)*Ex,(E)/Ex)):6>i?V(3>tx?(5>i?LG:MG)(G,X_):(5>i?LI:MI)(I,X_)):3>tx?BG($3(i-6,G<X_,G>X_,G==X_)):BI($3(i-6,I<X_,I>X_,I==X_))
G(sv,A(ga-z0,ia-z2,ea-ze))_U(Av,A(AZ,(i6)AZ,(e6)AZ),ii,VA,Ux)g(pe,P(1==tx,pB(i,x))Ua=i?*xU:0;Uc=b(1<<bx);x=i--?Av(i^2>i-6,sx-(1<<bx-3),x):_x(ln(-1,nx,x));*xU=c&a|~c&*xU;x)
G(s9,ij=ia;4>i&3<tx?_v(sv(i,a,v(x))):6>i?t(tx,$6(i,j+ix,j-ix,j*ix,0,l(j,ix),m(j,ix))):tb($3(i-6,j<ix,j>ix,j==ix)))f(y,4>tx?ti(-ix):te(-ex))g(tt,m(3>i?3:4>i?4:0,tx))
G(vv,_a(Av(i,sa,x)))
G(Z,P(!tx,K(Z(i,a,u)))a=T(m(ta,tt(i,x)),a);x=T(ta,x);aa<ax?sv(i-(1==i|3==i)^2>i-6,1==i?y(x):3==i?te(1/ex):x,a):(aa?ax?s9:sv:!ma^!mx?VV:vv)(i,a,x))
g(z,P(!i,ty(x))P(!tx,K(z(i,u)))P(ax,_v(z(i,v(x))))x=T(tt(i,x),x);$5(i,0,sv(1,0,x),Av(2,sx,x),E3(3,0,x),10>i?sv(8,0,x):_t(x)))
G(MD,P(!i--|3<m(ta,tx),Z(2,i?a:te(1/ea),x))in=a;P(ax,ti(i?ix%n:ix/n))Q(n-1>>16)im=(n+65535)/n;i?V(i6 a=Ix;a-n*(m*a>>16)):V(m*Ix>>16))
G(DM,Qr(!aa)x)
F(A_,iX=sx;ma?M(nx,ka,ik=ka<<ba-3;i(nx,ds(k,sr+k*i,sa+k*X_))):5==ba?r(uz(x),i(nx,r2[i]=a2[X_])):_x(R(ta,nx,$(ta,i(nx,sr[i]=sa[X_]))i(nx,rU[i]=r_(aU[X_])))))
F(i_,Q(2>tx)Uu;VX=sx;J(Nx,$3(l(1,tx-2),P(u=bg(ga==X_),l(nx,64*j|iu(u))),P(u=bi(ia==Ix),l(nx,16*j|iu(u))),P(u=bg(ia<Ix),l(nx,16*j|iu(u))));++X)nx)
F(_A,Q(ma|100<nx|5!=bx)Qt(ta!=tx)r(uz(x),iR=sr;iX=sx;j(nx,R_=i_(X_,a))))G(AA,it=i?ta:3;aa?MD(i,a,x):4==tx&!ax?at(a,x):_a(ax?i?ti(i_(x,a)):a_(x,a):(i?_A:A_)(a,t>tx?T(t,x):x)))
G(NN,Q(!aa)in=a;P(ax,nz(n,x))im=mn;n>>31^i?(n+=!i*m,_x(ln(n,m-n,x))):n>m?nl(n,x):x-(i?-n:m-n))F(C_,Q(!aa|ax|mx|!tx)mz(ia>>31?nx/-ia:ia,x))
g(us,Q(!ax)Qr(11!=i&13!=i&16!=i)nz(x,i-11>>1))
_g(e1,K(k(i,0,u)))f(n_,ax?nz(x,0):!tx|mx?e1(12,x):_x(mz(2>nx?0:*x2,nz(pi(x),te(1)))))g(vn,Qr(ax)$3(i-4,ff,rr,14>i?_v:_n)(x))G(O3,Qr(ax)Q(!pa)$3(i-9,(mx|!tx?4:10)<a?e1:pe,po,ps)(a,x))
G_(k,
19>--i?a?16>i?$4(i-10>>1,DM,AA,NN,Z)(10>i?i:1&i,a,x):(17>i?C_:_C)(a,x):11==i?n_(x):17>i?$3(3&"00002211100021201"[i],z,us,vn)(i,x):v(x):(25>i?R6:28>i?E3:O3)(i-19,a,6>i-22?H(x):x))
