o=-Ofast -fno-builtin -funsigned-char -fno-unwind-tables -Wno-multichar -Wno-parentheses -Wno-incompatible-pointer-types -Wfatal-errors

a:?.[ch] makefile
	clang -oa [az].c $o -s -march=native #-nostdlib

