t:_5e8%n*#v:@m:!n,n:256
\tn?t mm
\tt mv
\tt vm
\tt mSm
t:_5e8%#i:!#v:^n:100000
\tt Sv
\tt ~v
\tt vv
\t2?t -v
\t3?t %v
\t6?t Ev
\t9?t Zv
\t9?t vi
v:,s:5
t:1000000
\tt 2*1+3*s++4
\tt 2*1+3*v++4

L12345(4 8 16 32 64) ns:?=^<>i(.1-4) code(5) sync(50) gpu(20000) ssd(100000)
L2(104/../300)L3(52/104/200)L4(26/52)

[jv]s'(join value split)
x !wi x_:i:@<xS'Zx:='w@\x  12972[2315]
\tt o*x
\tt n.x
\t5?t +\i
\t5?t ?i
\t5?t =i
\t10?t ^i
\t50?t ^e
x:1'`kj
\t23 ?x
\t23 =x
