#include"v.h"
U(nm,b(6-m)+n>>6-m,im,in)
#define ft(m,o,O,t,T) Gf(O##t,i(6-m,z=O##T(z,S##m(i,z)))z)U(o##t,((T)O##t(r(Z##m,i(nm(m,n),r=O##T(r,Zi)))))[b(6-m)],in,EZ)V(o##T,T##z=Z0;i(nm(m,n),Ri=z=O##T(z[b(6-m)]-Z##m,O##t(Zi))),U3)
ft(0,s,S,g,G)ft(0,m,M,g,G)ft(2,m,M,i,I)ft(2,s,S,i,I)U(s2,i(n4(n),Ub=b2(k==Zi);P(b,16*i|iu(b)))n,ik,in,IZ)V0(gw,k-Z2,ik,in,GR)V0(n0,N0|(g)(64*i),in,GR)V2(n2,N2|16*i,in,GR)V2(jj,JJ(),in,GR)
#define e4(g,Y,y,a...) e(g,Se(r(E0,n=n4(n);Ez[4]={};i(n/4,i(4,zi+=Y*Z++))i(n%4,r+=y Zi)i(4,r+=zi)))[15],a)
e4(vv,*Y++*,Yi*,in,EY,EZ)e4(se,,,in,EZ)e(me,ii=mi(n,Z);*(e*)&i,in,EZ)V2(eV,$4(j,e+Zi,e-Zi,e*Zi,e/Zi),ij,ee,in,ER,EZ)V2(EV,$4(j,Yi+Zi,Yi-Zi,Yi*Zi,Yi/Zi),ij,EY,in,ER,EZ)
V(sX,ee=me(n,Z);i(n4(n),Ri=E_((E)Zi-e))e=1/se(n,R);i(n4(n),Ri*=e),U3)V2(EX,Yi*Zi/(1+E_(-(E)Zi)),EY,U3)V(RX,ee=1/((E)_Q(vv(n,Z,Z)/n-E0))[0];i(n4(n),Ri=e*Yi*Zi),EY,U3)
V(mm,i(3+I>>2,j(J,Ez[4]={};h(H,kk(4,z[k]+=Y[H*(4*i+k)+h]*Z[J*h+j]))kk(4,t?R[J*(4*i+k)+j]+=z[k]:(R[J*(4*i+k)+j]=z[k])))),it,iH,IJ)
V(MM,J/=16;$(H*J-1>>12,i(I*J,Ri=Z0)h(H/64,j(J/4,mm(1,64,I,4,Y+H*64+h,R+J*4+j,Z+J*H*(64+h)+j))))mm(0,H,I,J,R,Y,Z),iH,IJ)
V(mv,i(I,((e*)R)[i]=vv(J,Y+J*i,Z)),IJ)V(vm,J/=16;j(J/4,Ez[4]={};i(I,j(4,zj+=Yi*Zj)Z+=J)j(4,*R++=zj)Z-=I*J-4)i(J%4,Ri=r(E0,i(I,r+=Yi*Z[J*i])++Z)),IJ)
#define mM(n,i) ik=1<<i;h(1<<6-n-1-i,j(k,ii=2*h*k+j;zi=l##n(zi,r(zk,zk=m##n(zi,r)))))
V(t0,i(I>>6,j(J>>6,Gz[1<<6];i(1<<6,zi=Zi)i(6,mM(0,i))i(1<<6,Ri=zi))),IJ)V(t2,i(I>>4,j(J>>4,Gz[1<<4];i(1<<4,zi=Zi)i(4,mM(2,i))i(1<<4,Ri=zi))),IJ)
#define bB(g,t,y,Y) V(g,i(n6(n),Ri=b0(3>j?$3(j,y<Zi,y>Zi,y==Zi):GI($3(j-3,Y<Z_,Y>Z_,Y==Z_)))),ij,t,in,U*R,GZ)
bB(cV,ik,(g)k,(int)k)bB(CV,GY,Yi,Y_)V2(gb,O(selectb_)(Zi,1|Z0,Z0),in,IR,U*Z)V(BV,i(n9(n),Ri=$3(j,Yi&Zi,Yi|Zi,~Zi)),ij,U4)V2(IV,$3(j,Yi+Zi,Yi-Zi,Yi*Zi),ij,U4)
V0(G1,1&$3(j,g<Zi,g>Zi,g==Zi),ij,gg,in,GR,GZ)V2(a0,c(A(Y,Zi,1),_G),GY,in,_G*R,IZ)V2(a2,A(Y,Zi,2),U4)V2(iV,$3(j,k+Zi,k-Zi,k*Zi),ij,ik,U3)V2(DM,z(k*Zi>>16,j?Zi-j*z:z),ij,ik,U3)
V0(r0,R0(*--Z),U3)V2(r2,R2(*--Z),U3)V2(q_,(E)Zi*Zi,U3)V2(_q,_Q(Zi),U3)V2(gi,GI(Z_),U3)V2(ig,IG(_Z),U3)V2(ei,EI(Zi),U3)V2(ie,IE(Zi),U3)V2(eX,E_(Zi),U3)
