a:a.[ch] makefile
	clang-13 -Os -oa a.c -mavx2 -mpclmul -mfma -ffreestanding -nostdlib -s -funsigned-char -ffast-math -fno-finite-math-only -fno-unwind-tables -Wno-incompatible-pointer-types -Wno-parentheses
