#include"v.b"//reduce(MS) mv vm mm atomic(+-* <>=) uniform(+|\QR)
#define b4(g,a,b,Y...) e2(g,Se(r(ze,I=n2(I);Ez[4]={};i(I/4,i(4,zi+=a*R++))i(I%4,r+=b Ri)i(4,r+=zi)))[15],Y)
b4(se,,,_R)b4(vv,*X++*,Xi*,RX)V(vm,e2*a=A;J/=16;i(J/4,Ez[4]={};i(I,j(4,zj+=ai*Xj)X+=J)j(4,*R++=zj)X-=I*J-4)i(J%4,Ri=r(ze,i(I,r+=ai*X[J*i])++X)),RAX)
V(mv,J/=16;er=R;i(I,ri=vv(J,A+J*i,X)),RAX)V(mm,e2*x=X;I/=16;i(I,j(J/6,Ez[6]={};h(H,l(6,zl+=A[I*h+i]*x[H*(6*j+l)+h]))l(6,R[I*(6*j+l)+i]=zl))),iH,RAX)
#define ft(m,o,O,t,T) T##f(O##t,i(6-m,x=O##T(x,S##m(i,x)))x)i2(o##t,O##t(r(z##m,i(n##m(I),r=O##T(r,Ri))))[b(6-m)],_R)V(o##T,T##z=z0;i(n##m(I),Ri=z=O##T(z[b(6-m)]-z##m,O##t(Xi))),RX)
ft(0,s,S,g,G)ft(0,m,M,g,G)ft(2,m,M,i,I)ft(2,s,S,i,I)e2(me,ii=mi(I,R);*(e2*)&i,_R)i2(s2,i(n2(I),Ub=b2(n==(i6)Ri);P(b,16*i|iu(b)))I,in,_R)V2(jj,JJ(),_R)V2(nn,I2|16*i,_R)V0(gz,n-z2,in,_R)
V0(BV,!j?Ai&Xg:Ai|Xg,ij,gA,RX)V0(d0,Xi,RX)V0(r0,R0(*--X),RX)V2(r2,R2(*--X),RX)V2(ig,IG(X4),RX)V2(ei,EI(Xi),RX)V2(ie,IE(Xi),RX)V2(eZ,E(Xi),RX)V2(q_,Xi*Xi,RX)V2(_q,q(Xi),RX)V2(dV,e*Xi,ee,RX)
V(RZ,ee=1/q(vv(I,X,X)/I-ze)[0];N2(e*Ai*Xi),EA,RX)V(sZ,ee=me(I,X);N2(E(Xi-e))e=1/se(I,R);N2(e*Ri),RX)V2(EZ,Ai*Xi/(1+E(-Xi)),EA,RX)Ig(d,Iz=(i1)i*x>>16;(i>>=16)?x-i*z:z)
#define V4(g,t,T,a,z) V2(g,$4(j,a+Xi,a-Xi,a*Xi,z),ij,t,_R,T##X)
V4(iV,in,I,n,d(n,Xi))V4(eV,ee,E,e,e/Xi)V4(IV,IA,I,Ai,G2(A,Xi))V4(EV,EA,E,Ai,Ai/Xi)V0(b3,1&$3(j,c<Xg,c>Xg,c==Xg),ij,cc,RX)V0(B3,1&GI($3(j,n<X8,n>X8,n==X8)),ij,in,RX)
#define M0(i) ik=1<<i;h(1<<5-i,j(k,ii=2*h*k+j;zi=_p(zi,r(zk,zk=p_(zi,r)))))
#define M2(i) ik=1<<i;h(1<<3-i,j(k,ii=2*h*k+j;zi=_P(zi,r(zk,zk=P_(zi,r)))))
V(f0,J/=64;i(I/=64,j(J,Ez[64];h(64,zh=Xh)i(6,M0(i))h(64,Rh=zh))),iI,iJ,IR,IX)
V(f2,J/=16;i(I/=16,j(J,Ez[16];h(16,zh=Xh)i(4,M2(i))h(16,Rh=zh))),iI,iJ,IR,IX) 
