a:?.[ch] makefile
	#clang -Ofast -oa [az].c -w -march=native -funsigned-char -fno-stack-protector -fno-unwind-tables -s
	clang-13 -Ofast -oa [az].c -w -march=tigerlake -funsigned-char -fno-stack-protector -fno-unwind-tables -s
