a:a.[ch] makefile
	clang-13 -oa a.c @o -lm

#	clang-13 @o -lm -mavx512f -mavx512vbmi -mavx512vbmi2 #-nostdlib
#	clang-13 -mavx2 -mfma
#	clang-13 -target arm64-apple-macos -fno-stack-protector -fuse-ld=lld

