#include"u.c"
#define ji(m,n,z) j(m,i(n,z))
#define xji (x+64*(j*mx+i))
#define rji (r+64*(j*mx+i))
VG(v2,o(vpermi2varps)(a,I2/2+I2%2*16+8*i,b))
f(c_,_x(R(4,2*nx+16,nr-=16;I4(nx,e6 a=x_(O);e6 b=sqrt(1-a*a);j(2,rV[2*i+j]=v2(j,a,b))))))
_G(f4,i6 _[16];j(16,_[i]=x6)ji(4,8,Va=xV[2*i];Vb=xV[2*i+1];_[2*i]=v2(0,a,b);_[2*i+1]=v2(1,a,b))j(16,a6=_[i])0)
_f(q4,2!=zx|15&mx|mx!=nx/mx)
_f(f9,Qz(q4(x))_x(R(4,256,ji(mx,mx>>4,f4(mx,rji,xji)))))
_U(m9,Qz(q4(a))__(ux()),Ux,Ua)
F(qv,Qt(2!=zx|Ta!=Tx)Qn((ma?na/ma:na)!=mn)x)
G(mv,ik=i-1;Q(qv(a,x))_x(__(r(uz(a),)))) //in=nx;i(ma,I4(n,r6=k?aE*O:aE+O)r+=4*n;a+=4*n)))
G(vm,ik=i-1;Q(qv(a,x))__(x)) //ux())) //in=nx/mx;i(na,e2 e=eu(a2);I4(n,r6=k?e*xE:e+xE)r+=4*n;x+=4*n)))
F(mm,Q(qv(a,x))P(mx,m9(a,x))Z6(x);_x(ma?R(4,ma,i(nr,r2=EE(nx,a+4L*i*nx,x))):t(4,EE(na,a,x))))
g(o3,P(mx,ik=i;R(Tx,nx/mx,j(mx,I6(Nr,r6=j?$3(k,LI(r6,O),MI(r6,O),(4>Tr?SI:SE)(r6,O)):O)x+=Nr)))x=Z6(x);t(Tx,of[iy(i,x)](nx,x)))
g(o1,ik=i;P(Tx,Qz(!mx)in=nx/mx;R(Tx,mx,i(nr,r2=$3(k,li,mi,4>Tx?si:se)(n,x+(i*n<<zx)))))R0(o3(k,x3)))
_g(inv,tx?3>i?4>tx?ti(-ix):te(-ex):te(1/(4>tx?ix:ex)):3>i?4>tx?X(-xI):X(-xE):X(1/xE))
G(aa,4>i?4>tx?ti($3(i-1,ia+ix,ia-ix,ia*ix)):te($3(i-1,ea+ex,ea-ex,ea*ex)):5>i?te(ea/ex):7>i?a>jx^1&i?a:x:tb($3(i-7,ja<jx,ja>jx,ja==jx)))_g(tt,4>i?ti(ix):te(ix))
#define B3(v,m,a) $3(i-7,RD(1,m,b##m(v?6:1,a,O)),RD(1,m,b##m(v?1:6,a,O)),RD(1,m,b##m(0,a,O))) //-%,(sub div app)
G(av,4>i?4>Tx?$3(i-1,X(ai+xI),X(ai-xI),X(ai*xI)):$3(i-1,X(ae+xE),X(xE-aE),X(ae*xE)):5>i?X(ea/xE):7>i?$4(zx+i-5,X(LG(ag,O)),X(MG(ag,O)),X(LI(ai,O)),X(MI(ai,O))):$3(zx-!!zx,B3(0,3,ag),B3(0,1,ai),B3(0,0,aj)))
G(vv,4>i?4>Tx?$3(i-1,X(aI+xI),X(xI-aI),X(aI*xI)):$3(i-1,X(aE+xE),X(xE-aE),X(aE*xE)):5>i?X(xE/aE):7>i?$4(zx+i-5,X(LG(aG,O)),X(MG(aG,O)),X(LI(aI,O)),X(MI(aI,O))):$3(zx-!!zx,B3(1,3,aG),B3(1,1,aI),B3(1,0,aJ)))
#define Q0(z) vk(_x(R(0,nx,i(nx,Q(r3=z)))))
G(A,ij=ta?:Ta;ik=tx?:Tx;P(!j|!k,ij=i;__(Q0(A(j,ta?a:a_(i,a),tx?x:a_(i,x)))))it=m(4>i?3:5>i?4:0,m(j,k));a=t>j?(ta?tt:t_)(t,a):a;x=t>k?(tx?tt:t_)(t,x):x;
P(ta,(tx?aa:av)(i,a,x))x=(2==i|4==i)&&(tx||!ma&&mx)?inv(--i,x):x;tx?av(i,x,a):!ma^!mx?(ma?mv:vm)(i,a,x):_x(vv(i,x,a)))
G(md,P(!i|3<m(ta,tx?:Tx),A(3,i?inv(3,a):a,x))--i;Qz(ia-1>>16)P(tx,ti(i?ix%ia:ix/ia))in=(ia+65535)/ia;ij=i;X(i6 v=n*xI>>16;j?xI-ia*v:v))
_g(fv,P(Tx,_x(3>i?o3(i,x):A(3,te(1./mn),o3(2,x))))ij=2>i?5+i:1;Ua;N(a=i?vv(j,x,a):r_(x))_x(a))G(Fv,Qz(ta||!Tx)Qz(2!=i)mm(a,x))
f(_t,P(tx,_v(_t(v(x))))Qz(!Tx)$3(Tx-2,X(lL(O)),RD(2,4,C(g4,xI)),tz(3,X(C(s6,xE)))))
G(T_,m5(T(i,a),x,a<<l[8>i?i:0]))U(e1,R0(d(a_(i,x))),Uf d,Ux)U(el,R0(d(a_(i,x),r_(a))),UF d,Ux,Ua)g(nT,Qz(mx||i!=nx)cz(x))
#include"s.c"//bgie[Dd] :+-*%&|<>=~.!@?#_^,$ [rrit]n V! &V  [!?^[&|<>=@#]]n   LE ME 22>i?nt(A(8-i%2,a,x)): U o5(),t$(),$(),e9(),nn(),c_();
f(f1,xs[nx]=0;Ua=D7(x);Qs(!a,x)ii=d_(x,0);_x(R(2,a,_w(i,r,a);_d(i))))F(ie,Qd(1<ia)Qz(2!=Tx)Q(x=f1(x))ia?x:s_(x))G(io,Qz(2!=ta|62<ia-B)Qt(i?2!=Tx:Tx)i?_x(xs[nx++]=a;r(s_(x),--nx)):_s(a,x))
_F(_a,am(nx,a,x);Ub;$3(Tx-2,I6(Nx,P(b=b3(0,ag,xG),64*i+iu(b))),I6(Nx,P(b=b1(0,ai,xI),16*i+iu(b))),I6(Nx,P(b=b1(1,ai,xI),16*i+iu(b))));nx)
F(_A,Qt(3==Ta|Ta!=Tx)Qz(100<nx)_x(R(3,nx,i(nr,r2=_a($4(zx,x0,0,x2,x3),a)))))
F(A_,Qz(Ba)Z6(x=3>Tx?t_(3,x):x);Qn(mi(nx,x)>=na)Ta?$3(x(a,zx)-1,RD(2,4,C(g4,(i6)A0(a,O))),tz(Ta,X(A2(a,O))),RU(Ta,A3(a,x5))):R0(r_(aU[x2])))
G(AA,ta?(7>ta?md:nn)(i,a,x):tx?i?ti(_a(x,a)):a_(x,a):(ma|mx|4==Tx?mm:i?_A:A_)(a,x))f(rr,Qz(2!=zx)i2*a=xs+Nx;_x(R(Tx,nx,i(nr,r2=*--a))))

f(foo,_x(ti(tx?:Tx)))F(In,QZ)f(_n,_x(ti(mn)))f(dt,Qz(tx)Q(x=t4(x))c_(x))F(Md,md(2,a,x))
f(ff,Qr(!mx)f9(x))F(Nt,QZ)F(Dt,QZ)f(nt,Bx?X(~O):A(9,tg(0),x))
Zf(f,ff,rr,o_,_o,u_,nt,dt,n_,_v,un,_n,_t,on,v,$)_g(z,$6(i,vk(x),foo(x),inv(1,x),A(3,x,r_(x)),e9(0,x),Qr(tx&&1&0xff0a3e>>i-4)20>i?f[i-5](x):28>i?fv(i-20,x):e9(3,x)))
ZF(F,Nt,Dt,Md,0,0,N_,_N,C_,_C,S_)_G(Z,!i?AA(0,a,x):10>i?A(i,a,x):20>i?2>i-13?__(AA(i-13,a,x)):F[i-10](a,x):28>i?_(Qr(tx)27>i?Fv(i-20,a,x):In(a,x)):e9(a,x))
F(Pe,Qz(29!=Ta)a=*aU;Qz(2<a-20|Tx||!mxx)R0(o1(a-20,x3)))F(pe,Ub=a?*xU:0;11>a?Bx?_B(a,x):am(0,b,a?vv(a,x-(1<<zx),x):_x(ln(-1,nx,x))):20>a?e1(f[a-5],x):o1(a-20,x))
G(po,Qz(!pa)P(18==a,P(Tx,mx?mz(0,cz(x)):x)Qt(!qT(x))_x(_V(x)))P(3==a,ti(pi(x)))Qd(10!=a&1!=a&1<a-5)i?Bx?1==a?sG(nx,t_(2,x)):B_(a,x):(x=cz(x),sf[iy(a-5,x)](nx,x)):_x((Bx?ob:o3)(a-5,x)))
G_(k,B>i?x?8>i-8?t$(i%8,a,x):T_(i,a,x):T(i,a):64>i?z(i%B,a):93>i?Z(i%B,a,x):_(Qr(tx)94>i?__((ta?ie:pa?pe:Pe)(a,x)):(ta?io:po)(i-94,a,x)))
f_(k_,ZU _;P(_,x?_T(x):ti(a(1<<28,i(28,in=0;Ux=m[i];W(x)(++n,x=xx);a-=n<<i)a-1)))ox=(Uf)x;i(3,Va=PQ();P|=rn(i,a);a=PQ();Q|=rn(i,a))i(1e3,Va=PQ())M(m7(_=m[28]=M7(),1L<<35,14)))
