#include"b.c"//+-*%&|<>=~ .! @? #_ ^, $ [+-*%_~. &| @? #! <>=?^]  *m mm m6(l1/l2/l3)
_D(e2,vv,in=n4(nx);EX=sx;Ez[4]={};$(A,j(n/4,i(4,zi+=A_*X_)))j(n/4,i(4,zi+=X_))Eb=z[3];i(3,b+=zi)$(A,j(n%4,b+=A_*X_))j(n%4,b+=X_)sE(b)[15],EA,Ux)_D(e2,se,Z6(x);vv(0,x),Ux)
_Z(m6,j(n/4,Ez[4]={};EX=x+4*j;i(m,j(4,z[j]+=a[i]*X[j])X+=n)j(4,R_=z[j])),im,in,ER,e2*a,V*x)F(vm,in=kx;R(tx,n,m6(mx,n/16,ri,ai,xi)))F(mm,in=kx;M(ma,n,n/=16;i(ma,m6(mx,n,rV+n*i,ai+ka*i,xi))))
F(mv,R(tx,ma,eR=sr;i(ma,R_=vv(ai+i*nx,x))))F(T,__(_x(ma|mx?(ma?mx?mm:mv:vm)(a,x):te(vv(ai,x)))))
_F(S,Qn(x(a,mn)!=mn)P(!ma,T(a,x))in=kx;R(tx,n,VR=sr;n/=16;j(n/4,Ez[4]={};EA=aV+4*j;EX=xV+4*j;i(mx,j(4,z[j]+=A[j]*X[j])A+=n;X+=n)j(4,R_=z[j]))))F(qm,4==ta&&ta==tx&&ka==mn)G(VM,Qt(!qm(a,x))Qz(i&2!=i)in=kx;_x(r(ez(ne(n,x),x),h(mx,VR=ri+h*n;VX=xi+h*n;$(i,J(4*kx,R_=ae[h]+(e6)X_))J(4*kx,R_=ae[h]+(e6)X_)))))G(MV,Qt(!qm(a,x))0)//Ix+aV[j]
Zg(og,mg,mi,sg,si)g(o3,P(mx,Qz(2!=i)0)_x(2>tx?oB(i,x):!i--?0:4>tx?t(tx,og[i<<1|tx-2](nx,(U)sx)):te(se(x))))Zf(sf,Mg,Mi,Sg,Si)g(s3,Qz(mx)2>tx?sB(i,x):i--?sf[4>tx?i<<1|tx-2:4](x):0)
G(O9,QR P(3>i,a?S(a,x):mx?0:o3(i,x))x=t4(x);_x(6>i?te(se(x)/nx):E3(i-6,a,x)))
#define B3(t,f,a) {t*R=sr;$3(i-6,Xz(R_=f(a<*X)),Xz(R_=f(a>*X)),Xz(R_=f(a==*X)));}
#define A(G,I,E) 4>i?X(4>tx?$3(i,I+Ix,I-Ix,(I)*Ix):$4(i,E+Ex,E-Ex,(E)*Ex,(E)/Ex)):6>i?X(3>tx?5>i?LG(G,*X):MG(G,*X):5>i?LI(I,*X):MI(I,*X)):_x(R(1,nx,$(3>tx,B3(i1,bg,G))B3(i3,bi,I)))
G(av,A(ga-z0,ia-z2,ea-ze))G(a9,P(3<ta,_v(av(i,a,v(x))))ij=ia;6>i?t(tx,$6(i,j+ix,j-ix,j*ix,0,l(j,ix),m(j,ix))):tb($3(i-6,j<ix,j>ix,j==ix)))_g(T_,ax?4>i?x:te((int)x):t_(i,x))
U(zz,A(A_,(i6)A_,(e6)A_),ii,VA,Ux)G(pe,P(1==tx,pB(i,x))Ua=i?*xU:0;Ub=b(1<<bx);x=i--?zz(i^2>i-6,sx-(1<<bx-3),x):_x(ln(-1,nx,x));x=qy(i)?Y(i,x):x;*xU=b&a|~b&*xU;x)
G(A9,it=m(3>i?3:4>i?4:0,m(ta,tx));a=t>ta?T_(t,a):a;x=t>tx?T_(t,x):x;ax?aa?a9(i,a,x):av(i-qy(i)^2>i-6,qy(i)?y(i,x):x,a):aa?av(i,a,x):__(!ma&!mx?zz(i,sa,x):(ma?MV:VM)(i,a,x)))
G(md,P(!i|3<m(ta,tx),A9(2,i?y(3,a):a,x))im=a;P(ax,ti(++i?ix/m:ix%m))Qn(m-1>>16)in=(m+65535)/m;i?X(n*Ix>>16):X(Ix-m*(n*Ix>>16)))
g(uf,QR Qt(2!=tx)0)g(of,QR Qt(5!=bx)0)f(_o,of(1,x))f(o_,of(2,x))f(fq,uf(1,x))f(oq,ax?iz(1,x):of(4,x))f(uq,ax?iz(2,x):uf(5,x))f(gg,0)f(_n,QR ti(_x(mn)))
_F(_A,P(ax,ti(_a(x,a)))Qz(100<nx)Qt(ta!=tx)Qz(5!=bx)tz(3,R2(_a(*X,a))))F(at,P(ax,a_(x,a))P(ma|mx|4==tx,Qn(!qm(a,x))T(a,Z6(x)))Qt(3!=tx)Qz(5!=x(a,bx))tz(ta,R2(ai[*X])))
G(AA,aa?md(i,a,x):(i?_A:at)(a,x))G(NN,Qz(!aa)in=a;P(ax,nz(n,x))im=mn;n>>31^i?(n+=!i*m,_x(ln(n,m-n,x))):(i?n:n-m)+x)f(fl,ax?_v(_t(v(x))):_t(x))
U(e1,_x(R(0,nx,UR=sr;j(nx,R_=a(a_(j,x))))),Uf a,Ux)g(nc,mx?_x(R(0,i,UR=sr;j(i,R_=ln(j*i,i,x)))):mz(i,x))f(n_,P(ax,iz(0,x))Qn(2<nx-2)Ua=nz(pi(x),te(1));_x(nc(*xi,3>nx?a:nc(*xi*xi[1],a))))

F(cut,Qr(!aa)QR Qt(!tx)nc(*ai,x))f(dt,P(4==tx,a8(4,x))0)F(Dt,0)F(Nt,0)f(ff,0)g(io,0)g(is,0)F(tt,0) //R(0,ma+mx,UR=sr;UX=sa;i(ma,R_=X)UX=sx;i(mx,R_=X_)))
F(cat,Qt(2>ta|ta!=tx)a=aa?v(a):a;x=ax?v(x):x;if(ma|mx){a=ma?a:mz(1,a);x=mx?x:mz(1,x);P(ka!=kx,tt(a,x))}in=nx+ne(nx,x);mz(ma+mx,nx+_x(r(hn(ta,na+n)>hx?dz(n,a):a,VR=sr+Na;Xz(R_=*X)))))
Zf(f,ff,rr,_o,o_,fq,0,dt,n_,_e,uq,_n,fl,oq,e_,gg)g(z,4>i|9==i?i?a8(i,x):ti(tx):19>i?f[i-4](x):O9(i-19,0,x))g(ie,Qz(1!=i)of(0,x))
ZF(F,Nt,Dt,0,0,0,0,0,cut,cat,Nt)G(Z,9>i?A9(i,a,x):3>i-11?AA(i-12,a,x):2>i-14?NN(i-14,a,x):19>i?F[i-9](a,x):O9(i-19,a,x))
g(po,P(!i--,a_(nx-1,x))P(17==i,QR Qz(!tx)mz(0,x))P(2==i,Qt(3!=tx)_x(t(tx,pi(x))))Qz(!!i&1<i-4)o3(i?i-4:2,x))g(ps,P(!i--,x)Qz(mx)P(2>tx,sB(i,x))Qz(!!i&1<i-4)s3(i?i-4:2,x))
Zg(g,ie,pe,io,po,is,ps)G_(k,P(61>i,32>i?tn(i,a):a?Z(i-33,a,x):z(i-33,x))QR Qz(!aa)i-=61;!i&9>a-11?e1(f[a-4],x):g[2*i|pa](a,x))
