this.addEventListener("install",e=>{
 e.waitUntil(
  caches
   .open("v1")
   .then((cache)=>
    cache.addAll([
     "index.html",
     "../k.wasm",
     "ref",
     "kelas16.png",
     "kelas32.png",
     "queries.k",
     "db"
    ])
   )
  )
})
self.addEventListener('fetch',function(e){e.respondWith(caches.match(e.request).then(r=>r||fetch(e.request)))});
self.addEventListener("activate",e=>{})
self.addEventListener("beforeinstallprompt",e=>{})
