#define Qi Qr(!aa)Qt(3<aa)
#include"a.h"//[rrrtnnnn] bcieg At Cut Dot Equal Func Log Max Num Order Prod Q Res Sum Type Write B GHIJK UV [XYZ] complex(_-1 %-1)
u strlen(const char*);long write(),read();int open(),close(),stat();void*memcpy(),*malloc(),free();G(mc,(u)memcpy(sa,sx,f))ns(w_,write(1,s,n))f(w,127>x?w_(1,&x):w_(strlen(sx),sx))
Zu W;u(t_,ii=n<<lt[t];W+=i;ux=(u)malloc(8+i+1);*xU=t<<24|n<<32;x+8,it,un)f(_t,W-=Nx;free(sx-8);x)f(r_,Ax?x:(++xr,x))f(_r,Ax?x:b(24)&xr?(--xr,x):tx?_t(x):_(X(_r(xu))_t(x)))
int sprintf(char*,const char*s,...);u($i,bs[12];k(sprintf(s,"%d",x),s),int x)u($e,bs[12];k(sprintf(s,"%g",x),s),float x)f(sb,in=0;X(n+=xc)n)
iu(Ua,4>i?t(i,ix):te(ix))iu(Uv,c3(i-2,R2(xc),R3(xc),R4(xi)))
F(vc,++W;sx[nx++]=a;x)F(V,_a(R(tx,na+nx,mc(Na,r,a);mc(Nx,r+Na,x))))F(_C,_x(R(2,0,X(r=vc(a,V(r,xu))))))G(c,R(tx,a,mc(a<<lx,r,x+(f<<lx))))
f(ind,_x(R(3,sb(x),int*s=rI;X(if(xc)*s++=i))))F(C,_a(R0(c(xi,(i+1<nx?xI[i+1]:na)-xi-1,a))))f(C_,in=sx[nx-1];++xr;ua=R1(n==xc);a=_a(c(-1,na,a));*sa=1;C(x,ind(a)))
iu(a,tx?t(tx,ci):r_(xu))u(e,R0(g(a(i,x))),_ g,ux)f(v,r(t_(ax,1),*rU=x))f(n,R(3,x,i(nr,ri=i)))iu(nz,R(ax,i,If(3>ax,i(nr,rc=ix))i(nr,ri=ix)))
f($,px?k(1,"?"):ax?4>ax?$i(ix):$e(ex):lx?e($,x):2>tx?R2(48+xc):x)f($_,Ax||!lx?$(x):tx?_C(32,e($,x)):k(2,".."))f(wx,_x(w_(nx,sx)))f(w$,wx(Ax||tx?vc(10,$_(x)):_C(10,e($_,x))))
#define pq(g,o) f(g,ax?_(x=4>ax?Ua(4,x):x;te(o(ex))):_(x=4>tx?Uv(4,x):x;R4(o(xe))))
f(_s,ax?_(x=2>ax?Ua(2,x):x;t3(-ix,-ex)):_(x=2>tx?Uv(2,x):x;T3(-xc,-xi,-xe)))f(_e,ax?t(1,!ix):R1(ci))
float sqrtf(float),logf(float);float rf(float x){return 1/x;}pq(_p,rf)pq(_q,sqrtf)pq(l,logf)
#define SP(g,o) F(g,ax?aa?uu(c3(ax-2,tc(ia o ix),ti(ia o ix),te(ea o ex))):g(x,a):UU(c3(tx-2,R2(ai o xc),R3(ai o xi),R4(ae o xe))))
#define ME(g,o) F(g,ax?aa?uu(t(1,ia o ix)):M==g?M(_s(x),_s(a)):g(x,a):UU(R1(ai o ci)))
SP(S,+)SP(P,*)ME(M,>)ME(E,==)F(A,_a(_x(R(tx,nx,If(!lx,X(rc=aC[xi]))X(ri=aI[xi])))))F(err,w(a);w(58);w(x);w(10);Q)f(n_,Qr(!ax)Qt(3<ax)Qd(0>ix)n(ix))F(A_,Qr(aa)A(a,x))
F(_A,Qr(aa)QZ)
f(_n,Qr(ax)_x(ti(nx)))F(_N,Qi ax?nz(ia,x):_(Qd(ia>nx)A(x,n(ia))))F(N_,Qi QZ)f(f_,Qr(ax)A(x,R(3,nx,i(nx,ri=nx-1-i))))
f(_v,Qr(ax)_x(t(tx,*xU)))F(V_,a=aa?v(a):a;x=ax?v(x):x;Qt(ta!=tx)_x(V(a,x)))
F(_S,S(a,_s(x)))F(_P,P(a,_p(x)))F(_M,M(x,a))F(_E,_e(E(a,x)))f(d,QZ)f(F_,QZ)F(D,QZ)F(_$,QZ)F(_m,QZ)F(m_,QZ)f(U,QZ)f(o,QZ)f(_o,QZ)f(o_,_o(_e(x)))f(O,QZ)f(_O,QZ)
Z_// +  - *  % &  |   < >  =  ~  $ . !  @   ?  # _  ^ ,  *exp %log &Flip |flop <asc >desc =group ?unique ^order (#= #'=)
f[]={U,_s,_p,l,F_,f_,_o,o_,O,_e, $,d,n_,_v,_O,_n,_q,o,v },
F[]={S,_S,P,_P,_m,m_,_M,M ,E,_E,_$,D,U ,A_,_A,_N,N_,U,V_};Zu G[26];ns(cs,ii=0;W(s[i])Pr(n==s[i++],i)0)
f(z_,10>x-48?t(3,x-48):26>x-97?r_(G[x-97]):cs(x,"+-*%&|<>=~$.!@?#_^,"))s(z,ua=z_(*s++);!*s?a:x(z(s+!pa),Q(x)pa?f[a-1](x):F[z_(*s)-1](a,x)))Zu es();
s(ps,i(13,in=cs(" \"`;()[]{}'/\\"[i],s);Pr(n--,w((u)s);w(10);wx(vc(94,nz(n,tc(32))));w(10);Q))(u)s)
s(ws,ux=92==*s?(u)s:ps(s);Q(x)Q(x=es(sx))x?w$(x):0)s(ts,ux=ps(s);Q(x)in=1e6;uf=ut();i(n,Q(_r(es(sx))))ti((m(f,ut())-f)/eu-4*n/1e6))
s(f1,ii[36];in=!stat(s,i)&&1&i[6]>>15?i[12]:0;Qs(!n,s)R(2,n,ii=open(s,0);read(i,r,n);close(i)))s(f0,ux=f1(s);Q(x)C_(x))s(ls,ux=f0(s);Q(x)ii=-1;W(++i<nx&&nxu)Q(ws(sxu))_x(0))
s(es,92==*s?c4(cs(s[1],"ltw"),0,ls(s+3),ts(s+3),ti(W)):58==s[1]?_(u*a=G+*s-97;_r(*a);*a=z(s+2);0):z(s))
int main(int _,char**a){If(*++a,ls(*a))w((u)"k/naif (c)atw "__DATE__),w(10);bs[64];W(1)w(32),s[read(0,s,64)-1]=0,*s?ws(s):0;}
