#define N6 n6(Nx)
#define X(z) r(rx?(--rx,M(tx,mx,nx)):x,V(Nx,sr,sx,z))
#include"a.h"//%__ll
UV(b2,0)_f(v,ax?R(tx,1,*(U*)sr=*(U*)sx):mx?QZ:mz(1,r_(x)))
F(_a,X=(U)sx;Ub;$3(tx-2,i(N6,P(b=b_(ga==Gx),l(nx,i<<6|iu(b)))),i(N6,P(b=b2(ia==Ix),l(nx,i<<4|iu(b)))),i(N6,P(b=b2(ia<Ix),l(nx,i<<4|iu(b)))));nx)
G(av,X($3(i,ia+Ix,ia-Ix,ia*Ix)))g(pv,Qz(2<i)A=(U)sx-(1<<lx);X($3(i,Ix+Ia,Ix-Ia,Ix*Ia)))
g(e9,$5(i,X(sq(Ex)),X(C(s6,Ex))-(1L<<60),(1L<<60)+X(C(e6,(s6)Ix)),X(l_(Ex)),X(_l(Ex))))g(t_,Qz(4!=i|3!=tx)e9(2,x))
G(nn,Qz('l'!=ia)e9(2+i,x))F(E9,ax?_v(E9(a,v(x))):av(2,te(l_((4>ta?ia:ea)-ze)[0]),e9(4,x)))
g(a9,3<tx|2<i?_v(a9(i,v(x))):ax?3>i?ti($3(i,1+ix,-ix,ix*ix)):tb(!ix):2>i?av(i,!i,x):10>i?QZ:e9(1,x))
//!ma^!mx?MM:VV
G(A9,it=m(3>i?3:4>i?4:0,m(ta,tx));ax?3<t|3==i?_v(A9(i,a,v(x))):ti($3(i,ia+ix,ia-ix,ia*ix)):av(i,t>ta&7>3?te(ia):a,t>tx?t_(t,x):x))
G(md,P(!i|3<m(ta,tx),av(2,i?f1(a):a,x))im=ia;P(tx,ti(++i?ix/m:ix%m))Qz(m-1>>16)in=(m+65535)/m;i?X(n*Ix>>16):X(i6 a=Ix;a-m*(n*a>>16)))
g(z,R(3>x?x?4:3:tx,i,ee=1./i;V(Nr,sr,0,$4(x,I2|j<<4,e*C(e6,I2|j<<4),(e6)(127<<23|(i6)PQ()>>9)-1,3>tx?gx-z0:ix-z2))))
f(n_,z(x,0))
f(o_,P(ax,z(x,1))QZ)
f(_o,P(ax,4>tx?z(x,2):te(ex/0x1p64*PQ()[0]))QZ)
F(mm,QZ)F(vm,QZ)F(mv,QZ)F(vv,QZ)
F(_A,Qt(2>ta|ta!=tx)Qz(100<nx)QZ) 
F(A_,Qz(2>ta|3!=tx)QZ)
F(cut,Qr(!aa|!ax)QZ)
F(cat,a=aa?v(a):a;x=ax?v(x):x;Qz(ta!=tx)QZ)//CC
F(mat,QZ)
G(C3,$3(i-16,cat,cut,mat)(a,x))
G(AA,i-=12;P(aa,(7>ta?md:nn)(i,a,x))ax?i?ti(_a(x,a)):a_(x,a):!i&(ma|mx|4==tx)?(ma?mx?mm:mv:mx?vm:vv)(a,x):(i?_A:A_)(a,x))
G(NN,i-=14;Qr(!aa)P(ax,z(a,x))QZ)
f(_n,Qr(ax)_x(ti(mn)))//f(ff,QZ)f(rr,Qz(2>tx|mx)QZ)
Zf(f,n_,_v,_o,_n,0,o_,v,0)U(e1,_x(r(M(0,0,nx),U*_=sr;i(nx,_[i]=A(a_(i,x))))),Uf A,Ux)g(ie,QZ)G(io,QZ)G(os,QZ)G(f9,QZ)
g_(k,Qr(!tx)4>i|9==i|15==i?a9(i,x):11>i?QZ:19>i?f[i-11](x):f9(i,0,x))
G_(K,Qr(!aa|!tx)27>i?(11>i?A9:14>i?AA:16>i?NN:19>i?C3:f9)(i,a,x):28>i?E9(a,x):29>i?8>a-12?e1(f[a-12],x):(pa?pv:ie)(ia,x):(pa?os:io)(i-29,a,x))
//ZU s9();O2(m,M,i,I)O2(s,S,i,I)O2(s,S,e,E)Zg(of,mi,si,s9)
