k:0+v:0+6#,,x:^d:288;b:(,a),(,b),,c:&b:768#a:&d;b:6#,b0000112;a:1000#&d /b:0+6#,b0000112;a:32000#&d
f::x+g@fyZey:Rx+:d@(vi,:by)(z*cy)'ki,:(z:4^#ki)*ay:Rx
g::x?Mx:a@bf/ax
\t 100g/0



k  35/290 11/140
ga 83/340 29/160



n:#k:0+v:0+6#,,x:@@z:(,a),(,b),,c:&b:768#a:&288;z:6#,z0000112;a:32000#a
f::x+g@fyZey:Rx+:d@(vi,:cy)S6Z(ki,:n.by)*(%48)?(n:#@k).ay:Rx
g::x?Mx:a@zf/ax



\t 100g/0


l2 l3(f32 f16 i8)
cpu gpu npu?
