#include"a.h"//k(c)2024 arthur whitney(l)MIT ! #$%&'()*+,-./:;<=>?@[\]^_{|}~ [rrit]n
g(_M,W-=1<<f;xx=M[f];M[f]=x)Ui(M_,Ux=M[i];x?(W+=1<<i,M[i]=xx,x):30>i?_M(i,M_(i+1))+(2*n0<<i):OO())f(_r,pt?x:M1&rx?(--rx,x):e(if(!Tx)n(_r(xU))_M(mx,x-n0);x))f(r_,pt?x:M1&++rx?x:OO())
g(T,ii=l2(n0+tn(f,x))-l0-1;r(M_(i)+n0,R_=i<<16|f<<24|x<<32))Ui(gi,in=i;R(3,n,i(n,ru=i)))Ui(ge,in=i;R(4,n,i(n,ru=ue((i+.5)/n))))Ui(gE,in=i;K(n,Ua=ue((i+.5)/n)<<32;R(5,n,i(n,rU=a|ue((i+.5)/n)))))
g(a_,ii=f;t(Tx,$6(Tx,XU,1&xb>>i%32,xc,xu,xu,G_(xU))))U(f1,_K(nx,$(a_(i,x))),_ $,Ux)U(fr,_K(nx,$(a,a_(i,x))),_ $,Ua,Ux)G(e2,_K(nx,a2(f,ta?a:AU,tx?x:XU)))
F(dx,if(!Tx)n(XU)Un=Nx;ij=b(l0)&n;a=dn(a,n-=j,x);x+=n;i(j,ac=xc)a+j)F(V_,__(R(Ta,na+nx,dx(dn(r,x(a,Nx),a),x))))g(sS,in=f?nx:0;ij;n(Ua=xU;n+=j=na)_R(a(xx,Ta),n,Ua=r;n(a=dx(a,xU);if(f)*sa++=f)))
f(v_,R(tx,1,*UR=5==tx?_G(x):x))f(_v,_(a_(0,x)))U(ln,R(Tx,n,dn(r,(U)n<<Lx,x+((int)i<<Lx))),ii,in,Ux)F(_V,__(K(na,ln(au,(i+1<na?((u*)a)[i+1]:nx)-au,x))))Ui(c1,v_(tc(i)))g(vc,V_(x,c1(f)))
nS(i$,48>*s?-i$(n-1,s+1):r(0,i(n,r=si%16+10*r)))nS(e$,P(48>*s,N|e$(n-1,s+1))ii=is(101,n,s);ue(n>i?i$(i,s)*E[s[i+1]%16]:n>(i=is(46,n,s))?(n-=i+1,(i$(i,s)*E[n]+i$(n,s+i+1))/E[n]):i$(n,s)))
Ui($i,N&i?1|$i(-i)<<4:r(0l,do r=r<<4|4+i%10;W(i/=10)))ve($e,0>e?1|$e(-e)<<4:1e-9>e?4:1e9<e?52:1>e?3|$e(1/e)<<4:eq((int)e/e)?$i(e):x($i(.5+1e4*e),in=z4(x)-4<<2;2<<n|b(n)&x|(~b(n)&x)<<4))
f($,px?c1(_P[x]):tx?lx?a($3(tx-3,$i(ux),$e(ex),x=_G(x);Ua=$e(ex);x>>=32;a|(14|$e(ex)<<4)<<4*z4(a)),Vv=44+(15&a0(*(V*)&a,I0/2)>>I0%2*4);ns(z4(a),&v)):$(v_(x)):$3(Tx-1,_T(2,48+_b(xu)),10!=x_&&qe(x)?_p(x):x,f1($,x)))
g(t_,x=f-1>Tx?t_(f-1,x):x;$4(f-2,_N(_b(xu)),x,_T(4,C(Ve,(Vi)Ix)),_T(5,Uu)))v1(_t,3>Tx?_N(O+(26>O-65&32)):_T(Tx-1,5>Tx?C(Vi,Ex):sq(_u*_u+u_*u_)))g(T_,tx?t(f,$3(f-3,ux,ue((int)ux),G_(4>tx?(u)T_(4,x):ux))):t_(f,x))
g(v0,_T(f,_u))f(vk,Q(x)it=a(xx,ta);P(!t,x)n(Ua=xU;P(t!=ta,x))Qz(2!=L[t])v0(t,x))g(nz,Vv=1==tx?ux?~u0:u0:3>tx?cx+(V){}:5>tx?u0+ux:U0+_G(x);L(tx,f,v))
v1(uu,P(4<Tx,_T(4,u_))x=4>Tx?t_(4,x):x;_T(5,Uu<<32))v1(no,_($3(Tx-1,N(~Ix),bC(33>O),bI(0==Ix))))V1(j4,Qt(4<Tx)x=4>Tx?t_(4,x):x;_N(sq(Ex)))V1(d_,Qz(3!=Tx)_N(Ix/ua))V1(_d,Qz(3!=Tx)_N(Ix%ua))
f(sb,ii=nx/64;if(nx%64)xU&=b(nx%64);r(0,N6(r+=nb(xU))))f(n_,_R(3,sb(x),u*s=sr;N6(Ua=xU;j(nb(a),*s++=64*i+IU(a)))))f(Ss,Ua=ln(-1,nx,x);cc=*sa=x_;a=x(a,_(bC(c==O)));a=n_(a);x=_V(a,x);n(Ua=xU;(sa)[--na]=0)x)
Us(lf,it[36];!_l((U)s,(U)t)&&1&t[A?1:6]>>15?t[A?24:12]:0)Us(_1,in=lf(s);Qs(!n,s);ii=f_((U)s,0);R(2,n,_w(i,(U)sr,n);_f(i)))Us(_0,Qx(_1)Qd(10!=x_)ii=59==sx[nx-2];if(i)I(--nx,O=o(pmaxub)(B+c0,O))Ss(x))
g(bo,in=sb(x);_(2>f?tb(f?0<n:n==nx):ti(n)))g(bs,Un=0;_R(1,nx,N6(rU=n=X9(n>>63,xU))))g(bp,Un=0;_R(1,nx,N6(Ua=xU;n=n>>63|a<<1;rU=f?$6(f-5,a&n,a|n,~a&n,a&~n,0,a^n):n)))
g(fo,q3(bo)Qz(!f)ii=nx/8;if(nx%8)O=B(nx%8>I2,O,f?u0:~u0);_(t(Tx,$3(f,s_(u,l),s_(u,m),3==Tx?s_(u,a):ue(s_(e,a))))))g(fs,q3(bs)_(3==Tx?S_(u,a):S_(e,a)))
G(aA,Qz(2>f-5)7>f?N($3(Tx-3,a3(I),4>f?a3(E):Ea/Ex,Ve v=ta?U0+_G(a):Ea;$3(f-1,v+Ex,v-Ex,gg(v,Ex)))):3>Tx?bC(b3(Ca,Cx)):bI(b3(Ia,Ix)))
G(aa,5>f?4>tx?ti(a3(i)):te(4>f?a3(e):ea/ex):t(7>f?tx:1,$3(f-5,l(ua,ux),m(ua,ux),b3(ua,ux))))
g(fp,P(Bx,bp(f,x))Ua=6>f-1?xx:0;IF(f,Ur=x-(1<<Lx);Un=R_;R_=UX[-1];x=_(aA(f,x,r));R_=n)x=_(ln(-1,nx,x));ii=0;$3(Tx-1,xc&=254,xc=a,xu=a);x)G(p3,Qd(!pa)P(18==a,Qr(1-f||Tx)sS(0,x))$3(f,fp,fo,fs)(a,x))
G(jJ,ii=ta?:Ta;ij=tx?:Tx;P(!i||!j,e2(f,a,x))it=m(4>f?3:5>f?4:1,m(i,j));a=t>i?T_(t,a):a;x=t>j?T_(t,x):x;P(tx,Qz(!ta)5>tx?aa(f,a,x):_v(jJ(f,a,v_(x))))__(aA(f,a,x)))
F(C_,a=ta?v_(a):a;x=tx?v_(x):x;Qz(Bx)V_(Tx>Ta?t_(Tx,a):a,Ta>Tx?t_(Ta,x):x))F(Ll,C_(a,v_(x)))F(_C,Qr(ta||tx)Qt(3!=Ta||Bx)_V(a,x))F(mm,QZ)F(No,QZ)F(Dt,QZ)f(dt,QZ)
F(A_,Qt(3!=tx)a_(ux,a))F(_A,QZ)G(AA,P(2==ta,ij=a-101;Qd(3==f)j4(f+2*j,x))ta?f&&3==ta?d_(a,x):jJ(3,f?te(1/ea):a,x):qf(a)?z_(&x,a):!tx&&(!Tx||4==Tx)?mm(a,x):(f?A_:_A)(a,x))
G(NN,Qr(!ta||tx)P(1==nx,x=_v(x);tx?nz(ua,x):_K(ua,r_(x)))Qn(ua>nx)_(ln(f?ua:0,f?nx-ua:ua,x)))f(rr,Qz(2!=Tx)_R(2,nx,n(rc=sx[nx-1-i])))f(qr,Qr(1)0)f(ty,t(3,pt?tx:Tx))g(LMS,QZ)F(N_,Qt(3!=ta)_d(ua,x))
f(wd,n_(no(fp(8,x))))f(ff,P(tx?:Tx,uu(x))QZ)f(or,QZ)f(ou,Q(x=or(x))Qt(Bx||2<Lx)A_(x,wd(x)))f(_o,QZ)f(o_,QZ)f(og,QZ)f(_n,_(ti(nx)))
ZU ps(),zs();Us(os,P(!*s||39==*s,0)Qx(zs)x?wx(x):0)Us(ls,Qx(_0)n(Ua=xU;Q(na?os(sa):_(96)))_(0))g(ts,Q(x)Ua=ut();i(f,Q(_r(z_(0,x))))_(ti(((ut()-a)/(A?2.4e3:2.4e6)-f/2e5))))
Us(ys,if(!*s)_k(0);$5(is(*s,4,"ltvw"),ls(s+2),ii=is(B,20,s);si=0;ts(i?zs(s+2):1,ps(s+i+1)),QZ,ti(W),xs(pP)))
f(_z,pt||!Lx?$(x):qf(x)?$(_v(x)):sS(B,f1(_z,x)))f(wx,x=sS(10,px||tx||Tx||qf(x)?v_(_z(x)):f1(_z,x));w_(2,x,nx);_(0))
f(prs,QZ)f(hsh,QZ)
Z_(h,ff,qr,qr,qr,qr,no,dt,gi,qr,qr,gE,_t,ge,v_,hsh)Z_(H,ff,rr,_o,o_,og,no,dt,n_,_v,ou,_n,_t,or,v_,$)G(i3,P(2==Tx,P(f,prs(x))x=vc(0,x);_((ua?_1:_0)(sx)))QZ)G(c3,$3(f,QZ,Qr(Tx)sS(a,x),Qr(!Tx)Ss(vc(a,x))))
g(a1,P(20>f,Qr(px&&17>f-1)$6(f,x,3==tx?++x:jJ(1,ti(1),x),3==tx?--x:jJ(1,ti(-1),x),jJ(3,r_(x),x),j4(-1,x),(tx?h:H)[f-5](x)))LMS(f-20,x))Z_(G,No,Dt,N_,0,0,0,0,_C,C_,qr)
G(a2,P(20>f,P(!f,Ll(a,x))P(pa||px,Qr(13!=f)a1(a,x))10>f?jJ(f,a,x):4>f-13?(15>f?AA:NN)(1&f-1,a,x):G[f-10](a,x))Qz(29>f)f-=29;!f&&9>a-11?vk(f1(H[a-5],x)):$3(ta-2,c3,i3,p3)(f,a,x))U(v,_r(*_);*_=x,U*_,Ux)
U(z_,Ua=x;x=xx;Ur;_W(ij=xc%32;Q(r=*c=$5(xc/32,--c;20>j?j:ti(j-20),j?a1(j,r):(--i,j=xc%32,r_(v(A(),r))),a2(j,r,*++c),--c;r_(*A()),--c;a_(j,a))))*c++,U*_,Ux)f(Bz,0)f(Bd,0)f(Bb,Qz(qg(67,x))0)
Zc*P_=" L OSDE]abCARBK^@`GIHNMc_dQP F J",*_P=":+-*%&|<>=~.!@?#_^,$LMSAVD...'/\\;()[]";f(_p,BL(90+c0,10>O-20,O+28,96<O,O,a0(*(V*)_P,O%32)))f(nv,*sx-=1==*sx/32?32:0;x)f(av,r(rr(x),*sr+=32))
ZU rd(),pz();f(p_,BL(O,10>O-48,O-28,26>O-97,O,a0(*(V*)P_,O-B-(57<O&10)-(90<O&26)-(122<O&27))-B))g(qn,bp(f,bC(1!=O/32&224>O)))f(t3,qg(58,x)?2:qg(46,x)||qg(101,x))
g(u$,_(t(3+f,$3(f,i$(nx,sx),e$(nx,sx),in=is(58,nx,sx);G_(e$(n,sx)|e$(nx-n-1,sx+n+1)<<32)))))f(t$,P(!qg(B,x),u$(t3(x),x))x=vc(B,x);x=Ss(x);it=0;n(t=m(t,t3(xU)))v0(3+t,fr(u$,t,x)))
f(p$,P(!qg(64,x),pz(x))x=f1(pz,Ss(vc(64,x)));a(vc(50,nz(nx-1,tc(64))),V_(a,sS(0,x))))f(Bq,qg(34,x)?bp(0,bC(34==O)):0)f(Bt,bp(5,bC(Vv=10>O-48;v|s(-1,v)&s(1,v)&(B==O|46==O|58==O|101==O))))
f(Bp,qg(65,x)?bp(0,bC(2>O-65)):0)f(Bn,qn(5,x))f(n$,V_(nz(nx-1,tc(77)),x))f(q$,1==nx?_v(x):x)f(Ba,bC(3>O-61))f(a$,av(nv(x)))f(Bv,qn(7,x))f(v$,B==sx[1]?x:av(x))F(pS,n(IF(192>xc,*sa++=xc)a=pS(a,S[xc%32]))a)
Z_(P,Bq,Bt,Bz,Bp,Bd,Bb,Bn,Ba,Bv)Z_(R,q$,t$,0,p$,0,0,n$,a$,v$)Zu n;g(fd,Ua=P[f](x);P(!a,x)Q(a)a=n_(f&&3!=f?bp(10,a):a);r(na?rd(f,a,x):x,_r(a)))
G(rd,it=!f||3==f;c(ij=0;i(na,ik=au-1;r=dn(r,k-j,x+j);j=++i<na?au:nx;Q(S[n]=R[f](ns(j-k-2*t,sx+k+t)))*sr++=(2>f?128:7>f?192:224)+n++)dn(r,nx-j,x+j)))f(pz,P(2>nx,nv(x))i(6,Q(x=fd(3+i,x)))x)
Us(ps,Ux=xs(s);n=1;i(3,Q(x=fd(i,x)))x=p_(x);Qd(qg(0,x))Q(x=pz(x))x=c(pS(r,x));K(n,i?S[i]:x))Us(zs,P(92==*s,ys(s+1))ii=is(s[1],2,": ");P(qa(*s)&&2>i,v(D+*s%32,(i?ps:zs)(s+2));0)Qx(ps)_(z_(0,x)))
int main(int n,char**_){A=(U)$>N;M[29]=m_(0,n0<<30,3,A?0x1042:0x4022,0,0);M_(0);W=0;if(*++_)ls(*_);cc[256];W(1)wc(B),c[_w(0,(U)c,256)-1]=0,*c?os(c):0;}
