#include"v.c"//th*omuv t[.bqgiefs] o[ar] mq vq
G(a2,6>i?5>tx?bc(i,$6(i,b+c,b-c,b*c,0,L(b,c),M(b,c))):bc(e,$6(i,b+c,b-c,b*c,b/c,L(b,c),M(b,c))):t(1,$3(i-6,ia<ix,ia>ix,ia==ix)))ZU o_(it,in);
f(oz,i(256,Oi=i+1)i(30,Zi=x+(64l<<i))0)tn(bn,lu(M(64,Nt)-1)-6)f(z,cc=Nx%64;if(c)xV[Nx/64]&=I0<c;x)g(u_,~b(36)&x|lu(i)<<31|nx/i<<lu(i)|i)U(ln,Q(3>tx)R(tx,n,d0(Nr,sr,sx+(i<<bx))),ii,in,Ux)
g(_M,w-=1<<i;*(U*)x=Zi;Zi=x)Ui(M_,Ux=Zi;P(x,w+=1<<i;Zi=*(U*)x;x)Q(i>29)_M(i,M_(i+1))+(64L<<i))f(_o,_M(hx,(U)sx);Ox=o;o=ox;x)tn(o_,Ux=bn(t,n);U i=o;Q(i>>8)o=Oi;Oi=M_(x);x<<53|i<<36|t(8+t,n))
f(_r,ax?x:rx?(--Ox,x):_(i(!tx*nx,_r(xj))_o(x)))f(r_,++Ox;Q(!rx)x)g(_i,mx?ln(i*vx,vx,x):t(tx,$4(bx,xg,0,xi,xj)))f(v,R(tx,1,*(U*)sr=mx?x:jx))f(_v,_x(_i(0,x)))is(ns,r(o_(3,i),d0(i,sr,s)))
#define V9(g,z) V(g,i(n6(I),Ri=b0(z)),ij,in,iI,UR,GX)
V9(b3,$3(j,gn<Xi,gn>Xi,gn==Xi))V9(B3,GI($3(j,n<X8,n>X8,n==X8)))V9(c9,$4(j,34==Xi,10>Xi-48,26>Xi-97,0<40==Xi))V(BV,i(n9(I),$3(j-4,Ag&Xg,Ag|Xg,~Xg)),ij,ARX)
U(red,Z(1,c9(i,n,u3)),ii,in,Ux)V2(gi,GI(X8),RX)i2(ic,Ua;ii=0;W(!(a=b0(10==Xi)))++i;64*i+iu(a),GX)
G(dD,Q0(a)Qr(ax)Qt(3<tx)sx[nx]=0;x=ms(ns,sx);X(sd=sr;ss=sx;W(s<sx+nx)s+=1+r(ic(s),$(35!=*s&47!=*s,d0(r,d,s);d+=r));r+=d-sr-nx))
//atom over scan +-*%&|<>=~ !@? #_^
F(S,Qt(5-ta|5-tx)im=ua;in=vx;Qn(va-ux)$(mx,Qn(n%16))z(x);_a(_x(ma*mx?u_(m,R(5,m*n,ux*n-1>>16?MM(ux,rax):mm(0,ux,rax))):R(5,ma?m:n,(ma?mv:vm)(rax)))))i2(mz,(bx?mi:mg)(nx,sx),Ux)
G(s,z(x);_x(5>tx?t(tx,(bx?i?si:mi:i?sg:mg)(nx,sx)):a?_a(te(vv(n4(nx),sa,sx))):te((i?se:me)(nx,sx))))G(o3,Qr(ax)P(ta,red(i,ia,x))Qd(1!=a&6!=a|mx)31>i?s(2>a,0,x):X((2>a?sI:mI)(u3)))
f(rr,Qr(mx)Z(tx,(bx?r2:r0)(nx,sr,sx+Nx)))f(ff,Qr(!mx)iI=vx;iJ=ux;Q0(1<<6-bx!=I)u_(I,Z(tx,bx?t2(I,J,sr,sx):t0(I,J,sr,sx))))
G(k2,ax?a2(i,a,x):4>i?X(5>tx?iV(i,ia,u3):eV(i,ea,u3)):Z(1,(bx?B3:b3)(i-6,ia,u3)))
g(u,i>tx?ax?5>i?ti(ix):te(ix):4>tx?u(i,Z(4,ig(u3))):Z(5,ei(u3)):x)G(o7,Q0(1<i-24)Qr(ax|!!a*aa)s(1&i,a?u(5,a):a,a?u(5,x):x))
G(e1,x=u(5,x);ax?_v(e1(i,a,v(x))):_a(14-i?X(a?aa?eV(4,ea,u3):1&i?EV(4,arx):RZ(arx):$4(3&i,sZ,eZ,q_,_q)(u3)):Z(4,ie(u3))))g(k1,2>--i?k2(i,0,u(4,x)):9-i?e1(i,0,x):2>tx?X(BV(0,0,u3)):k2(8,0,x))
G(K2,--i;it=M(3>i?4:4>i?5:1,M(ta,tx));if(!aa){Qt(2>i-4&1<t)Qr(ax?0:!ma^!mx)Qn(na-nx)}a=u(t,a);x=u(t,x);aa?k2(i,a,x):_a(X((4>i?5>tx?IV:EV:BV)(i,arx))))
G(i3,in=ia;x=u(4,x);it=M(ta,tx);ij=12<i;12==i|4<t?12>i?0:k2(2,j?te(1/(5>ta?n:ea)):u(t,a),u(t,x)):!n?4:ax?ti(j?ix/n:ix%n):n>>16?4:2>n?j?x:k2(2,0,x):X(iV(3,!j*n<<16|(b(16)+n)/n,u3)))
G(I3,Qd(12>i)i&=1;P(ax?0:ma|mx,S(i?x:a,i?a:x))$(!i,Qn(na<=(ax?ix:mz(z(x))))Qt(4<tx))Qt(ta<tx)Q0(2-ba)x=ax?x:u(i?ta:4,x);_a(ax?i?ti(s2(ix,na,sa)):_i(ix,a):Z(ta,IV(3,arx))))
//list n#_^ [&|<>= !@?#^] |<>=
g(nz,R(tx,i,ih=ix;gz(3<tx?h:(h|=h<<8,h|h<<16),Nr,sr)))Ui(n,R(4,i,n_(i,sr)))f(s_,Q0(2-nx|4<tx)im=iv(0,x);ij=iv(1,x);Qn(!m|!j|m*j>>20)_x(u_(m,n(m*j))))f(_s,_x(R(4,2,*ru=ux;ru[1]=vx)))
g(v1,$6(i-5,ff(x),rr(x),0,0,0,$7(i-11,(mx?_s:s_)(x),_v(x),0,_x(ti(ux)),0,0,Qr(mx)u_(1,x))))U(m3,_x(u_(n,R(3,63+n*n,j(n,b3(L(2,i),3>i?j:n-1-j,n,sr+n*j,sx)))-63)),ii,in,Ux)
g(g1,im=iz(x);Qn(m>>30|10>i>m)6>i?u_(m,nz(m*m,t(3,1))):10>i?64<m?0:m3(i-7,m,R(3,m,*rV=I0)):$7(i-11,n(m),0,R(5,m,jj(m,sr)),0,0,i3(13,te(m),n(m)),v(x)))
G(no,0)
F(v2,Qt(3>tx)ii=6-bx;i=nx+b(i)>>i<<i;_x(r(bn(ta,na+i)>ha?_a(R(ta,na+i,d0(Na,sr,sa))+nx-i):a+nx,d0(Nx,sr+Na,sx))))
F(v9,Qt(ta-tx)Qr(aa|ma|!ax*mx)v2(a,ax?v(x):x))
g(nt,i>nx?nt(i,v2(x,r_(x))):x+i-nx)G(l3,i-=14;im=iz(a);in=m>>31;P(ax,Q0(i|n)nz(m,x))Q0(1<i|mx)m+=n*nx;i^n?_x(ln(m,nx-L(nx,m),x)):m>>31?x:nt(m,x))G(L3,Qr(!aa)l3(i,a,x))
G_(k,i?r(!tx?:18>i>a?(5>i|10==i|15==i?k1:ax?g1:v1)(i,x):!!a&!ta&29>i?:17-i?(10>i?K2:11>i?no:14>i?aa?i3:I3:17>i?L3:20>i?dD:22>i?e1:29>i?o7:o3)(i,a,x):v9(a,x),$(pr,_a(_r(x)))):a?_r(a):r_(x))
g_(k_,ZU a;i|x?px?o_(i,x):$3(i,(U)sx,Z(1,B3(0,0,u3)),Z(3,gi(u3))):a?ti(w):oz(m(0,a=1l<<36)))
