//wa.js opcode table is generated by ../ai/wa.mk, source is wa_js
//A compiles a(text) to webassembly(uint8array)
let A=(_=>{
let o,O=x=>o.push(...(Array.isArray(x)?x:[x])),E=(l,x)=>{throw new Error("wa: line "+l+": "+x)},
lebu=(x,r,b)=>{r=[];do{b=x&127;r.push((x>>>=7)?b|=128:b)}while(x);return r},                                                         //unsigned i32
lebs=(x,r,b)=>{x|=0;r=[];while(1){b=x&127;x>>=7;if(x==0&&!(b&64)||(x==-1&&(b&64))){r.push(b);break};r.push(b|128)};return r},        //signed i32
lebn=(x,r,b)=>{r=[];while(1){b=Number(x&127n);x>>=7n;if(x==0n&&!(b&64)||(x==-1n&&(b&64))){r.push(b);break};r.push(b|128)};return r}  //signed BitInt

sect=(x,y)=>y.length?(O(x),O(lebu(y.length)),O(y)):0,
vect=x=>[...lebu(x.length),...x.flat()],
typs={"":0,g:1,i:127,j:126,e:125,f:124},
expo=(n,j)=>n.map((x,i)=>[...lebu(x.length),...x.split("").map(x=>x.charCodeAt(0)),2*!i,...lebu(j[i])]),
locs=x=>[0], //todo encode locals

/*o-p-s*/
ops={
ezi:0x45,
eqi:0x46,
nei:0x47,
lti:0x48,
ltu:0x49,
gti:0x4a,
gtu:0x4b,
lei:0x4c,
leu:0x4d,
gei:0x4e,
geu:0x4f,
ezj:0x50,
eqj:0x51,
nej:0x52,
ltj:0x53,
ltl:0x54,
gtj:0x55,
gtl:0x56,
lej:0x57,
lel:0x58,
gej:0x59,
gel:0x5a,
eqe:0x5b,
nee:0x5c,
lte:0x5d,
gte:0x5e,
lee:0x5f,
gee:0x60,
eqf:0x61,
nef:0x62,
ltf:0x63,
gtf:0x64,
lef:0x65,
gef:0x66,
clz:0x67,
ctz:0x68,
pci:0x69,
adi:0x6a,
sui:0x6b,
mui:0x6c,
dvi:0x6d,
dvu:0x6e,
moi:0x6f,
mou:0x70,
ani:0x71,
ori:0x72,
xoi:0x73,
sli:0x74,
sri:0x75,
sru:0x76,
rli:0x77,
rri:0x78,
clj:0x79,
ctj:0x7a,
pcj:0x7b,
adj:0x7c,
suj:0x7d,
muj:0x7e,
dvj:0x7f,
dvl:0x80,
moj:0x81,
mol:0x82,
anj:0x83,
orj:0x84,
xoj:0x85,
slj:0x86,
srj:0x87,
srl:0x88,
rlj:0x89,
rrj:0x8a,
abe:0x8b,
nge:0x8c,
cee:0x8d,
fle:0x8e,
tre:0x8f,
nae:0x90,
sqe:0x91,
ade:0x92,
sue:0x93,
mue:0x94,
dve:0x95,
mie:0x96,
mae:0x97,
cse:0x98,
abf:0x99,
ngf:0x9a,
cef:0x9b,
flf:0x9c,
trf:0x9d,
naf:0x9e,
sqf:0x9f,
adf:0xa0,
suf:0xa1,
muf:0xa2,
dvf:0xa3,
mif:0xa4,
maf:0xa5,
csf:0xa6,
ioj:0xa7,
ioe:0xa8,
uoe:0xa9,
iof:0xaa,
iou:0xab,
joi:0xac,
jou:0xad,
joe:0xae,
loe:0xaf,
jof:0xb0,
lof:0xb1,
eoi:0xb2,
eou:0xb3,
eoj:0xb4,
eol:0xb5,
eof:0xb6,
foi:0xb7,
fou:0xb8,
foj:0xb9,
fol:0xba,
foe:0xbb,
ire:0xbc,
jrf:0xbd,
eri:0xbe,
frj:0xbf,
ixg:0xc0,
ixh:0xc1,
jxg:0xc2,
jxh:0xc3,
jxi:0xc4,
ldi:[0x28,2,0],
ldj:[0x29,3,0],
lde:[0x2a,2,0],
ldf:[0x2b,3,0],
ldg:[0x2c,0,0],
ldb:[0x2d,0,0],
ldh:[0x2e,1,0],
lds:[0x2f,1,0],
sti:[0x36,2,0],
stj:[0x37,3,0],
ste:[0x38,2,0],
stf:[0x39,3,0],
stg:[0x3a,0,0],
sth:[0x3b,1,0],
siz:[0x3f,0],
grw:[0x40,0],
cpy:[0xfc,10,0,0],
fil:[0xfc,11,0],
},
/*o-p-s*/

wa=x=>{
 //parse asm 
 let a,n=0,s,e="",c=[],p=_=>((n?funs.push({sig:addsig(s),code:c,name:n,export:e}):0),[n,s,e,c]=[0,"","",[]]),
 sigs=[],addsig=x=>(sigs.includes(x)?x:sigs.push(x),x), //e.g. ["i:ii",":ij",..]
 funs=[]          //{sig:"i:ii",code:[1,2,..],name:"a","export":"A"}
 x.split("\n").forEach((x,line)=>{
  im=x=>(2>x.length)?E(line,x[0]+" expect immediate"):x[1]
  int=x=>Number.isInteger(x)?x:E(line,"expect integer")
  try{x=x.trim();if(x.length){a=(x.includes(" ")?x.split(" "):[x]);
   ((1<a.length)&&(a[1].includes(":")))?(p(),n=a[0],s=a[1],e=((3>a.length)?"":(3==a.length)?a[0]:a[3]))
   :("get"==a[0])?c.push(32,...lebu(int(Number(im(a)))))
   :(x in ops)?(Array.isArray(ops[x])?c.push(...ops[x]):c.push(ops[x]))
   :           E(line,"unknown op "+a[0])
  }}catch(e) { E(line,e.message) }
 });p()

 //emit
 o=[0,97,115,109,1,0,0,0] 
 sect( 1,vect(sigs.map((x,r,a)=>([r,a]=x.split(":"),[96,a.length,...a.split("").map(x=>typs[x]),r.length,...r.split("").map(x=>typs[x])]))))
 sect( 2,[]) //imports..
 sect( 3,vect(funs.map(x=>lebu(sigs.indexOf(x.sig))))),
 sect( 4,[]) //table..
 sect( 5,[1,0,1]) //memory: 1segment, unshared, 1block
 sect( 6,[]) //global..
 sect( 7,vect(expo(["memory",...funs.filter(x=>x.export.length>0).map(x=>x.export)], //names
                   [0,...funs.map((x,i)=>(x.export.length?i:-1)).filter(x=>x>=0)]))) //index
 sect( 8,[]) //start
 sect( 9,[]) //elements(indirect function table)
 sect(10,vect(funs.map(x=>((x=[...locs(x),...x.code,11]),[...lebu(x.length),...x])))) //code
 sect(11,[]) //data
 return new Uint8Array(o)}

 return wa})()
