#define I(t,x) W(i<j){((t*)r)[i]=x;++i;}
#include"v.h"//ABCD.MLGE vv mv sX RX SX DX
D(G,JJ,ZJ Y={-1};ZJ Z={0xc6a4a7935bd1e995};Zu a;if(!a){i(a=8,if(i)Yi=Zi=i)i(1e4,JJ())}Y^=Z;Y^=Z<<14^(Y<<55|Y>>9);Z=Z<<37|Z>>27;(E)(127<<23|(1<<23)-1&(I)(Y+Z))-1)
e(Ae,i(4,z+=S2(i,z))z[15],Ez)e(_v,Ae(r(E0,Ez[4]={};i(n/4,i(4,zi+=*Z++))i(n%4,r+=Zi)i(4,r+=zi))),in,EZ)e(vv,Ae(r(E0,Ez[4]={};i(n/4,i(4,zi+=*Y++**Z++))i(n%4,r+=Yi*Zi)i(4,r+=zi))),in,EY,EZ)
#define fo(m,T,R,g,G) u(R,i(6-m,z=G(z,S##m(i,z)))z[b(6-m)],T z)un(g,R(r(Z2,i(n,r=G(r,Zi)))))
fo(0,G,Ag,ag,GA)fo(0,G,Mg,mg,GM)fo(2,I,Ai,ai,IA)fo(2,I,Mi,mi,IM)un(au,ue(_v(n,Z)))un(sb,Ai(r(Z2,i(n,r+=SB(Zi)))))
V(rX,ee=1/_Q(vv(n4(n),Z,Z)/n-E0)[0];i(n,Ri=e*Zi),in,IR,EZ)V(sX,ee=eu(mi(n,Z));i(n,Ri=E_(Zi-e))e=1/_v(n,R);i(n,Ri*=e),in,ER,EZ)un(p0,ii=n/64;gg=n%64;$(g,Zi&=I0<g);n)
void P_();extern int N;Zu l,m,n;ZI*r,*y,*z;u(mn,m=I;r=R;y=Y;z=Z;n=n6(J),IJ)V(p_,$(N>1&n>=N*512,P_(_))N=r(N,N=1;_(0)),in,_ _)_ w;V(a_,ih=i*n/N;iR=r;Ri=w((i*n+n)/N-h,z+h),ii)
U_(a,P(4>t,UY=Z;ii=n/64;gg=n%64;if(g)Yi&=b(g);sb(n6(p0(n3(n),Z)),Z))Zu r[16];w=$5(6>t?j:14>t|!j?j+2:4,mg,ag,mi,ai,au);p_(mn(0,p0(n<<bt-3,Z),r,0,Z),a_);w(1,r),ij,it,in,IZ)
Vn(n_,I(I,$4(m,I2|16*(int)i,JJ(),iz-Z2,zi)))V_(nx,p_(mn(2>z?z:2,n,R,0,6>tz?z|z<<8|z<<16|z<<24:z),n_),in,IR,Uz)V_(dg,p_(mn(3,n,R,0,Z),n_),in,IR,IZ)V_(r0,i(n6(n),Ri=(6>t?R0:R2)(*--Z)),it,in,IR,IZ)
Vn(b_,I(U,b0($6(m,gy<zg,gy>zg,gy==zg,GI(iy<z_),GI(iy>z_),GI(iy==z_)))))Vn(v_,I(I,$8(m,GB(((U*)z)[i]),c(_z,I),IE(zi),EI(zi),(1<<31)-1&zi,ze*zi,_Q(zi),E_(zi))))
Vn(i_,I(I,$8(m,iy+zi,iy-zi,iy*zi,x(iy%i1*zi/i1,iy/i1?zi-iy/i1*x:x),yi+zi,yi-zi,yi*zi,AT(y,zi,2))))Vn(e_,I(I,$9(m,ey+ze,ey-ze,ey*ze,ey/ze,ye+ze,ye-ze,ye*ze,ye/ze,ye*ze/(1+E_(-ze)))))
//+-*%&|<>=..@^^_^+*%RE ''''''''''..\\_^..%RE//+-*%&|<>=~//abcd.mlge //zzzzzz111..y466eeeeee
V_(av,ii=3>j-6;n=p0(n<<bt-3,Z);19-j?p_(mn(y?i?6>t?j-6:j-3:j+4*!ty:j-12,i&4<t?3+n>>2:n,R,y,Z),y?i?b_:14>t?i_:e_:v_):rX(n,R,Z),ij,it,in,IR,Uy,IZ)
Vm(mv_,I(e,vv(n,y+i*n,z)))Vn(vm_,ER=r+i*n;eY=y;EZ=z+i*n;j-=i;i(j/4,Ez[4]={};i(m,j(4,zj+=Yi*Zj)Z+=n)j(4,*R++=zj)Z-=m*n-4)i(j%4,Ri=r(E0,i(m,r+=Yi*Z[n*i])++Z)))
V_(mv,p_(I*mn(I,p0(4*J,Z),R,Y,Z),mv_),IJ)V_(vm,p_(I*mn(I,4*J,R,Y,Z),vm_),IJ)
V(m0,i(I,j(J,Ez[4]={};h(H,k(4,zk+=Y[H*(4*i+k)+h]*Z[J*h+j]))k(4,R[J*(4*i+k)+j]=zk))),iH,IJ)V(m6,i(I,j(4,Ez[4]={};h(64,k(4,zk+=Y[64*(4*i+k)+h]*Z[4*h+j]))k(4,R[4*(4*i+k)+j]+=zk))),IJ)
Vm(mm_,ER=r+4*i*n;eY=y+16*i*l;im=j-i;i(4*m*n,Ri=Z0)i(l/64,j(n/4,m6(m,4,R+j*4,Y,z+j*4+i*64*n))))V_(mm,$(H*J>>16,p_((l=H)*I*mn(I/4,4*J,R,Y,Z),mm_))m0(H,I/4,J/16,R,Y,Z),iH,IJ)
#define mM(n,i) ik=1<<i;h(1<<6-n-1-i,j(k,ii=2*h*k+j;zi=l##n(zi,r(z[i|k],z[i|k]=h##n(zi,r)))))
V_(t0,i(I>>6,j(J>>6,Gz[1<<6];i(1<<6,zi=Zi)i(6,mM(0,i))i(1<<6,Ri=zi))),IJ)V_(t2,i(I>>4,j(J>>4,Gz[1<<4];i(1<<4,zi=Zi)i(4,mM(2,i))i(1<<4,Ri=zi))),IJ)
