#include"v.b"//reduce(MS) mv vm mm atomic(+-* <>=) uniform(+|\QR) AZ(a*~r x+.y)
#define ft(m,o,O,t,T) T##f(O##t,i(6-m,x=O##T(x,S##m(i,x)))x)i2(o##t,O##t(r(z0,i(n##m(n),r=O##T(r,Xi))))[b(6-m)],in,IX)V(o##T,T##z=z2;N##m(z=O##T(z[b(6-m)]-z2,O##t(Xi))),RX)
#define b4(g,a,b,Y...) e2(g,Se(r(ze,n=n2(n);Ez[4]={};i(n/4,i(4,zi+=a*X++))i(n%4,r+=b Xi)i(4,r+=zi)))[15],Y)
b4(se,,,in,EX)b4(vv,*R++*,Ri*,RX)ft(0,s,S,g,G)ft(0,m,M,g,G)ft(2,m,M,i,I)ft(2,s,S,i,I)e2(me,ii=mi(n,X);*(e2*)&i,in,EX)i2(s2,i(n2(n),Ub=b2(m==Xi);P(b,16*i|iu(b)))n,im,in,IX)
V0(b3,1&$3(m,c<Xg,c>Xg,c==Xg),im,cc,RX)V0(B3,1&GI($3(m,j<X8,j>X8,j==X8)),im,ij,RX)
V2(iV,$4(m,j+X6,j-X6,j*X6,x((i1)j*X6>>16,j>>16?X6-(j>>16)*x:x)),im,ij,RX)V2(eV,$4(m,e+Xi,e-Xi,e*Xi,e/Xi),im,ee,RX)
V0(d0,Xi,RX)V2(ig,IG(X4),RX)V2(ei,EI(Xi),RX)V2(ie,IE(Xi),RX)V(sZ,ee=me(n,X);N2(E(Xi-e))e=1/se(n,R);N2(e*Ri),RX)V2(eZ,E(Xi),RX)V2(q_,Xi*Xi,RX)V2(_q,q(Xi),RX)V2(r2,R2(*--X),RX)V2(dV,e*Xi,ee,RX)
V(RZ,ee=1/q(vv(n,X,X)/n-ze)[0];N2(e*Ai*Xi),EA,RX)V0(BV,!m?Ag&Xg:Ag|Xg,im,EA,RX)V2(IV,$4(m,A6+Xi,A6-Xi,A6*Xi,G2(A,Xi)),im,EA,RX)V2(EV,$5(m,Ai+Xi,Ai-Xi,Ai*Xi,Ai/Xi,Ai*Xi/(1+E(-Xi))),im,EA,RX)
#define M2(K) h(8/K,ik=K;j(k,ii=2*h*k+j;zi=_P(zi,r(zk,zk=P_(zi,r)))))
V(f2,n/=16;j(m/=16,i(n,Ez[16];h(16,zh=X[n*(16*j|h)|i])M2(1)M2(2)M2(4)M2(8)h(16,R[n*(16*i|h)|j]=zh))),im,RX)V2(jj,JJ(),in,ER)V2(nn,I2|16*i,in,ER)V0(gz,m-z2,im,in,ER)
