#include"v.b"//reduce(MS) mv vm mm atomic(+-* <>=) uniform(+|\QR)
#define b4(g,a,b,Y...) e2(g,Se(r(ze,I=n2(I);Ez[4]={};i(I/4,i(4,zi+=a*R++))i(I%4,r+=b Ri)i(4,r+=zi)))[15],Y)
b4(se,,,iI,ER)b4(vv,*X++*,Xi*,iI,ER,EX)
V(vm,e2*a=A;J/=16;i(J/4,Ez[4]={};i(I,j(4,zj+=ai*Xj)X+=J)j(4,*R++=zj)X-=I*J-4)i(J%4,Ri=r(ze,i(I,r+=ai*X[J*i])++X)),iI,EA,iJ,ER,EX)
V(mm,I/=16;i(I,j(J/6,Ez[6]={};h(H,l(6,zl+=A[I*h+i]*X[H*(6*j+l)+h]))l(6,R[I*(6*j+l)+i]=zl))),iI,iJ,iH,EA,eX,ER)
V(mv,J/=16;er=R;i(I,ri=vv(J,A+J*i,X)),iI,EA,iJ,ER,EX)
#define ft(m,o,O,t,T) T##f(O##t,i(6-m,x=O##T(x,S##m(i,x)))x)i2(o##t,O##t(r(z0,i(n##m(n),r=O##T(r,Xi))))[b(6-m)],in,IX)V(o##T,T##z=z2;N##m(z=O##T(z[b(6-m)]-z2,O##t(Xi))),RX)
ft(0,s,S,g,G)ft(0,m,M,g,G)ft(2,m,M,i,I)ft(2,s,S,i,I)e2(me,ii=mi(n,X);*(e2*)&i,in,EX)i2(s2,i(n2(n),Ub=b2(m==Xi);P(b,16*i|iu(b)))n,im,in,IX)
V0(gz,m-z2,im,in,ER)V0(d0,Xi,RX)V0(r0,R0(*--X),RX)V0(BV,!m?Ai&Xg:Ai|Xg,im,gA,RX)V0(b3,1&$3(m,c<Xg,c>Xg,c==Xg),im,cc,RX)V0(B3,1&GI($3(m,j<X8,j>X8,j==X8)),im,ij,RX)V2(jj,JJ(),in,ER)
V2(nn,I2|16*i,in,ER)V2(r2,R2(*--X),RX)V2(ig,IG(X4),RX)V2(ei,EI(Xi),RX)V2(ie,IE(Xi),RX)V2(eZ,E(Xi),RX)V2(q_,Xi*Xi,RX)V2(_q,q(Xi),RX)V(sZ,ee=me(n,X);N2(E(Xi-e))e=1/se(n,R);N2(e*Ri),RX)
V2(dV,e*Xi,ee,RX)V(RZ,ee=1/q(vv(n,X,X)/n-ze)[0];N2(e*Ai*Xi),EA,RX)V2(iV,$4(m,j+X6,j-X6,j*X6,x((i1)j*X6>>16,j>>16?X6-(j>>16)*x:x)),im,ij,RX)V2(eV,$4(m,e+Xi,e-Xi,e*Xi,e/Xi),im,ee,RX)
V2(IV,$4(m,A6+Xi,A6-Xi,A6*Xi,G2(A,Xi)),im,EA,RX)V2(EV,$5(m,Ai+Xi,Ai-Xi,Ai*Xi,Ai/Xi,Ai*Xi/(1+E(-Xi))),im,EA,RX)
